#ifndef _SS3D_SERVICE_KEY_H_
#define _SS3D_SERVICE_KEY_H_

enum EProxySearchUserIDType
{
	EN_PROXY_USERID_TYPE__UIN = 0,
	EN_PROXY_USERID_TYPE__DID = 1,
	EN_PROXY_USERID_TYPE__UID = 2,
};

enum EClientReqMode
{
    EN_CLIENT_REQ_MODE__HTTP = 0,
    EN_CLIENT_REQ_MODE__TCP,
};

enum EClientUrlEncryptType
{
    EN_CLIENT_REQ_ENTYPE__NO = 0,
    EN_CLIENT_REQ_ENTYPE__YES,
};

enum EContentType
{
    EN_CONTENT_TYPE__STRING = 0,
    EN_CONTENT_TYPE__BJSON,
};

enum EDownNodeType
{
    DOWN_NODE_TYPE__LOCK_SVR = 2,
    DOWN_NODE_TYPE__AWS_PROXY = 3,
    DOWN_NODE_TYPE__DB_PROXY = 4,
    DOWN_NODE_TYPE__EVENT_PROXY = 10,
    DOWN_NODE_TYPE__CACHE_PROXY = 11,
    DOWN_NODE_TYPE__TRANSLATE_PROXY = 12,
    DOWN_NODE_TYPE__DATA_CENTER_PROXY = 13,
    DOWN_NODE_TYPE__EVENT_CENTER = 14,
    DOWN_NODE_TYPE__MAP_SVR_PROXY = 15,
    DOWN_NODE_TYPE__IU = 16,
    DOWN_NODE_TYPE__MAP_SVR_CENTER = 17,

    DOWN_NODE_TYPE__BUFF_ACTION_SVR = 22,
    DOWN_NODE_TYPE__AL_ACTION_SVR = 23,
    DOWN_NODE_TYPE__MARCH_ACTION_SVR = 24,
    DOWN_NODE_TYPE__HU = 25,
    DOWN_NODE_TYPE__REPORT_USER_SVR = 26,
    DOWN_NODE_TYPE__USER_LINKER = 27,

    DOWN_NODE_TYPE__RANK_SVR = 28,
    DOWN_NODE_TYPE__CHAT_SVR = 29,
    DOWN_NODE_TYPE__HU_OP = 30,
    DOWN_NODE_TYPE__PURCHAES_CHECK = 31,
    DOWN_NODE_TYPE__MAIL_USER_SVR = 32,
    DOWN_NODE_TYPE__LOGIN_SVR = 33,

    DOWN_NODE_TYPE__LOGIN_CENTER = 40,
    DOWN_NODE_TYPE__AU_MARCH = 41,    
    DOWN_NODE_TYPE__USER_MGR = 42,

    DOWN_NODE_TYPE__IAP_SVR = 43,

    DOWN_NODE_TYPE__NOTIC_PUSH_SVR = 44,

    DOWN_NODE_TYPE__THEME_EVENT_PROXY = 45,

    DOWN_NODE_WORNG_NODE_INFO = 999
};

enum EServiceType
{
	//注册部分保留1000开始的key值///////	

	// CLIENT层
	EN_SERVICE_TYPE__CLIENT__BEGIN = 2000,
    EN_SERVICE_TYPE__CLIENT__HEARTBEAT_REQ,  // heart beat
    EN_SERVICE_TYPE__CLIENT__HEARTBEAT_RSP,
    EN_SERVICE_TYPE__CLIENT__COMMAND_REQ,    // command
    EN_SERVICE_TYPE__CLIENT__COMMAND_RSP,
    EN_SERVICE_TYPE__CLIENT__LOGIN_REQ,      // 登录请求
    EN_SERVICE_TYPE__CLIENT__LOGIN_RSP,
    EN_SERVICE_TYPE__CLIENT__DATA_PUSH_REQ,  // data push
    EN_SERVICE_TYPE__CLIENT__DATA_PUSH_RSP,
    EN_SERVICE_TYPE__CLIENT__CREATE_NEW_PLAYER_REQ, // new player create
    EN_SERVICE_TYPE__CLIENT__CHAT_REQ, //chat
    EN_SERVICE_TYPE__CLIENT__CHAT_RSP,
    EN_SERVICE_TYPE__CLIENT__RANK_REQ, //rank
    EN_SERVICE_TYPE__CLIENT__RANK_RSP,
    EN_SERVICE_TYPE__CLIENT__INC_REFRESH_RSP,
    EN_SERVICE_TYPE__CLIENT__ALL_REFRESH_RSP,

    EN_SERVICE_TYPE__SVR__RANK_REQ,
    EN_SERVICE_TYPE__SVR__RANK_RSP,

    // LINKER层
    EN_SERVICE_TYPE__LINKER__BEGIN = 2100,
    EN_SERVICE_TYPE__LINKER__PLAYER_MGR_REQ, // player online status mgr
    EN_SERVICE_TYPE__LINKER__PLAYER_MGR_RSP,

    //LOGIC层
    EN_SERVICE_TYPE__LOGIC__BEGIN = 2200,
	
    // DATA层
    EN_SERVICE_TYPE__DATA__BEGIN = 2300,
    EN_SERVICE_TYPE__DATA__NORMAL_REQ,
    EN_SERVICE_TYPE__DATA__NORMAL_RSP,
    EN_SERVICE_TYPE__DATA__MAP_REQ,
    EN_SERVICE_TYPE__DATA__MAP_RSP,
    EN_SERVICE_TYPE__DATA__REPORT_REQ,
    EN_SERVICE_TYPE__DATA__REPORT_RSP,
    EN_SERVICE_TYPE__DATA__MAIL_REQ,
    EN_SERVICE_TYPE__DATA__MAIL_RSP,
    EN_SERVICE_TYPE__DATA__ACTION_REQ,
    EN_SERVICE_TYPE__DATA__ACTION_RSP,
    EN_SERVICE_TYPE__DATA__TEMP_REQ,
    EN_SERVICE_TYPE__DATA__TEMP_RSP,
    EN_SERVICE_TYPE__DATA__EVENT_REQ,
    EN_SERVICE_TYPE__DATA__EVENT_RSP,
    EN_SERVICE_TYPE__DATA__RANK_REQ,
    EN_SERVICE_TYPE__DATA__RANK_RSP,
    EN_SERVICE_TYPE__DATA__ACCOUNT_REQ,
    EN_SERVICE_TYPE__DATA__ACCOUNT_RSP,


	// hu <---> hs
	EN_HU2HS__BEGIN = 3000,
	EN_SERVICE_TYPE_HU2HS__SEARCH_REQ,
    EN_SERVICE_TYPE_HU2HS__UPDT_REQ,
	EN_SERVICE_TYPE_QUERY_DYNAMODB_REQ, //leyton add 2013-08-20
	EN_SERVICE_TYPE_QUERY_MYSQL_REQ, //leyton add 2013-10-15

	EN_HS2HU__BEGIN = 3100,
	EN_SERVICE_TYPE_HS2HU__SEARCH_RSP,
	EN_SERVICE_TYPE_HS2HU__UPDT_RSP,
	EN_SERVICE_TYPE_QUERY_DYNAMODB_RSP, //leyton add 2013-08-20
	EN_SERVICE_TYPE_QUERY_MYSQL_RSP, //leyton add 2013-10-15

	// hu <---> lock
	EN_HU2LOCK__BEGIN = 4000,
	EN_SERVICE_TYPE_HU2LOCK__GET_REQ,
	EN_SERVICE_TYPE_HU2LOCK__RELEASE_REQ,

	EN_LOCK2HU__BEGIN = 4100,
	EN_SERVICE_TYPE_LOCK2HU__GET_RSP,
	EN_SERVICE_TYPE_LOCK2HU__RELEASE_RSP,

	// hu <---> chat_svr
	EN_HU2CHAT__BEGIN = 5000,
	EN_HU2CHAT__SEARCH_REQ,
	EN_HU2CHAT__UPDT_REQ,

	EN_CHAT2HU__BEGIN = 5100,
	EN_CHAT2HU__SEARCH_RSP,
	EN_CHAT2HU__UPDT_RSP,

    //hu <---> auction_svr     nemo
    EN_HU2AUCTION__BEGIN = 6000,
    EN_HU2AUCTION__PB_REQ,
    
    EN_AUCTION2HU__BEGIN = 6100,
    EN_AUCTION2HU__PB_RSP,


    EN_SERVICE_TYPE_QUERY_EVENT_REQ = 7000,
    EN_SERVICE_TYPE_QUERY_EVENT_RSP,

    // cache
    EN_SERVICE_TYPE_CACHE_REQ = 8000,
    EN_SERVICE_TYPE_CACHE_RSP,

    // translate
    EN_SERVICE_TYPE_TRANSLATE_REQ = 9000,
    EN_SERVICE_TYPE_TRANSLATE_RSP,
    
    // data center
    EN_SERVICE_TYPE_DATA_CENTER_REQ = 10000,  //请求包的service_type
    EN_SERVICE_TYPE_DATA_CENTER_RSP = 10001,  //返回包的service_type

    // IU
    EN_SERVICE_TYPE__IU_REQUEST = 11000,
    EN_SERVICE_TYPE__IU_RESPONSE = 11001,

    //map_svr
    EN_SERVICE_TYPE_MAP_SVR_PROXY_REQ = 20000,
    EN_SERVICE_TYPE_MAP_SVR_PROXY_RSP = 20001,

    EN_SERVICE_TYPE_MAP_SVR_CENTER_REQ = 20010,
    EN_SERVICE_TYPE_MAP_SVR_CENTER_RSP = 20011,

    EN_SERVICE_TYPE_ACTION_PROXY_REQ = 20020,
    EN_SERVICE_TYPE_ACTION_PROXY_RSP = 20021,

    EN_SERVICE_TYPE_ACTION_CENTER_REQ = 20030,
    EN_SERVICE_TYPE_ACTION_CENTER_RSP = 20031,

    EN_SERVICE_TYPE_REPORT_CENTER_REQ = 20050,
    EN_SERVICE_TYPE_REPORT_CENTER_RSP = 20051,

    EN_SERVICE_TYPE_PURCHASE_CHECK_REQ = 20060,
    EN_SERVICE_TYPE_PURCHASE_CHECK_RSP = 20061,

    EN_SERVICE_TYPE_MAIL_CENTER_REQ = 20070,
    EN_SERVICE_TYPE_MAIL_CENTER_RSP = 20071,

    //user_linker-->user_mgr
    EN_SERVICE_TYPE_UL2UM_DATA_SYNC_REQ = 30001,
};

enum EServiceKey
{
	//////////////////////////
	// GLOBAL KEY
	EN_GLOBAL_KEY__BEGIN = 0,
	EN_GLOBAL_KEY__RES_CODE,
	EN_GLOBAL_KEY__RES_COST_TIME,
	EN_GLOBAL_KEY__RES_TOTAL_RES_NUM,
	EN_GLOBAL_KEY__RES_CUR_RES_NUM,
	EN_GLOBAL_KEY__RES_BUF,
	EN_GLOBAL_KEY__REQ_SEQ,
	
	//----dynamodb和mysql使用----
	EN_GLOBAL_KEY__INDEX_NO,
	EN_GLOBAL_KEY__TABLE_NAME,
	EN_GLOBAL_KEY__OPERATOR_NAME,
	EN_GLOBAL_KEY__DB_IDX,	//svrid
	EN_GLOBAL_KEY__AWSTBL_CACHE_MODE,
	EN_GLOBAL_KEY__AWSTBL_ROUTE_FLD,
	EN_GLOBAL_KEY__AWSTBL_ROUTE_THRD,
	EN_GLOBAL_KEY__AWSTBL_HASH_KEY,
	EN_GOLBAL_KEY__AWSTBL_RANGE_KEY,

    //
    EN_GLOBAL_KEY__REQ_BUF = 16,
    EN_GLOBAL_KEY__REQ_TYPE = 17,// 0: string 1: bjson
    EN_GLOBAL_KEY__RES_TYPE = 18,


    //map_svr
    EN_MAP_SVR_KEY__NEED_LOCK = 20,
    EN_MAP_SVR_KEY__NEED_UNLOCK,
    EN_MAP_SVR_KEY__OPERATE,
    EN_MAP_SVR_KEY__SVR_ID,
    EN_MAP_SVR_KEY__REQ_BUF, // 根据不同请求自行解析
    EN_MAP_SVR_KEY__END = 29,

    // IU
    EN_GLOBAL_KEY__IU_CMD = 30,
    EN_GLOBAL_KEY__IU_KEY,
    EN_GLOBAL_KEY__IU_CACHE_MODE,
    EN_GLOBAL_KEY__IU_INDEX_NUM_MAX,
    EN_GLOBAL_KEY__IU_INDEX_BUF,
    EN_GLOBAL_KEY__IU_LEFT_SEARCH_TYPE,
    EN_GLOBAL_KEY__IU_RIGHT_SEARCH_TYPE,
    EN_GLOBAL_KEY__IU_SORT_ORDER,
    EN_GLOBAL_KEY__IU_SERVER_NO,
    EN_GLOBAL_KEY__IU_TABLE_NAME,
    EN_GLOBAL_KEY__IU_OPERATOR_NAME,
    EN_GLOBAL_KEY__IU_RET_CODE,
    EN_GLOBAL_KEY__IU_RET_STR,
    EN_GLOBAL_KEY__IU_RET_VAL,

    EN_ACTION_SVR_KEY__OPERATE = 100,
    EN_ACTION_SVR_KEY__SVR_ID,
    EN_ACTION_SVR_KEY__REQ_BUF,
    EN_ACTION_SVR_KEY__ACTION_TYPE,
    EN_ACTION_SVR_KEY__TABLE_NAME,
    EN_ACTION_SVR_KEY__END = 199,

    // GlobalKEY ---add
    EN_GLOBAL_KEY__TARGET_UID = 20000,
    EN_GLOBAL_KEY__TARGET_TYPE, //enum
    EN_GLOBAL_KEY__TARGET_LIST_SIZE, //UINT32
    EN_GLOBAL_KEY__TARGET_LIST, //id(uint32) list
    EN_GLOBAL_KEY__EXCEPT_TYPE, //enum
    EN_GLOBAL_KEY__EXCEPT_LIST_SIZE,
    EN_GLOBAL_KEY__EXCEPT_LIST, //id(uint32) list
    EN_GLOBAL_KEY__RES_BUF_COMPRESS_FLAG, //flag(int8)
    EN_GLOBAL_KEY__LINKER_CMD_REF, //INT
    EN_GLOBAL_KEY__CLIENT_IP,       //char*
    EN_GLOBAL_KEY__TARGET_SID,      //INT
    EN_GLOBAL_KEY__TARGET_AID,      //UINT32

	//////////////////////////
	// BUSINUSS KEY
	// front <-> hu
	EN_KEY_FRONT2HU__BEGIN = 4000,
	EN_KEY_FRONT2HU__REQ,

	EN_KEY_HU2FRONT__BEGIN = 4100,
	EN_KEY_HU2FRONT__RSP,

	// hu <-> hs
	EN_KEY_HU2HS__BEGIN = 5000,
	EN_KEY_HU2HS__REQ_NUM,
	EN_KEY_HU2HS__REQ_BUF,

	EN_KEY_HS2HU__BEGIN = 5100,
	EN_KEY_HS2HU__RES_DB_TYPE,
	EN_KEY_HS2HU__RES_TBL_TYPE,
	EN_KEY_HS2HU__RES_INDEX_OPENTYPE,
	EN_KEY_HS2HU__RES_COMMAND,

	// hu -> lock
	EN_KEY_HU2LOCK__BEGIN = 6000,
	EN_KEY_HU2LOCK__REQ_KEY_NUM,
	EN_KEY_HU2LOCK__REQ_KEY_LIST,
	EN_KEY_HU2LOCK__REQ_TIMEOUT_US,

    //event_proxy
    EN_KEY_EVENT_PROXY__REQ_JSON = 7000,
    EN_KEY_EVENT_PROXY__REQ_TYPE,

    // cache
    EN_CACHE__BEGIN = 8000,
    EN_CACHE__REQ_SEQ,
	EN_CACHE__NAME,
	EN_CACHE__OPERATE,
	EN_CACHE__KEY,
    EN_CACHE__VALUE_VAILDTIME,
    EN_CACHE__VALUE_DATA,
    EN_CACHE__RES_CODE,
    EN_CACHE__KEY_EXIST,

    // translate
    EN_TRANSLATE__BEGIN = 9000,
    EN_TRANSLATE__REQ_SEQ,
    EN_TRANSLATE__TYPE,
    EN_TRANSLATE__OPERATE,      // 翻译操作
    EN_TRANSLATE__RAW_LANG,     // 翻译的原语言
    EN_TRANSLATE__RESULT_LANG,  // 翻译后的语言
    EN_TRANSLATE__CONTENT,      // 翻译的请求内容
    EN_TRANSLATE__RESULT,       // 翻译的结果内容
    EN_TRANSLATE__RES_CODE,     // 翻译服务的返回码

    // data center
    EN_DATA_CENTER__BEGIN = 10000,
    EN_DATA_CENTER__REQ_SEQ = 10001,  //请求包seq号的key
    EN_DATA_CENTER__REQ_TYPE = 10002,  //请求包类型的key
    EN_DATA_CENTER__REQ_JSON = 10003,  //请求json的key

    EN_DATA_CENTER__RSP_RET_CODE = 10004,  //返回包状态码的key
    EN_DATA_CENTER__RSP_TYPE = 10005,  //返回包type的key
    EN_DATA_CENTER__RSP_JSON = 10006,  //返回json的key
};

enum EHuRequestType
{
    EN_HU_REQUEST_TYPE__UNKNOWN = -1,
    EN_HU_REQUEST_TYPE__GET_IAP_PROMOTE = 0,
    EN_HU_REQUEST_TYPE__RECHARGE = 1,
    EN_HU_REQUEST_TYPE__END
};

enum EHuRequestKey
{
    EN_HU_REQUEST_KEY__REQUEST_SEQ = 10001,
    EN_HU_REQUEST_KEY__REQUEST_TYPE = 10002,
    EN_HU_REQUEST_KEY__REQUEST_JSON = 10003
};

enum EHuResponseKey
{
    EN_HU_RESPONSE_KEY__SEQ = 10001,
    EN_HU_RESPONSE_KEY__RET_CODE = 10004,
    EN_HU_RESPONSE_KEY__REQUEST_TYPE = 10005,
    EN_HU_RESPONSE_KEY__JSON = 10006
};


enum EGlobaLCmd
{
    EN_GLOBAL_CMD__IU__ITEM_UPDATE = 1,
    EN_GLOBAL_CMD__IU__ITEM_DELETE,
    EN_GLOBAL_CMD__IU__ITEM_CREATE,
    EN_GLOBAL_CMD__IU__INDEX_QUERY,
    EN_GLOBAL_CMD__IU__INDEX_RESET,
    EN_GLOBAL_CMD__IU__DATA_SYNC,
};

enum ECacheIUParamType
{
    EN_GLOBAL_DIRECT_CACHE = 0,
    EN_GLOBAL_INDEX_CACHE,
    EN_GLOBAL_INTERVAL_UNDEFINE,
    EN_GLOBAL_INTERVAL_OPEN,
    EN_GLOBAL_INTERVAL_CLOSE,
    EN_GLOBAL_SORT_UNKNOWN,
    EN_GLOBAL_SORT_ASCENDING,
    EN_GLOBAL_SORT_DESCENDING,
};

enum ECacheIURetCode
{
    EN_RET_CODE_REQ_SUCCESS = 0,
    EN_RET_CODE_REQ_FAIL,
    EN_RET_CODE_QUERY_KEY_NOT_EXIST,
    EN_RET_CODE_SYNC_SUCCESS,
    EN_RET_CODE_SYNC_FAIL,
};


// 定义系统的结果码
enum ETshpErrCode
{
    EN_RET_CODE__SUCCESS = 0,
    EN_RET_CODE__ZERO,
    EN_RET_CODE__NO_ERROR, //不按套路出牌的错误码
    EN_RET_CODE__USER_DATA_IS_USING = 100,
    EN_RET_CODE__UNEXPECTED = 1000,


    //client error
    EN_RET_CODE__NET_ERROR = 10000,
    EN_RET_CODE__TROOP_SLOT_LACK,       // 队列不够
    EN_RET_CODE__FORT_SLOT_LACK,        // 队列不够
    EN_RET_CODE__SCOUT_SLOT_LACK,       // 队列不够
    EN_RET_CODE__MARCH_SLOT_LACK,       // 队列不够
    EN_RET_CODE__TROOP_OVER_LOADED,     // march over thrd
    EN_RET_CODE__MARCH_COORD_INVALID,   //
    EN_RET_CODE__LAB_NOT_BUILDED,       //
    EN_RET_CODE__TEXT_INPUT_INVALID,    //
    EN_RET_CODE__TROOP_SIZE_ZERO,       //
    EN_RET_CODE__TO_RESTART_GAME,       //
    EN_RET_CODE__BOOK_MARK_EXIST,       //
    EN_RET_CODE__BOOK_MARK_OVERLOAD,    //

    EN_RET_CODE__NEED_TO_JOIN_ALLIANCE = 10166,
    EN_RET_CODE__CAPTURE_HERO = 10170,
    EN_RET_CODE__IS_RALLY_WAR_ATTACKED_BY_TARGET_ALLIANCE = 10174,
    EN_RET_CODE__ALREADY_HAS_TITLE = 10175,
    EN_RET_CODE__VIP_LEVEL_REACH_THE_TOP = 10177,
    EN_RET_CODE__DRAGON_EXP_REACH_THE_TOP = 10178,
    EN_RET_CODE__HERO_ENERGY_REACH_THE_TOP = 10179,
    EN_RET_CODE__HERO_IS_INVALID_TO_ADD_EXP = 10180,
    EN_RET_CODE__HERO_IS_INVALID_TO_ADD_ENERGY = 10181,

    EN_RET_CODE__CANNOT_CHANGE_SVR_IN_ALLIANCE = 10183,
    EN_RET_CODE__OVER_MAX_MARCH_DISTACE          = 10185,
    EN_RET_CODE__TERMINATE_FRIENDLY_DIPLOMACY_FIRST = 10196,
    EN_RET_CODE__TERMINATE_HOSTILE_DIPLOMACY_FIRST = 10197,

    EN_RET_CODE__BLACKLIST_IS_FULL = 10199,

    EN_RET_CODE__TRANSPORT_SLOT_LACK = 10217,

    EN_RET_CODE__CANNOT_MOVE_CITY_ON_RALLY_WAR = 10222,

    EN_RET_CODE__NEW_PROTECT_CANNOT_MOVE_TO_SPECAIL = 10232,
    EN_RET_CODE__USER_CANNOT_CLEAR,

    //server error
    EN_RET_CODE__TRANSPORT_COORD_INVALID = 20000,
    EN_RET_CODE__ATTACK_COORD_INVALID,
    EN_RET_CODE__REASSIGN_COORD_INVALID,
    EN_RET_CODE__REINFORCE_COORD_INVALID,
    EN_RET_CODE__MOVE_CITY_COORD_INVALID,
    EN_RET_CODE__KNIGHT_UNVAILABEL,
    EN_RET_CODE__PLAYER_NAME_EXIST,
    EN_RET_CODE__CITY_UNDER_PROTECT,
    EN_RET_CODE__RESOURCE_LACK,
    EN_RET_CODE__GEM_LACK,
    EN_RET_CODE__TROOP_LACK_USELESS,//useless
    EN_RET_CODE__MAIL_RECEIVER_INVALID,
    EN_RET_CODE__HAS_LOG_IN,
    EN_RET_CODE__POPULATION_NOT_ENOUGH,
    EN_RET_CODE__ITEM_NOT_ENOUGH,
    EN_RET_CODE__ALLIANCE_NAME_EXIST,
    EN_RET_CODE__YOURSELF_UNDER_PROTECT,
    EN_RET_CODE__GEM_SEQ_NO_INVALID,
    EN_RET_CODE__CAN_NOT_LEAVE_ALLIANCE,
    EN_RET_CODE__POPULATION_OVERLOAD,
    EN_RET_CODE__YOUR_ALLIANCE_MEMBER_OVER_LOAD,        // 联盟成员个数超限,批准加入时使用
    EN_RET_CODE__HAPPINESS_OVERLOAD,
    EN_RET_CODE__KNIGHT_EXP_OVERLOAD,
    EN_RET_CODE__NO_DESTROY_ITEM,
    EN_RET_CODE__PLAYER_NAME_RESERVE,
    EN_RET_CODE__SVR_IS_FULL,  // TODO
    EN_RET_CODE__PLAYER_NOT_IN_ALLIANCE_USELESS,
    EN_RET_CODE__PLAYER_NOT_IN_ALLIANCE, //llt add@20131230,擦,与客户端保持一致
    EN_RET_CODE__ALLIANCE_NOT_EXIST,
    EN_RET_CODE__ALREADY_IN_ALLIANCE,
    // 最高经验物品使用受限
    EN_RET_CODE__MAX_KNIGHT_EXP_ITEM_LIMITED = 20040,

    // occupy的对象必须是资源地，并且资源地上不能有用户或者兵力
    EN_RET_CODE__OCCUPY_COORD_INVALID = 20050,
    EN_RET_CODE__NEW_PLAYER_LIMIT = 20051,

    EN_RET_CODE__REQ_SID_ERROR = 20060,             // sid错误

    EN_RET_CODE__MARKET_IS_BUILDING = 20079,               //  在建造 market 的时候不能点 goods 查看商品
    EN_RET_CODE__TARGET_RALLY_FIELD_NOT_EXIST = 20080,

    //llt add
    EN_RET_CODE__STORE_ITEM_NOT_ENOUGH = 20101, //next
    //EN_RET_CODE__HALL_OF_WAR_NOT_EXIST,
    EN_RET_CODE__TARGET_CONSULATE_NOT_EXIST = 20102, // TODO
    EN_RET_CODE__MARKET_NOT_EXIST = 20103,

    EN_RET_CODE__RALLY_WAR_ONLY_ONE_MARCH = 20115,
    EN_RET_CODE__ALLIANCE_MEMBER_OVER_LOAD = 20117,

    EN_RET_CODE__HAVE_NO_PERMISSION = 20133,
    EN_RET_CODE__FUNCTION_NOT_OPEN = 20161,
    EN_RET_CODE__PEACETIME_ON_NEW_PROTECT = 20194,      //在新手保护期间不能使用peacetime物品

    EN_RET_CODE__REMOVE_LAST_BARRACK_WHILE_TRAIN = 20197,
    EN_RET_CODE__REMOVE_LAST_HOSPITAL_WHILE_TREAN = 20198,

    EN_RET_CODE__PLAYER_LV_NOT_ENOUGH_PUT_ON_EQUIP = 20199,
    EN_RET_CODE__EQUIP_NOT_EXIT = 20200,
    EN_RET_CODE__EQUIP_CAN_NOT_PUT_OFF = 20201,
    EN_RET_CODE__EQUIP_UPGRADE_MATERIAL_NOT_ENOUGH = 20202,
    EN_RET_CODE__EQUIP_UPGRADE_OTHER_EQUIP_DONING = 20203,

    EN_RET_CODE__ABSORB_NOT_SAME_POS_EQUIP = 20204,
    EN_RET_CODE__ATTRIBUTE_NOT_SAME = 20205,
    EN_RET_CODE__EQUIP_NOT_HIGHTEST_LV_OR_QUANLITY = 20206,
    EN_RET_CODE__EQUIP_AGE_NOT_RIGHT = 20207,
    EN_RET_CODE__HAS_POST_ASSIST = 20208,
    EN_RET_CODE__EQUIP_UPGRADING = 20209,
    EN_RET_CODE__ABSORT_TIME_MAX = 20210,
    EN_RET_CODE__INSERT_IDX_NOT_RIGHT = 20211,
    EN_RET_CODE__CRYSTAL_NOT_ENOUGH = 20212,
    EN_RET_CODE__CRYSTAL_NOT_IN_EQUIP = 20213,
    EN_RET_CODE__EQUIP_NUM_MAX = 20214,
    EN_RET_CODE__MATERIAL_UPGRADE_NOT_ENOUGH = 20215,
    EN_RET_CODE__CRYSTAL_UPGRADE_NOT_ENOUGH = 20216,


    EN_RET_CODE__CAN_NOT_DESTROY_TIME_EFFECT_EQUIP = 20218,
    EN_RET_CODE__HOSPITAL_NOT_EXIST = 20219,
    EN_RET_CODE__REQUEST_CHANGED = 20220,
    EN_RET_CODE__ACTION_NOT_EXIST = 20221,
    EN_RET_CODE__FURE_MAX_QUANLITY_AND_LV = 20222,
    EN_RET_CODE__CAN_NOT_DESTROY_WHILE_UPGRADE = 20223,
    EN_RET_CODE__TWO_BUILDING_ACTION_DOING = 20224,
    

    EN_RET_CODE__HACKER = 25000,
    EN_RET_CODE__HERO_NOT_IN_CITY = 20501,
    EN_RET_CODE__ACTION_DOING_ON_YOU = 20502,
    EN_RET_CODE__NAME_INVALID=20503,
    EN_RET_CODE__CAN_NOT_REMOVE_LAST_BUILDING = 20504,
    EN_RET_CODE__EQUIP_GRIDE_NOT_ENOUGH = 20505,
	EN_RET_CODE__CONSULATE_NOT_EXIST = 20506,
    EN_RET_CODE__CAN_NOT_UDW_TO_MOVE_CRYSTAL = 20507,
    EN_RET_CODE__EQUIP_ON_PLAYER = 20508,
    EN_RET_CODE__ALLIANCE_NAME_BE_USED = 20509,
    EN_RET_CODE__ALLIANCE_NICK_BE_USED = 20510,
    EN_RET_CODE__CANNOT_MEET_THE_DEFEAT_LV = 20511,
    EN_RET_CODE__CANNOT_MOVE_CITY_BY_MARCH_ACTION = 20512,
    EN_RET_CODE__CANNOT_CHANGE_SVR_BY_CITY_NUM = 20513,
    EN_RET_CODE__COMPOSE_DRAGON_LV_NOT_ENOUGH = 20514,
    EN_RET_CODE__RALLYING_TIME_UP = 20515,
    EN_RET_CODE__EMBASSY_IS_FULL = 20516,
    EN_RET_CODE__NO_SLOT = 20517,
    EN_RET_CODE__NO_BLACKSMITH = 20518,

    EN_RET_CODE__SP_CRYSTAL_NOT_ENOUGH = 20519,
    EN_RET_CODE__SOUL_NOT_ENOUGH = 20520,
    EN_RET_CODE__PARTS_NOT_ENOUGH = 20521,
    EN_RET_CODE__DRAGON_STATUS_NOT_RIGHT = 20522,
    EN_RET_CODE__TROOP_LACK = 20523,
    EN_RET_CODE__PLAYER_CHANGE_SVR = 20524, //for 称号授予
    EN_RET_CODE__SVR_CHANGE_ACTION_ERR = 20525,
    EN_RET_CODE__PEACETIME_CANT_REINFORCE = 20526,
    EN_RET_CODE__HAS_INVITED_IN_LIMIT_TIME = 20527,
    EN_RET_CODE__CAN_NOT_INVITE_TARGET = 20528,

    EN_RET_CODE__TRADE_NUM_NOT_ENOUGH = 20529, //nemo add v1.2
    EN_RET_CODE__VIOLET_GOLD_NOT_ENOUGH = 20530, //nemo add v1.2
    EN_RET_CODE__PLAYER_HAS_LEAVE_ALLIANCE = 20531, //WAVE add v1.2
    EN_RET_CODE__TRADE_HAS_BEEN_BACK = 20532, //nemo add v1.2
    EN_RET_CODE__PLAYER_CHANGE_SVR_NORMAL = 20533, //wave add v1.2
    EN_RET_CODE__ALLIANCE_NOT_EXIT_IN_THIS_SVR = 20534, //wave add v1.2
    EN_RET_CODE__PLAYER_HAS_REACH_INVITED_LIMIT = 20535, //wave add v1.2

    EN_RET_CODE__TRADE_TARGET_HAS_GONE = 20536, //nemo add v1.2
    EN_RET_CODE__SAME_TYPE_CRYSTAL = 20537,

    EN_RET_CODE__WALL_NOT_EXIST = 20538,

    EN_RET_CODE__AL_FUND_NOT_ENOUGH = 20539,

    EN_RET_CODE__CHANCELLOR_CAN_NOT_ACCEPT_INVITE = 20540,

    EN_RET_CODE__TARGET_NOT_YOUR_ALLY = 20541,

    EN_RET_CODE__ACTION_HAS_BEEN_RECALL = 20542,

    EN_RET_CODE__THRONE_RESEARCH_NOT_EXIST = 20543,

    EN_RET_CODE__PLAYER_NAME_INVALID = 20544,
    EN_RET_CODE__OTHER_NAME_INVALID = 20545,

    EN_RET_CODE__PLAYER_HAVE_NO_DRAGON = 20546,

    EN_RET_CODE__CAN_NOT_PEACETIME = 20550,
    EN_RET_CODE__RALLY_WAR_ONE_POS_ONLY_ONE_MARCH,

    EN_RET_CODE__CAN_NOT_PEACETIME_ON_SPECIAL = 20552,

    EN_RET_CODE__DRAGON_SHARD_NOT_ENOUGH = 20553,
    EN_RET_CODE__DRAGON_NOT_IN_CITY = 20554,
    EN_RET_CODE__REINFORCE_SAME_PEOPLE = 20555,

    EN_RET_CODE__FRIEND_ALLIANCE_FULL = 20556,
    EN_RET_CODE__HOSTILE_ALLIANCE_FULL = 20557,

    EN_RET_CODE__REINFORCE_ARRIVE_LIMIT = 20558,

    EN_RET_CODE__CANNOT_USER_DRAGON_SHARD = 20559,

    EN_RET_CODE__CAMP_COORD_INVALID = 20560,

    EN_RET_CODE__RALLY_REINFORCE_ARRIVE_LIMIT = 20561,

    EN_RET_CODE__HAS_KICKED_OUT = 20562,
    EN_RET_CODE__BE_KICKING_OUT = 20563,

    EN_RET_CODE__CANNOT_MOVE_CITY_WHEN_DRAGON_NOT_IN_CITY = 20564,

    EN_RET_CODE__CANNOT_BE_KING_WHEN_PEACE_TIME = 20565,
    EN_RET_CODE__KING_CANNOT_USE_PEACE_TIME = 20566,

    EN_RET_CODE__THRONE_NOT_YOUR_ALLY = 20567,

    // only server
    EN_RET_CODE__ERROR_COMMAND = 30000,
    EN_RET_CODE__REQ_PARAM_ERROR,               // 请求参数错误
    EN_RET_CODE__ACCOUNT_HAS_USED,
    EN_RET_CODE__ACCOUNT_RELATED,
    EN_RET_CODE__PACKAGE_LEN_OVERFLOW,
    EN_RET_CODE__GET_SESSION_OVERTIME,
    EN_RET_CODE__PARSE_PACKAGE_ERR,
    EN_RET_CODE__TIMEOUT,
    EN_RET_CODE__NO_VALID_DOWNSTEAM,
    EN_RET_CODE__SEND_REQ_FAILED,
    EN_RET_CODE__MYSQL_SQL_CONNECT_FAILED,
    EN_RET_CODE__MYSQL_SQL_SEARCH_FAILED,
    EN_RET_CODE__PROCESS_CMD_ERROR,
    EN_RET_CODE__GET_MAP_FAILED,
    EN_RET_CODE__USER_INFO_INCOMPLETE,
    EN_RET_CODE__DATA_INCOMPLETE,
    EN_RET_CODE__TARGET_NOT_EXIST,
    EN_RET_CODE__TIME_NOT_RIGHT,
    EN_RET_CODE__RESEARCH_DOING,
    EN_RET_CODE__BUILDING_DOING,
    EN_RET_CODE__CANNOT_ATTACT_FRIEND,

    EN_RET_CODE__BLACKLIST_FULL = 30023,
    EN_RET_CODE__TARGET_LEFT,
    EN_RET_CODE__PLAIN_LACK,
    EN_RET_CODE__BLACK_ACCOUNT,//账号被黑名单命中
    EN_RET_CODE__DATA_CHANGE_FAIL,
    EN_RET_CODE__COMPOSE_DOING = 30028, //合成状态
    EN_RET_CODE__USER_CANNOT_CLEAR_OLD,
    EN_RET_CODE__USER_RECOVER_FAIL,
    EN_RET_CODE__ITEM_NOT_SHOW,
    EN_RET_CODE__GET_IAP_FAIL,
    EN_RET_CODE__REPORT_ID_GET_FAIL,
    EN_RET_CODE__BW_EVENT_PROTECT = 30040,
    EN_RET_CODE__PARSE_EVENT_PACKAGE_ERR,
    EN_RET_CODE__SEND_EVENT_REQ_ERR,
    EN_RET_CODE__NOT_IN_ALLIANCE = 30043,
    EN_RET_CODE__IAP_WHITE_MAX = 30044,
    EN_RET_CODE__AL_COMMENT_IS_FULL = 30045,
       
    EN_RET_CODE__GET_EVENT_FAIL = 30046,
    EN_RET_CODE__GET_HISTROY_EVENT_FAIL,

    
    EN_RET_CODE__PARSE_CACHE_PACKAGE_ERR,
    EN_RET_CODE__SEND_CACHE_REQ_ERR,

    EN_RET_CODE__SEND_DATA_CENTER_REQ_ERR,
    EN_RET_CODE__PARSE_DATA_CENTER_PACKAGE_ERR,
    EN_RET_CODE__DATA_CENTER_PACKAGE_FORMAT_ERR,

    EN_RET_CODE__SVR_MERGE_PROTECTED, //合服保护状态
    EN_RET_CODE__SVR_MERGE_TMP,

    EN_RET_CODE__SEND_IAP_SERVER_REQ_ERR,
    EN_RET_CODE__PARSE_IAP_SERVER_PACKAGE_ERR,
    EN_RET_CODE__IAP_SERVER_PACKAGE_FORMAT_ERR,

    EN_RET_CODE__ALREADY_IN_AL_FOR_CREATE_AL = 30060,

    EN_RET_CODE__ADOBE_SAID_NETWORK_ERROR = 31000,
    EN_RET_CODE__CAN_NOT_FIND_MAP_FOR_RANDOM_MOVE = 31001,

    EN_RET_CODE__NOT_KING,

    EN_RET_CODE__AL_POS_NOT_MATCH = 31003,

    EN_RET_CODE__TRIAL_NOT_INIT = 31004,
    EN_RET_CODE__TRIAL_MODE_NOT_NORMAL,
    EN_RET_CODE__TRIAL_MODE_NOT_RAGE,
    EN_RET_CODE__TRIAL_ATK_TIME_NOT_ENOUGH,
    EN_RET_CODE__TRIAL_NO_GIFT,
    EN_RET_CODE__PURCHASE_CHECK_FAIL,
    EN_RET_CODE__PRO_SYS_GET_DATA_FAIL,
    EN_RET_CODE__ACCOUNT_CHANGE_SVR_FAIL,

    //module@user_linker:32000-32999
    EN_RET_CODE__UL_ERROR_BEGIN = 32000,
    //todo
    EN_RET_CODE__UL_PARSE_PACKAGE_ERR,
    EN_RET_CODE__UL_GET_UID_ERROR,
    EN_RET_CODE__UL_GET_RES_BUF_ERROR,
    EN_RET_CODE__UL_ERROR_END = 32999,

    //module@chat:33000-33999
    EN_RET_CODE__CHAT__BEGIN = 33000,
    EN_RET_CODE__CHAT__UPDT_CACHE_ERR,
    EN_RET_CODE__CHAT__FIND_CACHE_ERR,
    EN_RET_CODE__CHAT__BLACK_UID,
    EN_RET_CODE__CHAT__END,

};

#endif
