#ifndef _GAME_COMMAND_DEFINE_H_
#define _GAME_COMMAND_DEFINE_H_

#include "session.h"

#include "process_player.h"
#include "process_account.h"
#include "process_operate.h"

#include <map>

using namespace std;

// todo: 该枚举不能删除,目前并且顺序不能颠倒,用于客户端的json输出,若输出优化了之后顺序可以颠倒
enum EClientReqCommand
{
    EN_CLIENT_REQ_COMMAND__UNKNOW = 0,
    EN_CLIENT_REQ_COMMAND__LOGIN_GET,
    EN_CLIENT_REQ_COMMAND__LOGIN_FAKE,
    EN_CLIENT_REQ_COMMAND__LOGIN_CREATE,
    EN_CLIENT_REQ_COMMAND__GUIDE_FINISH,
    EN_CLIENT_REQ_COMMAND__GUIDE_FINISH_STAGE,
    EN_CLIENT_REQ_COMMAND__SVR_CHANGE,
    EN_CLIENT_REQ_COMMAND__USER_INFO_CREATE,
    EN_CLIENT_REQ_COMMAND__USER_INFO_RECOVER,

    EN_CLIENT_REQ_COMMAND__GEM_RECHARGE,
    // apns_update
    EN_CLIENT_REQ_COMMAND__APNS_UPDATE,
    // apns_token
    EN_CLIENT_REQ_COMMAND__APNS_TOKEN,
    // apns_switch
    EN_CLIENT_REQ_COMMAND__APNS_SWITCH,


    // SVR GET
    EN_CLIENT_REQ_COMMAND__SVR_GET,

    EN_CLIENT_REQ_COMMAND__ITEM_USE,
    EN_CLIENT_REQ_COMMAND__ITEM_BUY,
    EN_CLIENT_REQ_COMMAND__ITEM_BUY_AND_USE,
    EN_CLIENT_REQ_COMMAND__RANDOM_MOVE_CITY,
    EN_CLIENT_REQ_COMMAND__MOVE_CITY,
    EN_CLIENT_REQ_COMMAND__MOVE_CITY_PREPARE,
    EN_CLIENT_REQ_COMMAND__OPEN_ALL_CHEST,


    EN_CLIENT_REQ_COMMAND__BUILDING_UPGRADE,
    EN_CLIENT_REQ_COMMAND__BUILDING_REMOVE,
    EN_CLIENT_REQ_COMMAND__BUILDING_MOVE,
    EN_CLIENT_REQ_COMMAND__BUILDING_EDIT,
    EN_CLIENT_REQ_COMMAND__AGE_UPGRADE,

    EN_CLIENT_REQ_COMMAND__GEM_SPEED_UP,
    EN_CLIENT_REQ_COMMAND__FREE_SPEED_UP,
    EN_CLIENT_REQ_COMMAND__ACTION_CANCLE,


    EN_CLIENT_REQ_COMMAND__RESEARCH_UPGRADE,
    EN_CLIENT_REQ_COMMAND__REMOVE_OBSTACLE,
    EN_CLIENT_REQ_COMMAND__SECOND_BUILD_ACTION,
    EN_CLIENT_REQ_COMMAND__TROOP_TRAIN,
    EN_CLIENT_REQ_COMMAND__FORT_TRAIN,
    EN_CLIENT_REQ_COMMAND__TROOP_DISMISS,
    EN_CLIENT_REQ_COMMAND__FORT_DISMISS,
    EN_CLIENT_REQ_COMMAND__TROOP_HEAL,
    EN_CLIENT_REQ_COMMAND__FORT_HEAL,
    EN_CLIENT_REQ_COMMAND__HOSPITAL_TROOP_ABANDON,
    EN_CLIENT_REQ_COMMAND__DEAD_FORT_ABANDON,

    EN_CLIENT_REQ_COMMAND__TROOP_CANCEL,
    EN_CLIENT_REQ_COMMAND__FORT_CANCEL,
    EN_CLIENT_REQ_COMMAND__HOSPITAL_TROOP_TREAT_CANCEL,
    EN_CLIENT_REQ_COMMAND__DEAD_FORT_HEAL_CANCEL,

    EN_CLIENT_REQ_COMMAND__TROOP_TRAIN_CANCLE,
    EN_CLIENT_REQ_COMMAND__FORT_TRAIN_CANCLE,
    EN_CLIENT_REQ_COMMAND__ALTAR_DEVIVE_TROOP,
    EN_CLIENT_REQ_COMMAND__ALTAR_ABANDON_TROOP,
    EN_CLIENT_REQ_COMMAND__CHANGE_PLAYER_NAME,
    EN_CLIENT_REQ_COMMAND__CHANGE_BASE_NAME,
    EN_CLIENT_REQ_COMMAND__CHANGE_AVATAR,
    EN_CLIENT_REQ_COMMAND__CHANGE_DRAGON_NAME,
    EN_CLIENT_REQ_COMMAND__CHANGE_DRAGON_AVATAR,
    EN_CLIENT_REQ_COMMAND__DRAGON_REVIVE,
    EN_CLIENT_REQ_COMMAND__DRAGON_KILL,
    EN_CLIENT_REQ_COMMAND__DRAGON_RELEASE,
    
    EN_CLIENT_REQ_COMMAND__PLAYER_INFO_GET,
    EN_CLIENT_REQ_COMMAND__SET_GUIDE_FLAG,
    EN_CLIENT_REQ_COMMAND__LOGIN_REWARD,
    EN_CLIENT_REQ_COMMAND__QUEST_START,
    EN_CLIENT_REQ_COMMAND__QUEST_REWARD_COLLECT,
    EN_CLIENT_REQ_COMMAND__REFRESH_TIME_QUEST,
    EN_CLIENT_REQ_COMMAND__MISTERY_GIFT_COLLECT,
    EN_CLIENT_REQ_COMMAND__QUEST_CLAIM,
    EN_CLIENT_REQ_COMMAND__LORD_LEVEL_UP,
    EN_CLIENT_REQ_COMMAND__DRAGON_LEVEL_UP,
    EN_CLIENT_REQ_COMMAND__TASK_CLEAR_FLAG,
    EN_CLIENT_REQ_COMMAND__TASK_OPERATE,
    EN_CLIENT_REQ_COMMAND__RANDOM_REWARD,
    EN_CLIENT_REQ_COMMAND__OPEN_TASK_WINDOW,

    EN_CLIENT_REQ_COMMAND__LORD_SKILL_UPGRADE,
    EN_CLIENT_REQ_COMMAND__LORD_SKILL_RESET,
    EN_CLIENT_REQ_COMMAND__DRAGON_SKILL_UPGRADE,
    EN_CLIENT_REQ_COMMAND__DRAGON_SKILL_RESET,
    EN_CLIENT_REQ_COMMAND__DRAGON_MONSTER_SKILL_UPGRADE,
    EN_CLIENT_REQ_COMMAND__DRAGON_MONSTER_SKILL_RESET,

    EN_CLIENT_REQ_COMMAND__COMPOSE_EQUIP,
    EN_CLIENT_REQ_COMMAND__COMPOSE_MATERIAL,
    EN_CLIENT_REQ_COMMAND__COMPOSE_SOUL,
    EN_CLIENT_REQ_COMMAND__COMPOSE_PARTS,
    EN_CLIENT_REQ_COMMAND__COMPOSE_CRYSTAL,
    EN_CLIENT_REQ_COMMAND__COMPOSE_SP_CRYSTAL,
    EN_CLIENT_REQ_COMMAND__ADD_EQUIP_GRID,
    EN_CLIENT_REQ_COMMAND__CRYSTAL_INSERT,
    EN_CLIENT_REQ_COMMAND__CRYSTAL_REMOVE,
    EN_CLIENT_REQ_COMMAND__PUT_ON_EQUIP,
    EN_CLIENT_REQ_COMMAND__PUT_OFF_EQUIP,
    EN_CLIENT_REQ_COMMAND__EQUIP_DESTROY,

    EN_CLIENT_REQ_COMMAND__BUY_SCROLL,
    EN_CLIENT_REQ_COMMAND__BUY_SCROLL_NEW,
    EN_CLIENT_REQ_COMMAND__SCROLL_DISMISS,

    EN_CLIENT_REQ_COMMAND__TRIAL_INIT,
    EN_CLIENT_REQ_COMMAND__TRIAL_RAGE_MODE,
    EN_CLIENT_REQ_COMMAND__TRIAL_NORMAL_MODE,
    EN_CLIENT_REQ_COMMAND__TRIAL_ATTACK,
    EN_CLIENT_REQ_COMMAND__TRIAL_LUCKY_BAG_NORMAL,
    EN_CLIENT_REQ_COMMAND__TRIAL_LUCKY_BAG_RAGE,
    EN_CLIENT_REQ_COMMAND__TRIAL_GIFT_COLLECT,
    EN_CLIENT_REQ_COMMAND__FINISH_GUIDE,
	
    EN_CLIENT_REQ_COMMAND__RECOVERY_MERGE_USER,

    // ALLIANCE
    EN_CLIENT_REQ_COMMAND__ALLIANCE_CREATE,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_JOIN,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_LEAVE,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_KICKOUT,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_REQUEST_GET,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_ALLOW_JOIN,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_REGECT_JOIN,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_MEMBER_GET,		// 获取count（需要修正alliance信息中的数量），hs获取list；
    EN_CLIENT_REQ_COMMAND__ALLIANCE_POS_CHANGE,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_CHANGE_POLICY,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_CHANGE_DESC,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_CHANGE_NOTIC,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_CHANGE_LANGUAGE,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_WALL_TOP,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_WALL_GET,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_WALL_INSERT,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_WALL_DELETE,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_TASK_HELP_REQUEST,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_TASK_HELP_GET,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_TASK_HELP_SPEED_UP,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_TASK_HELP_SPEED_UP_ALL,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_GIFT_GET,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_GIFT_OPEN,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_GIFT_DEL,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_GIFT_DEL_ALL,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_ITEM_EXCHANGE,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_ITEM_BUY,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_ITEM_MARK,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_ITEM_UNMARK,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_ITEM_MARK_CLEAR,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_DIPLOMACY_GET,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_DIPLOMACY_SET,
	EN_CLIENT_REQ_COMMAND__ALLIANCE_AVATAR_CHANGE,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_ASSIST_SEND,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_ASSIST_GET,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_ASSIST_DEL,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_INFO_GET,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_CHANGE_NICK,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_CHANGE_NAME,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_DUB,

    EN_CLIENT_REQ_COMMAND__ALLIANCE_INVITE,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_INVITED_JOIN,
    EN_CLIENT_REQ_COMMAND__PLAYER_RECOMMAND_GET,
    EN_CLIENT_REQ_COMMAND__AL_HIVE_POS_SHOW, 
    EN_CLIENT_REQ_COMMAND__AL_SET_HIVE_POS,

    EN_CLIENT_REQ_COMMAND__BOOKMARK_GET,
    EN_CLIENT_REQ_COMMAND__BOOKMARK_ADD,
    EN_CLIENT_REQ_COMMAND__BOOKMARK_UPDT,
    EN_CLIENT_REQ_COMMAND__BOOKMARK_DEL,

    EN_CLIENT_REQ_COMMAND__MARCH_SCOUT,
    EN_CLIENT_REQ_COMMAND__MARCH_CAMP,
    EN_CLIENT_REQ_COMMAND__MARCH_ATTACK,
    EN_CLIENT_REQ_COMMAND__MARCH_OCCUPY,
    EN_CLIENT_REQ_COMMAND__MARCH_TRANSPORT,
    EN_CLIENT_REQ_COMMAND__MARCH_REINFORCE,
    EN_CLIENT_REQ_COMMAND__MARCH_REASSIGIN,
    EN_CLIENT_REQ_COMMAND__MARCH_RECALL,
    EN_CLIENT_REQ_COMMAND__MARCH_DRAGON_ATTACK,
    EN_CLIENT_REQ_COMMAND__MARCH_RALLY_ATK,
    EN_CLIENT_REQ_COMMAND__MARCH_RALLY_REINFORCE,
    EN_CLIENT_REQ_COMMAND__MARCH_RALLY_RECALL,
    EN_CLIENT_REQ_COMMAND__MARCH_RALLY_DISMISS,
    EN_CLIENT_REQ_COMMAND__MARCH_RALLY_SLOT_BUY,
    EN_CLIENT_REQ_COMMAND__MARCH_RALLY_INFO,
    EN_CLIENT_REQ_COMMAND__MARCH_RALLY_HISTORY,
    EN_CLIENT_REQ_COMMAND__ABANDON_MANOR,
    EN_CLIENT_REQ_COMMAND__REPATRIATE,
    EN_CLIENT_REQ_COMMAND__RECALL_ALL_REINFORCE,
    EN_CLIENT_REQ_COMMAND__SENDBACK_ALL_REINFORCE,
    
    EN_CLIENT_REQ_COMMAND__MYSTERY_STORE_BUY,
    EN_CLIENT_REQ_COMMAND__MYSTERY_STORE_PASS,
    EN_CLIENT_REQ_COMMAND__MERCENARY_STORE_BUY,

    EN_CLIENT_REQ_COMMAND__BLACKUSER_ADD,
    EN_CLIENT_REQ_COMMAND__BLACKUSER_DEL,

    EN_CLIENT_REQ_COMMAND__THRONE_TAX_SET,

    EN_CLIENT_REQ_COMMAND__MAIL_GET,
    EN_CLIENT_REQ_COMMAND__MAIL_DETAIL_GET,
    EN_CLIENT_REQ_COMMAND__MAIL_READ,
    EN_CLIENT_REQ_COMMAND__MAIL_DEL,
    EN_CLIENT_REQ_COMMAND__MAIL_STAR,
    EN_CLIENT_REQ_COMMAND__MAIL_UNSTAR,
    EN_CLIENT_REQ_COMMAND__MAIL_REWARD_COLLECT,
    EN_CLIENT_REQ_COMMAND__MAIL_SEND,
    EN_CLIENT_REQ_COMMAND__MAIL_SEND_BY_ID,

    EN_CLIENT_OPERATE_COMMAND__MAIL_GET,
    EN_CLIENT_OPERATE_COMMAND__MAIL_SEND,

    EN_CLIENT_REQ_COMMAND__REPORT_GET,
    EN_CLIENT_REQ_COMMAND__REPORT_DETAIL_GET,
    EN_CLIENT_REQ_COMMAND__REPORT_READ,
    EN_CLIENT_REQ_COMMAND__REPORT_DEL,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_REPORT_GET,
    EN_CLIENT_REQ_COMMAND__BROADCAST_GET,
    EN_CLIENT_REQ_COMMAND__ADVERTISEMENT_SEND,

    EN_CLIENT_OPERATE_COMMAND__REPORT_GET,

    EN_CLIENT_REQ_COMMAND__MAP_GET,
    EN_CLIENT_REQ_COMMAND__MAP_BLOCK_GET,
    EN_CLIENT_REQ_COMMAND__MANOR_INFO,
    EN_CLIENT_REQ_COMMAND__PRISON_INFO,

    EN_CLIENT_REQ_COMMAND__MATERIAL_LOTTERY_REFRESH,
    EN_CLIENT_REQ_COMMAND__MATERIAL_LOTTERY_COLLECT,
    EN_CLIENT_REQ_COMMAND__CLEAR_HELP_BUBBLE_STATUS,  //关闭帮助神像的气泡

    EN_CLIENT_REQ_COMMAND__ALLIANCE_GET_INFO,
    EN_CLIENT_REQ_COMMAND__ALLIANCE_RECOMMAND_GET,

    //knight
    EN_CLIENT_REQ_COMMAND__KNIGHT_ASSIGN,

    EN_CLIENT_REQ_COMMAND__PERSON_GUIDE,

    EN_CLIENT_REQ_COMMAND__DRAGON_UNLOCK,

    EN_CLIENT_REQ_COMMAND__ADD_RANDOM_REWARD,
    EN_CLIENT_REQ_COMMAND__GET_RANDOM_REWARD,

    EN_CLIENT_REQ_COMMAND__CLAIM_RANDOM_REWARD,

    EN_CLIENT_REQ_COMMAND__IDOL_ATTACK,
    EN_CLIENT_REQ_COMMAND__GET_IDOL_INFO,

    EN_CLIENT_REQ_COMMAND__THRONE_ATTACK,
    EN_CLIENT_REQ_COMMAND__THRONE_RALLY_WAR,
    EN_CLIENT_REQ_COMMAND__THRONE_REINFORCE,
    EN_CLIENT_REQ_COMMAND__THRONE_DISPATCH,
    EN_CLIENT_REQ_COMMAND__THRONE_DISMISS_KNIGHT_DRAGON,
    EN_CLIENT_REQ_COMMAND__THRONE_DISMISS_REINFORCE,
    EN_CLIENT_REQ_COMMAND__THRONE_DISMISS_ALL,
    EN_CLIENT_REQ_COMMAND__THRONE_RECALL_KNIGHT_DRAGON,
    EN_CLIENT_REQ_COMMAND__THRONE_RECALL_REINFORCE,
    EN_CLIENT_REQ_COMMAND__THRONE_REINFORCE_SPEEDUP,

    EN_CLIENT_REQ_COMMAND__GET_THRONE_INFO,
    EN_CLIENT_REQ_COMMAND__GET_TITLE_INFO,

    EN_CLIENT_REQ_COMMAND__THRONE_DISMISS_TITLE,
    EN_CLIENT_REQ_COMMAND__THRONE_DUB_TITLE,

    EN_CLIENT_REQ_COMMAND__THRONE_ABANDON,

    EN_CLIENT_REQ_COMMAND__REINFORCE_SPEEDUP,

    // operate cmd ：运营相关cmd	
    EN_CLIENT_OPERATE_CMD__LOGIN_GET,
    EN_CLIENT_OPERATE_CMD__LOG,
    EN_CLIENT_REQ_COMMAND__OPRATE_GEM_RECHARGE,
    EN_CLIENT_OPERATE_CMD__ADD_PERSON_AL_GIFT,
    EN_CLIENT_OPERATE_CMD__ADD_ALLIANCE_AL_GIFT,
    EN_CLIENT_OPERATE_CMD__RECALL_TEST,
    EN_CLIENT_OPERATE_CMD__NPC_UPDATE,
    EN_CLIENT_OPERATE_CMD__USER_UPDATE,
    EN_CLIENT_OPERATE_CMD__CHANGE_PLAYER_NAME,
    EN_CLIENT_OPERATE_CMD__CHANGE_CITY_NAME,
    EN_CLIENT_OPERATE_CMD__ADD_TROOP,
    EN_CLIENT_OPERATE_CMD__ADD_FORT,
    EN_CLIENT_OPERATE_CMD__CLEAN_RESOURCE,
    EN_CLIENT_OPERATE_CMD__ADD_RESOURCE,
    EN_CLIENT_OPERATE_CMD__ADD_GEM,
    EN_CLIENT_OPERATE_CMD__ADD_ITEM,
    EN_CLIENT_OPERATE_CMD__SET_ITEM,
    EN_CLIENT_OPERATE_CMD__AL_MEMBER_GET,
    EN_CLIENT_OPERATE_CMD__AL_INFO_GET,
    EN_CLIENT_OPERATE_CMD__AL_CHANGE_CHANCELLOR,
    EN_CLIENT_OPERATE_CMD__RESEARCH_LV_SET,
    EN_CLIENT_OPERATE_CMD__BUILDING_LV_SET,
    EN_CLIENT_OPERATE_CMD__IDENTITY_CHANGE,
    EN_CLIENT_OPERATE_CMD__ADD_AL_LOYALTY_FUND,
    EN_CLIENT_OPERATE_CMD__LIST_BUILDING_POS,
    EN_CLIENT_OPERATE_CMD__ACCOUNT_OPERATE,
    EN_CLIENT_OPERATE_CMD__ALLIANCE_LEAVE,
    EN_CLIENT_OPERATE_CMD__SET_IAP_KEY,
    EN_CLIENT_OPERATE_CMD__SVR_CHANGE,

    EN_CLIENT_OPERATE_CMD__STATISTICAL_OPEN_AL_GIFT,

    EN_CLIENT_OPERATE_CMD__RESET_MAP,
    EN_CLIENT_OPERATE_CMD__CLEAR_NOPLAYER_MAP,

    //nemo add 
    EN_CLIENT_OPERATE_CMD__CREATE_NEW_PLAYER_ALLIANCE,

    EN_CLIENT_OPERATE_CMD__RALLY_PRIDICT_SEND,

    EN_CLIENT_OPERATE_CMD__GEN_TAX_ACTION,

    EN_CLIENT_OP_CMD__RELEASE_DRAGON,

	EN_OPSELF_SET_LUCKY_POINT,
    EN_OPSELF_ADD_REWARD_LIST,
    EN_OPSELF_ADD_AL_REWARD_LIST,
    EN_OPSELF_ADD_AL_REWARD_LIST_NEW,
    EN_OPSELF_CHECK_PLAYER_MAP,
    EN_OPSELF_RECOVER_PLAYER_CITY,
    EN_OPSELF_CHECK_PLAYER_SVR_MAP,
	EN_OPSELF_SET_LOTTERY_RESULT_TYPE,
    EN_OPSELF_SET_LOTTERY_USER_UPDT_TIME,
    EN_OPSELF_SET_LOTTERY_GLOBAL_UPDT_TIME,
    //self_system_operate   ing

    EN_SELF_SYSTEM_OPERATE_SET_GEM_NUM,
    //

    // 自助系统相关的命令字枚举
    EN_OPSELF_CLEAN_EQUIP_GRID,
    EN_OPSELF_SET_GEM,
    EN_OPSELF_SET_RESOURCE,
    EN_OPSELF_SET_TROOP,
    EN_OPSELF_SET_FORT,
    EN_OPSELF_SET_POPULATION,
    EN_OPSELF_SET_ITEM,
    EN_OPSELF_SET_FUND,
    EN_OPSELF_SET_LOYALTY,
    EN_OPSELF_SET_BUILDING_LV,
    EN_OPSELF_SET_POS_BUILDING_LV,
    EN_OPSELF_SET_RESEARCH_LV,
    EN_OPSELF_SET_LAST_LOGIN_TIME,
    EN_OPSELF_SET_CUR_LOYTAL,
    EN_OPSELF_ADD_CLEAR_SCROLL,
    EN_OPSELF_ADD_CLEAR_TROOP,
    EN_OPSELF_ADD_CLEAR_FORT,
    EN_OPSELF_ADD_CLEAR_RESOURCE,
    EN_OPSELF_CLEAR_ITEM,
    EN_OPSELF_SET_ALL_RESEARCH_LV,
    EN_OPSELF_SET_ALL_BUILDING_LV,
    EN_OPSELF_ADD_DEAD_FORT,
    EN_OPSELF_REDUCE_DEAD_FORT,
    EN_OPSELF_ADD_HOS_TROOP,
    EN_OPSELF_REDUCE_HOS_TROOP,
    EN_OPSELF_ADD_ALTAR_TROOP,
    EN_OPSELF_CLEAR_ACCOUNT,
    EN_OPSELF_REDUCE_ALTARTROOP_ABANDON_TIME,
	EN_OPSELF_BREAK_NEW_USER_PROTET,
	EN_OPSELF_SET_VIP_LEVEL,
	EN_OPSELF_SET_VIP_LEFT_TIME,
	EN_OPSELF_GET_BUFFER_INFO,
	EN_OPSELF_JOIN_ALLIANCE,
    
    EN_OPSELF_SET_PLAYER_LV,
    EN_OPSELF_GET_EQUIP_BUFFER_INFO,
    EN_OPSELF_OPEN_CHEST,
    
    EN_OPSELF_DELETE_SET_CONN_LOGIN_DAY,
    EN_OPSELF_DELETE_REFRESH_CONN_LOGIN,
    
    EN_OPSELF_GET_TASK_CONDITION_INFO,
    EN_OPSELF_SET_CONDITION_INFO,
    EN_OPSELF_RESET_FINISH_TASK,
    EN_OPSELF_SET_FINISH_TASK,
    EN_OPSELF_REFRESH_TIME_TASK,
    EN_OPSELF_ADD_WILD,
    EN_OPSELF_CLEAR_GUIDE_FLAG,
    EN_OPSELF_SET_GUIDE_FLAG,
    EN_OPSELF_SET_PERSON_GUIDE_FLAG,
    EN_OPSELF_CLEAN_SECOND_BUILD_ACTION,

    EN_OPSELF_ADD_CRYSTAL,
    EN_OPSELF_ADD_SP_CRYSTAL,
    EN_OPSELF_ADD_MATERIAL,
    EN_OPSELF_ADD_SOUL,
    EN_OPSELF_ADD_PARTS,
    EN_OPSELF_ADD_NORMAL_EQUIP,
    EN_OPSELF_ADD_SP_EQUIP,

    EN_OPSELF_CLEAN_ALL_CRYSTAL,
    EN_OPSELF_CLEAN_ALL_MATERIAL,
    EN_OPSELF_CLEAN_ALL_SOUL,
    EN_OPSELF_CLEAN_ALL_PARTS,
    EN_OPSELF_CLEAN_ALL_EQUIP,

    EN_OPSELF_SET_AL_GIFT_TIME,
    EN_OPSELF_SET_AL_GIFT_LEVEL,

    EN_OPSELF_ADD_RECOMMEND_PLAYER,
    EN_OPSELF_DEL_INVITE_RECORD,
    EN_OPSELF_SET_AL_STAR,
    EN_OPSELF_SET_ASSIST_POST_TIME,
    EN_OPSELF_SET_LAST_UPDATE_TIME,
    EN_OPSELF_RELEASE_DRAGON,
    EN_OPSELF_SET_THRONE_TROOP,
    EN_OPSELF_SET_MAIL_TIME,
    EN_OPSELF_CLEAR_RECOMMEND,
    EN_OPSELF_CLEAR_INVITED_COUNT,

    EN_OPSELF_KILL_SELF_DRAGON,
    EN_OPSELF_SET_DRAGON_EXCUTE_TIME,
    EN_OPSELF_SET_DRAGON_AUTO_RELEASE_TIME,
    EN_OPSELF_CUT_PREPARE_TIME,
    EN_OPSELF_SET_THRONE_TIME,
    EN_OPSELF_RECOVER_THRONE_TIME,
    EN_OPSELF_CAPTURE_DRAGON,

    EN_OPSELF_ADD_GLOBALRES,
    EN_OPSELF_HELP_SELF_ACTION,
    EN_OPSELF_SET_ALTAR_BUFF_TIME,
    EN_OPSELF_ADD_VIP_POINT,
    EN_OPSELF_SET_QUEST_REFRESH_TIME,
    EN_OPSELF_SET_QUEST_FINISH_TIME,
    EN_OPSELF_CHANGE_GLOBALRES,
    EN_OPSELF_SET_GLOBALRES,

    EN_OPSELF_CLEAN_ALL_TREE,
    EN_OPSELF_CLEAR_ALL_BUFF,
    EN_OPSELF_CLEAN_ALL_TITLE,
    EN_OPSELF_SEND_BROADCAST,
    EN_OPSELF_SET_AL_ADS_END_TIME,
    EN_OPSELF_AL_WALL_SET_TIME,

    //nemo add
    EN_OPSELF_SET_TRADE_REFRESH_TIME,
    EN_OPSELF_SET_TRADE_MARCHING_TIME,
    EN_OPSELF_SET_TRADE_WAITING_TIME,
    EN_OPSELF_SET_MYSTERY_STORE_REFRESH_TIME,
    EN_OPSELF_SET_VIOLET_GOLD,
    EN_OPSELF_SET_USER_CREATE_TIME,
    EN_OPSELF_SET_CONTINUE_LOGIN_DAY,
    EN_OPSELF_SET_SEND_NEW_AL_MAIL,

    EN_OPSELF_RESET_MISTERY_GUIDE_FLAG,
    EN_OPSELF_SET_BOUNTY_REFRESH_TIME,
    EN_OPSELF_SET_BOUNTY_NODE_START_NUM,
    EN_OPSELF_SET_PERSONAL_HELP_BUBBLE,
    EN_OPSELF_SET_HELP_BUBBLE_TIMEOUT,
    EN_OPSELF_SET_TAX_TIME,
    EN_OPSELF_CLEAR_SUPPORT_TIME_TAG,
    EN_OPSELF_SET_DRAGON_SHARD,

    //event
    EN_CLIENT_ALL_EVENT_GET,
    EN_CLIENT_EVENT_INFO_GET,
    EN_CLIENT_HISTORY_EVENT_INFO_GET,

    //rating
    EN_CLIENT_REQ_COMMAND__RATING_REWARD_COLLECT,
    EN_CLIENT_OPERATE_CMD__CLEAR_DEAD_PLAYER,
    EN_CLIENT_OPERATE_CMD__BLOCK_HACKER,

    //压测用命令字
    EN_CLIENT_OPERATE_CMD__HU_PRESUSURE_MEASURE,
    EN_CLIENT_OPERATE_CMD__AU_PRESUSURE_MEASURE,
    EN_CLIENT_OPERATE_CMD__CLEAN_AU_PRESUSURE_ACTION,

    // cache测试
    EN_CLIENT_OPERATE_CMD__CACHE_TEST,
    // 测试上报统计信息到agent
    EN_CLIENT_OPERATE_CMD__WARNING_TEST,
    // 测试翻译
    EN_CLIENT_OPERATE_CMD__TRANSLATE_TEST,

    // 客服系统命令字
    EN_CLIENT_OPERATE_COM__SEND_HELP_MAIL,  //发送帮助邮件到客服系统
    EN_CLIENT_OPERATE_CMD__SET_HELP_BUBBLE_STATUS,  //开启帮助神像的气泡

    EN_CLIENT_OP_CMD_SET_SYSTEM_TIME,

    EN_CLIENT_OP_CMD_SET_DRAGON_FLAG,

    EN_CLIENT_OP_CMD__CHANGE_SVR,
    
    EN_OPSELF_SET_DRAGON_LEVEL,
    EN_OPSELF_SET_PLAYER_LEVEL,
    EN_OPSELF_SET_KNIGHT_LEVEL,
    EN_OPSELF_SET_BUFF_FAILURE_TIME,
    EN_OPSELF_SET_MONSTER_WILD_REFRESH_TIME,
    EN_OPSELF_SET_SMOKE_FIRE_DISAPPEAR_TIME,
    EN_OPSELF_SET_CONSECUTIVE,

    EN_CLIENT_OP_CMD__REWARD_ADD_MINUS_FOR_OP,
    EN_OPSELF_SET_TASK_IN_SHOWLIST,

    EN_OPSELF_CLEAR_MONSTER_HIT,
    EN_OPSELF_SET_MAP,
    EN_OPSELF_SET_MAP_EXPIRE,
    EN_OPSELF_SET_RALLY_TIME,
    EN_OPSELF_SET_CAMP_PROTECT_TIME,
    EN_OPSELF_SET_TRIAL_LOCK,
    EN_OPSELF_ADD_AL_GIFT_POINT,
    EN_OPSELF_ADD_AL_LOYALTY_AND_FUND,
    EN_OPSELF_SET_ATTACK_MOVE_TIME,
    EN_OPSELF_SET_RALLY_ATTACK_SLOT_ALL_OPEN,
    EN_OPSELF_SET_AL_GIFT_DISAPPEAR_TIME,

    EN_CLIENT_OP_CMD__PRO_SYS_GET_DATA,
    EN_CLIENT_OP_CMD__GEN_MOVE_ACTION,

    EN_CLIENT_OP_CMD__GEN_IDOL,
    EN_CLIENT_OP_CMD__GEN_THRONE,

    EN_CLIENT_OP_CMD__NPC_UP_TO_10,

    EN_CLIENT_THEME_HISTORY_EVENT_INFO_GET,
    
    EN_OPSELF_ADD_THEME_REWARD_LIST,
    EN_OPSELF_ADD_THEME_AL_REWARD_LIST,

    EN_OPSELF_SET_IDOL_TIME,
    EN_OPSELF_FILL_IDOL_RANK,
    EN_OPSELF_SET_TITLE_EXPIRE_TIME,
    EN_OPSELF_SET_TAX_BEGIN_TIME,
    EN_OPSELF_SET_TAX_INTERVAL_TIME,
    EN_OPSELF_SET_THRONE_TIME_NEW,

    EN_OP_GET_RANK,

    EN_OPSELF_SET_PEACE_TIME,

    EN_CLIENT_REQ_COMMAND__END,
};

enum ECmdProcedureType
{
    EN_UNKNOW_PROCEDURE = 0,
    EN_NORMAL,
    EN_SPECIAL,
};

enum ECmdType
{
    EN_UNKNOW_CMD = 0,
    EN_PLAYER,
    EN_ACTION,
    EN_ITEM,
    EN_MARCH,
    EN_ALLIANCE,
    EN_ACCOUNT,
    EN_RANK,
    EN_CARD,
    EN_OP,
    EN_BOOKMARK,
    EN_MAIL_REPORT,
    EN_MAP,
    EN_EVENT,
};

typedef TINT32 (*Process_Proc)(SSession *pstSession, TBOOL &bNeedResponse);
typedef TVOID (*Process_Output)(SSession *pstSession, TCHAR *pszOut, TUINT32 &udwOutLen);

// 命令字初始化所需的结构体
struct SFunctionSet
{    
    // cmd的名字
    TCHAR szCmdName[DEFAULT_NAME_STR_LEN];
    // cmd主流程分类的标志
    ECmdProcedureType dwProcedureType;
    // cmd分类的标志
    ECmdType dwCmdType;
    // cmd所对应的处理函数
    Process_Proc ProcessProc;
    // cmd所对应的json输出函数
    Process_Output ProcessOutput;
};

struct SCmdInfo
{
    // cmd所对应的枚举
    EClientReqCommand udwCmdEnum;
    // cmd所对应的功能集
    struct SFunctionSet stFunctionSet;    
};

class CClientCmd
{
public:
    // 获取实例
    static CClientCmd *GetInstance();

    // function ===> cmd信息的总初始化函数
    TINT32 Init();

    // function ===> 通过cmd的名字获取cmd的枚举
    TUINT32 GetCommandID(const TCHAR *pszCommand);

    map<EClientReqCommand, struct SFunctionSet> *Get_CmdMap();
    
    map<string, EClientReqCommand> *Get_CmdEnumMap();

    static TUINT32 GetCmdType(TUINT32 udwCommandId);
    
private:
    CClientCmd();     

    // function ===> cmd初始化表的初始化
    TINT32 Init_CmdInfo();
    // function ===> CmdMap的初始化
    TINT32 Init_CmdMap();
    // function ===> CmdEnumMap的初始化
    TINT32 Init_CmdEnumMap();    
    
private:
    static CClientCmd *m_poClientCmdInstance;  

    // cmd初始化表
    struct SCmdInfo m_stszClientReqCommand[EN_CLIENT_REQ_COMMAND__END + 1];
    // CmdMap(cmdenum --> cmdfunction)
    map<EClientReqCommand, struct SFunctionSet> m_oCmdMap;
    // CmdEnumMap(cmdname --> cmdenum)
    map<string, EClientReqCommand> m_oCmdEnumMap;
    

};

#endif
