#ifndef _GAME_COMMON_DEF_H_
#define _GAME_COMMON_DEF_H_

#include "base/common/wtse_std_header.h"
#include "my_define.h"

#define LOTTERY_DATA_FILE			"../data/chance.json"
#define MAX_LOTTERY_CHOICE_NUM		(9)

// des-key：注意最好不要超过8个字节，否则速度将受影响
#define DES_ENCRYPT_KEY_STR					"Ly123!@#"
#define RC4_ENCRYPT_KEY_STR					"Ly1234567!@#$%^&"

//////////////
#define MAX_SVR_NUM     (100)

#define WILD_ID_LOCK_OFFSET         (1000000LL)  //1000 * 1000
#define USER_ID_LOCK_OFFSET         (100000000000LL)    //100,000,000,000
#define ALLIANCE_ID_LOCK_OFFSET     (1000000000000LL)  //1000,000,000,000
#define TASK_ID_LOCK_OFFSET         (0LL)

#define MAP_X_Y_POS_COMPUTE_OFFSET  (10000)

///////////////////////////////
//抽奖相关
#define NORMAL_LOTTERY_REWARD_LIST_LEN 12
#define CAMPAIGN_LOTTERY_REWARD_LIST_LEN 16

//////////////////////////////////////////
// 各field字符串限制
#define MAX_TABLE_NAME_LEN			(32)
#define MAX_TABLE_MAIL_TITLE_LEN	(64)
#define MAX_TABLE_MAIL_CONTENT_LEN	(1000)
#define MAX_TABLE_INSTRUCTION_LEN	(512)
#define MAX_USER_EMAIL_STR_LEN		(128)
#define MAX_GAME_CENTER_ID_LEN	(128)
#define MAX_DEVICE_ID_LEN			(64)
#define MAX_OS_VER_LEN			(128)
#define MAX_PRODUCT_ID_LEN			(64)


#define MAX_PLAYER_DEAD_TIME        (7*24*3600)

#define PLAYER_ALLIANCE_ID_OFFSET   (100)

#define ALLIANCE_POLICY_OFFSET		(1000000)

//#define SP_CRYSTAL_POS 3
#define MAX_CRYSTAL_IN_EQUIPMENT 5
#define MAX_BASE_BUFFER_NUM_IN_EQUIP 100
#define MAX_CRYSTAL_BUFFER 10
#define MAX_COMPOSE_PARTS_USE 6
#define MAX_COMPOSE_MATERIAL_USE 4      
#define MAX_EQUIP_LV 6
#define MAX_RANDOM_VALUE_NUM 101
#define MAX_UPGRADE_ITEM_USE 4      
#define MAX_EQUIP_POS_ON_PLAYER 7

#define MAX_DAILY_ALLIANCE_VIP_QUEST_NUM 10
// notice
#define MAX_NOTICE_TITLE_LEN	(128)
#define MAX_NOTICE_CONTENT_LEN	(512)
#define MAX_NOTICE_URL_LEN		(1024)
#define MAX_NOTICE_NUM			(20)

// diplomacy
#define MAX_DIPLOMACY_NUM	(50)    //total=friendly+hostile
#define MAX_FRIENDLY_DIPLOMACY_NUM  (20)
#define MAX_HOSTILE_DIPLOMACY_NUM   (30)

// wall
#define MAX_WALL_UIN_LEN	(32)
#define MAX_WALL_MSG_LEN	(512)
#define MAX_WALL_MSG_NUM	(20)
#define MAX_WALL_MSG_RESERV_NUM	(40)

//city block
#define MAX_CITY_BLOCK_NUM    (4)

#define WALL_MSG_OFFSET (365*24*3600*10L)

///////////////////////////////////////////
// 系统限制
#define	MAX_GAME_SVR_NUM			(100)
#define MAX_USER_CITY_NUM			(4)
#define MAX_USER_DRAGON_NUM         (4)
#define MAX_USER_CAPTURE_DRAGON_NUM (10)
#define MAX_BUILDING_NUM_IN_ONE_CITY		(500)
#define MAX_BUILDING_SIZE		(1000)
#define CRAD_CITY_BUILDING_BPOS     (80)
#define MAX_ITEM_TYPE_NUM			(2000)
#define MAX_QUEST_NUM				(1000)
#define MAX_WILD_RETURN_NUM			(400)
#define MAX_ACTIVITIES_RETURN_NUM   (100)
#define MAX_PROVINCE_NUM			(16)

#define MAX_ALLIANCE_MEMBER_NUM		(100)
#define MAX_ALLIANCE_REQUEST_NUM    (30)
#define MAX_ALLIANCE_LEADER_NUM		(20)
#define MAX_NEWUSER_PROTECT_TIME_LEN (604800) //7天

#define MAX_RESOURCE_LIMIT_NUM		(2000000000)

#define DEFAULT_BIN_STRUCT_NUM      (1)

#define MAX_PLAYER_LEVEL            (200)

#define MAX_DELAY_TASK_NUM          (1000)
#define MAX_LOTTERY_REWARD_NUM		(16)  //可抽取的物品数量 @charles
#define MAX_LUCKY_POINT_GOAL_NUM	(20)  //最大的幸运点兑换项个数 @charles
#define MAX_GOAL_ITEM_NUM			(10)   //单个兑换项包含的最大物品数量
#define MAX_CHEST_NUM				(3)   //最大的可开启宝箱数 @charles
#define MAX_SPIN_TIME_NUM			(10)  //一次性最多连抽次数
#define MAX_LOTTERY_RAW_DATA_NUM	(200)
#define MAX_MAIL_OPERATE_NODE_NUM   (500)

#define MAX_MONSTER_SHOW_INTERVAL_TIME  (3600*3*300) //WAVE@20160408 // 线上是3天  不要乱动...

#define MAX_ARMY_TIER_LIMIT         (20)

///////////////////////////////////////////
// 表大小限制
#define MAIL_TABLE_NUM			(10)
#define MAIL_USER_TABLE_NUM		(10)
#define REPORT_TABLE_NUM		(10)
#define REPORT_AL_TABLE_NUM		(10)
#define REPORT_USER_TABLE_NUM	(10)

//////////////////////////////////////////////
// user mail & report limit
#define MAX_USER_MAIL_SAVE_NUM		(100)
#define MAX_USER_REPORT_SAVE_NUM	(100)
#define MAX_ALLIANCE_REPORT_RETURN_NUM  (1000)
#define MAX_MAIL_REPORT_TABLE_SIZE  (1000000)

///////////////////////////////////////////
// 等级限制
#define MAX_BUILDING_LEVEL			(50)
#define MAX_RESEARCH_LEVEL			(10)
#define MAX_CARD_RESEARCH_LEVEL		(10)
#define MAX_VIP_LEVEL               (10)

///////////////////////////////////////////
// 用户属性限制
#define MAX_CITY_WILD_NUM			(10)
#define MAX_KNIGHT_NUM              (22)
#define MAX_MAP_BLOCK_RETURN_NUM	(30)
#define MAX_USER_ACTION_PARAM_LEN	(256)
//#define MAX_GOLD_RESERVED_NUM		(5000)
#define MAX_GOLD_RESERVED_NUM		(30000)
#define DEAD_PLAYER_HAPPINESS       (5)


//#define MAX_USER_ACTION_NUM			(100)
//#define MAX_AL_CAN_HELP_TASK_NUM    MAX_USER_ACTION_NUM
//#define MAX_MAP_ACTION_NUM          MAX_USER_ACTION_NUM


#define MAX_CITY_TROOP_TRAIN_LIST_NUM	(30)
#define MAX_CITY_FORT_TRAIN_LIST_NUM	(30)
#define MAX_BOOKMARK_NUM			(100)

#define MAX_USER_STAT_TBL_NUM       (2)
#define MAX_USER_BLACK_TBL_NUM      (2)

// action 表相关限制
#define MAX_USER_ACTION_NUM             (100)
#define MAX_USER_MARCH_NUM              (200)
#define MAX_USER_AL_ACTION_NUM          (100)
#define MAX_REINFORCE_NUM             (100)

#define MAX_USER_EQUIP_NUM          (1000)
#define MAX_USER_CRYSTAL_NUM          (1000)
#define MAX_USER_SOUL_NUM          (1000)
#define MAX_USER_PARTS_NUM          (1000)
#define MAX_USER_MATERIAL_NUM          (1000)

#define MAX_CREATE_USER_REDEFINE_TIME       (3)
///////////////////////////////////////////
// 时间间隔
#define HAPPINESS_CHANGE_TIME_INTERVAL_SEC	(360)
#define WILD_RECOVER_RATE					(10)
///////////////////////////////////////////

//#define MAX_TMP_AL_GIFT_NUM         (50)
#define AL_GIFT_OPEN_RSP_NUM    10

//时间型任务数量
#define MAX_TIME_QUEST_NUM  10
//active quest
#define MAX_ACTIVE_QUEST_NUM  100
//时间型任务刷新间隔
#define TIME_QUEST_REFRESH_INTERVAL (6*60*60)

#define MAX_ACTIVE_POINT_QUEST_NUM  10
#define MAX_CONN_LOGIN_QUEST_NUM  25
#define MAX_LOGIN_TMP_QUEST_NUM 200

#define MAX_AL_HELP_LIST_NUM 6
#define MAX_AL_HELP_NODE_NUM 50

#define MAX_IAP_GIFT_OPER_LIST_NUM  6
#define MAX_IAP_GIFT_OPER_NODE_NUM 50

#define AL_IAP_GIFT_EXPIRE_TIME (24L*60*60*1000*1000)

//
#define AL_LOYALTY_GET_INTERVAL    (12*60*60)
#define AL_FUND_GET_INTERVAL    (12*60*60)
#define MAX_AL_LOYALTY_GET_PER_INTERVAL    5000
#define MAX_AL_FUND_GET_PER_INTERVAL    5000
#define AL_LOYALTY_ADD_PER_TIME 100
#define AL_FUND_ADD_PER_TIME  100


//返回给客户端最多的联盟礼物数
#define MAX_AL_IAP_GIFT_NUM     300
#define MAX_NEW_AL_GIFT_NUM     100
#define MAX_AL_IAP_GIFT_NUM_SVR (MAX_AL_IAP_GIFT_NUM + MAX_NEW_AL_GIFT_NUM)

#define MAX_AL_CONSUME_NUM      100
#define MAX_AL_ASSIST_NUM       100
#define MAX_PLAYER_TIPS_NUM     25
#define MAX_PLAYER_INVITE_NUM     400
#define MAX_EVENT_TIPS_NUM      50
#define MAX_BROADCAST_NUM_EACH_TYPE (10)
#define MAX_BROADCAST_NUM_TOTAL MAX_BROADCAST_NUM_EACH_TYPE //现在只有一类
#define MAX_BROADCAST_EXPIRE_TIME   (10L*24*60*60*1000*1000)
#define MAX_BROADCAST_RESERVE_TIME  (3L*24*60*60*1000*1000)
#define MAX_ADS_EXPIRE_TIME     (24L*60*60*1000*1000)
#define MAX_ADS_QUERY_NUM       (100)
#define MAX_ADS_SPACE           (MAX_ADS_QUERY_NUM+10)

#define MAX_MAIL_RES_NUM 30
#define MAX_REWARD_ITEM_NUM  10
#define MAX_SP_REWARD_ITEM_NUM  1024
#define MAX_ACTIVE_QUEST_REWARD_NUM  5
#define MAX_TIME_QUEST_REWARD_NUM  5

#define MAX_CHALLENGER_REWARD_ITEM_NUM  100

// rally war
#define ALLIANCE_RALLY_WAR_TROOP_MAX_NUM    (50)

//龙处死时限
#define DRAGON_KILL_DEADLINE    (3*24*3600)

#define MAX_TRAIN_TROOP_RELY_ITEM_TYPE (16)
#define MAX_ITEM_NUM			(100000000)

// 连续登录最大的天数
#define CONN_LOGIN_REWARD_NUM 7

#define BW_RES_FRESH_TIME_INTERVAL (10800)

//ResFromUrl res最大长度
#define MAX_JSON_LEN (100<<10)

//Giude Flag
#define MAX_GUIDE_FLAG_NUM 128

//notic task_flag
#define LIMIT_NOTIC_TASK_FLAG_NUM 128

//Giude Flag
#define MAX_MAIL_FLAG_NUM 128

//OLD USER TIME
#define OLD_USER_TIME 1410349155
#define OLD_ITEM_ACTION_TIME 1410533400

#define  EN_MAX_ARMY_NUM (200)

#define MAX_BEAT_NUM	(100)


#define MAX_OWN_CARD_NUM (200)
#define MAX_CAPTURE_CARD_NUM (200)

#define MAX_CARD_SKILL_NUM (10)
#define MAX_CARD_EQUIP_NUM (10)
#define MAX_CARD_ASSIGNED_NUM (4)

#define MASK_INVITE_CODE (900000)
#define MIN_INVITE_CODE (100000)


#define MAX_CARD_MATERIAL_LOTTERY_NUM   (12)
#define MAX_CARD_MATERIAL_LV            (6)
#define MAX_CARD_BASE_MATERIAL_TYPE     (18)
#define EN_TOP_QUEST_NUM_LIMIT          (1536)
#define EN_TASK_NUM_LIMIT          (1536)
#define EN_PERSON_GUIDE_NUM_LIMIT       (512)
#define MAX_TASK_CURR_NORMAL_LIMIT          (6)
#define MAX_TASK_CURR_TIME_LIMIT          (5)
#define MAX_TASK_CONDITION_LIMIT          (5)

#define THRONE_POS                  (2500600)

#define MAX_LEVEL_LIMIT             (200) //lord and dragon

#define EN_CONN_LOGIN_DAY_LIMIT       (30)

#define MAX_ATTRIBUTE_NUM 10

#define MAX_BASE_MATERIAL_TYPE (50)

#define MAX_MAP_WILD_LV     (6)

#define MAX_TRIAL_ATK_TIME  (10)
#define MAX_TRIAL_LUCKY_BAG_NORMAL_NUM  (3)
#define MAX_TRIAL_LUCKY_BAG_RAGE_NUM    (25)
#define MAX_FINISH_GUIDE_LIST_NUM       (100)
#define MAX_REPORT_BUFFER_NUM           (32)

// 是否优化包
#define FILTER_JSON (0)

// mail 分类汇总
#define SYSTEM_NOTICE       (-1000000)
#define SYSTEM_EVENT        (-1000001)
#define SYSTEM_ENCOURAGE    (-1000002)
#define SYSTEM_WAR          (-1000003)
#define SYSTEM_ACTIVITY     (-1000004)
#define SYSTEM_HOLIDAY      (-1000005)
#define SYSTEM_NEW_PLAYER_AL (-1000006)
#define SYSTEM_INVITE       (-1000008)
#define SYSTEM_DIPLOMACY    (-1000009)
#define SYSTEM_SUPPORT      (-1000010)

#define SYSTEM_END          (-2000000)


// 一个服最多拥有多少称号
#define MAX_TITLEINFO_NUM_IN_ONE_SERVER 50

// rally war
#define MAX_RALLY_HISTORY  (50)

#define MAX_SCORE_ID_NUM	(300)  //score id的上限（取决于几个score类型的大小）
#define  MAX_SCORE_LIST_LENGTH  (200)

#define MAX_RECOMMEND_NUM (10)
#define EN_INTIVE_LIMIT_TIME (60*60*24)

#define EN_ASSIST_EXPIRED_TIME (60*60*12)
#define EN_ASSIST_SELF_EXPIRED_TIME (60*60*12)

#define MAX_TRADE_NUM (20)

#define MAX_MYSTERY_PACKAGE_ITEM_NUM (10)
#define MAX_LOCK_ID_LIST_LEN (10)

#define MAX_MYSTERY_PACKAGE_NUM (20)

#define CHEST_CANDIDATE_MAX_NUM (32*40) // 怪物箱子候选集最大容量
#define CHEST_CANDIDATE_TYPE_NUM (20) // 怪物箱子候选集最大种类数
#define CHEST_CANDIDATE_LIST_NUM (40) // 每种材料实际候选容量，和种类数相乘不得大于最大容量
#define CANDIDATE_SEQ_NUM (5)

#define MAX_BLACKLIST_NUM (50)

#define MAX_UNIX_TIME_LIMIT      (2147483647L)

#define MAX_MONSTER_LV (10)

#define MAX_REWARD_WINDOW_NUM (10)
#define MAX_DELAY_TIME_REWARD_WINDOW (30)

#define MAX_RANDOM_REWARD_NUM (10)

#define MAX_IDOL_NUM (10)

//client building action 相关
#define CLIENT_ACTION_ID_OFFSET (4000000000)
#define MAX_CLIENT_SEQ (10000000)

enum EActionCategory
{
    EN_UID_ACTION = 0, //global
    EN_AID_ACTION, //global
    EN_MARCH_ACTION, //global
    EN_ACTION_END,
};

enum EDataCenterOpenItemChestType
{
    EN_ITEM_FUNC_TYPE_CRYSTAL = 10030,
    EN_ITEM_FUNC_TYPE_MATERIALS = 10031,
    EN_ITEM_FUNC_TYPE_CHALLENGER = 10054,
    EN_ITEM_FUNC_TYPE_MONSTER = 10055,
};



enum EQuestRefreshType
{
    EN_QUEST_REFRESH_TYPE_NORMAL = 0,
    EN_QUEST_REFRESH_TYPE_FORCE = 1,
};


enum EPersonGuide
{
    EN_PERSON_GUIDE_VIP = 1,
    EN_PERSON_GUIDE_PLAYER_SKILL,
    EN_PERSON_GUIDE_BUILDING,
    EN_PERSON_GUIDE_CHEST,
    EN_PERSON_GUIDE_JOIN_ALLIANCE,
    EN_PERSON_GUIDE_NEVER_USE_SPEED_ITEM,    
};


enum EGuideFinishStage
{
    EN_GUIDE_FINISH = 1,
    EN_GUIDE_FINISH_STAGE_1_RESEARCH = 2,
    EN_GUIDE_FINISH_STAGE_2_TRAIN_TROOP,
    EN_GUIDE_FINISH_STAGE_3_ADD_KNIGHT_EXP, //useless
    EN_GUIDE_FINISH_STAGE_4_OCCUPY_RESOURCE, //useless
    EN_GUIDE_FINISH_STAGE_5_ASSIGN_HERO_SKILL, //useless
};

enum ECityType
{
    EN_MAIN_CITY = 0,
    EN_CARD_CITY,
};

// 信息墙的展示样式
enum EMsgWallStyle
{
    EN_STYLE_ONE = 1,
    EN_STYLE_TWO,
    EN_STYLE_THREE,
    EN_STYLE_FOUR,
};

// 信息墙的格式
enum EMsgWallContentType
{
    EN_CONTENT_TYPE_RANK_CHANGE = 0,
    EN_CONTENT_TYPE_RANK_REACH,
    EN_CONTENT_TYPE_SCORE_REWARD,
    EN_CONTENT_TYPE_BW_GRAB,
    EN_CONTENT_TYPE_BW_BATTLEFIELD,
};

enum EGemReward
{
    // 宝石膨胀10倍
    EN_GEM_REWARD__LOGIN_CREATE = 300,
    EN_GEM_REWARD__GUIDE_0_COST_GEM = 0,
    EN_GEM_REWARD__GUIDE_1_COST_GEM = 10,
    EN_GEM_REWARD__GUIDE_2_COST_GEM = 0,
    EN_GEM_REWARD__ALLIANCE_FIRST_JOIN = 100,
    EN_GEM_REWARD__INVITED_GEM = 1000,
    EN_GEM_REWARD__INVITE_GEM = 1000,
};

enum EGlobalHsTableType
{
    EN_GLOBAL_TABLE__LOGIN = 0,
    EN_GLOBAL_TABLE__APNS,
    EN_GLOBAL_TABLE__IAP,
    EN_GLOBAL_TABLE__END,
};

static const char meterial_name[][32] =
{
    "Parchement",
    "Clay",
    "Marble",
    "Timber",
    "Standard Parchment",
    "Standard Clay",
    "Standard Marble",
    "Standard Timber",
    "Holy Parchment",
    "Holy Clay",
    "Holy Marble",
    "Holy Timber",
    "Horn",
    "Feather",
    "Leather",
    "Cloth",
    "Unicorn Horn",
    "Eagle Feather",
    "Ox Leather",
    "Wool",
    "Dragon Horn",
    "Phoenix Feather",
    "Crocodile Leather",
    "Silk"
};

static const char crystal_name[][32] =
{
    "Red Crystal",
    "Yellow Crystal",
    "Purple Crystal",
    "Blue Crystal"
};

static const char equiment_name[][32] =
{
    "Iron Helmet",
    "Iron Wings",
    "Iron Vest",
    "Iron Wrists",
    "Silver Helmet",
    "Silver Wings",
    "Silver Vest",
    "Silver Wrists",
    "Gold Helmet",
    "Gold Wings",
    "Gold Vest",
    "Gold Wrists"

};

enum EResourceType
{
    EN_RESOURCE_TYPE__GOLD = 0,
    EN_RESOURCE_TYPE__FOOD,
    EN_RESOURCE_TYPE__WOOD,
    EN_RESOURCE_TYPE__STONE,
    EN_RESOURCE_TYPE__ORE,
    EN_RESOURCE_TYPE__END,
};

enum EResourceBonusType
{
    EN_BONUS_TYPE__KNIGHT = 0,
    EN_BONUS_TYPE__RESEARCH,
    EN_BONUS_TYPE__WILDS,
    EN_BONUS_TYPE__ITEM,
    EN_BONUS_TYPE__OTHER,
    EN_BONUS_TYPE__DRAGON,
    EN_BONUS_TYPE__LORD,
    EN_BONUS_TYPE__VIP,
    EN_BONUS_TYPE__END,
};

enum EBonusEffect
{
    EN_BONUS_EFFECT__GOLD = 0,
    EN_BONUS_EFFECT__FOOD,
    EN_BONUS_EFFECT__WOOD,
    EN_BONUS_EFFECT__STONE,
    EN_BONUS_EFFECT__ORE,
    EN_BONUS_EFFECT__BUILDING,
    EN_BONUS_EFFECT__RESEARCH,
    EN_BONUS_EFFECT__TRAIN,
    EN_BONUS_EFFECT__TROOP_ATTACK,
    EN_BONUS_EFFECT__FORT_ATTACK,
    EN_BONUS_EFFECT__TROOP_HEALTH,
    EN_BONUS_EFFECT__FORT_HEALTH,
    EN_BONUS_EFFECT__RES_COLLECT,
    EN_BONUS_EFFECT__LOAD,
    EN_BONUS_EFFECT__RES_PROTECT,
    EN_BONUS_EFFECT__END,
};

enum EGoldBonusType
{
    EN_GOLD_BONUS_TYPE__TAX = 0,
    EN_GOLD_BONUX_TYPE__POPULATION,
    EN_GOLD_BONUS_TYPE__KNIGHT_SALARY,
};

enum EDataFlag
{
    EN_DATA_FLAG__NO_DATA = 0,
    EN_DATA_FLAG__REQUEST,		// 数据请求
    EN_DATA_FLAG__RESPONSE,		// 有数据，且数据合法
};

enum EUserLoginStatus
{
    EN_LOGIN_STATUS__USING = 0,
    EN_LOGIN_STATUS__LOGIN,
};

enum EUserLoginType
{
    EN_LOGIN_TYPE__GID = 0,
    EN_LOGIN_TYPE__DID = 1,
    EN_LOGIN_TYPE__ACCOUNT = 2,
    EN_LOGIN_TYPE__END,
};

enum EDiplomacyType
{
    EN_DIPLOMACY_TYPE__NORMAL = 0,
    EN_DIPLOMACY_TYPE__HOSTILE,
    EN_DIPLOMACY_TYPE__PEDDING,
    EN_DIPLOMACY_TYPE__FRIENDLY,
    EN_DIPLOMACY_TYPE__END,
};

enum EAllianceParseType   //从src_to_des字段解析aid的方式
{
    EN_ALLIANCE_PARSE_TYPE__SOURCE = 0,
    EN_ALLIANCE_PARSE_TYPE__DESTINATION,
    EN_ALLIANCE_PARSE_TYPE__END,
};

enum ETableUpdtFlag
{
    EN_TABLE_UPDT_FLAG__UNCHANGE = 0,
    EN_TABLE_UPDT_FLAG__CHANGE,
    EN_TABLE_UPDT_FLAG__NEW,
    EN_TABLE_UPDT_FLAG__DEL,
    //EN_TABLE_UPDT_FLAG_DONE,
};

const TUINT32 g_udwDiplomacyThrd[EN_DIPLOMACY_TYPE__END] =
{
    (TUINT32)-1,
    10,
    10,
    10,
};

enum EDiplomacyStatus
{
    EN_DIPLOMACY_STATUS__WAIT_A_DECIDE = 1,
    EN_DIPLOMACY_STATUS__WAIT_B_DECIDE,
    EN_DIPLOMACY_STATUS__SUCCESS,
    EN_DIPLOMACY_STATUS__END,
};

enum EBaseCostType
{
    EN_BASE_COST_TYPE__GOLD = 0,
    EN_BASE_COST_TYPE__FOOD,
    EN_BASE_COST_TYPE__WOOD,
    EN_BASE_COST_TYPE__STONE,
    EN_BASE_COST_TYPE__ORE,
    EN_BASE_COST_TYPE__SPACE,
    EN_BASE_COST_TYPE__POPULATION,
    EN_BASE_COST_TYPE__TIME,
    EN_BASE_COST_TYPE__END,
};

enum ETroopStatus
{
    EN_TROOP_STATUS__ID = 0,
    EN_TROOP_STATUS__HEALTH,
    EN_TROOP_STATUS__ATTACK,
    EN_TROOP_STATUS__SPEED,
    EN_TROOP_STATUS__LOAD,
    EN_TROOP_STATUS__CATEGORY,
    EN_TROOP_STATUS__TIER,
    EN_TROOP_STATUS__TRAINABLE,
    EN_TROOP_STATUS__UPKEEP,
    EN_TROOP_STATUS__MIGHT,
    EN_TROOP_STATUS__END,
};

enum EPropStatus
{
    EN_PROP_STATUS__PRICE = 0,
    EN_PROP_STATUS__CATEGORY,
    EN_PROP_STATUS__FUNCTION,
    EN_PROP_STATUS__IN_SHOP,
    EN_PROP_STATUS__SHOP_USE,
    EN_PROP_STATUS__SALE_PRICE,
    EN_PROP_STATUS__PLAYER_LV,
    EN_PROP_STATUS__DISPLAY_ORDER,
    EN_PROP_STATUS__TYPE_FLAG,
    EN_PROP_STATUS__FUND_PRICE,
    EN_PROP_STATUS__LOYALTY_PRICE,
    EN_PROP_STATUS__DISPLAY_ORDER_IN_ALLIANCE,
    EN_PROP_STATUS__AUTO_USE,
    EN_PROP_STATUS__END,
};


enum EActionDisplayClass
{
    EN_ACTION_DISPLAY_CLASS_NONE = 0,
    EN_ACTION_DISPLAY_CLASS_BUILD,
    EN_ACTION_DISPLAY_CLASS_TRAIN,
    EN_ACTION_DISPLAY_CLASS_MARCH,
    EN_ACTION_DISPLAY_CLASS_END,
};

// 只是后台做分类用
enum EActionMainClass
{
    EN_ACTION_MAIN_CLASS__BUILDING = 0, //Aid action
    EN_ACTION_MAIN_CLASS__TRAIN_NEW,    //Aid action
    EN_ACTION_MAIN_CLASS__MARCH,        //Sid action
    EN_ACTION_MAIN_CLASS__ITEM,         //Uid action
    EN_ACTION_MAIN_CLASS__EQUIP,        //Aid action
    EN_ACTION_MAIN_CLASS__DRAGON,

    EN_ACTION_MAIN_TASK_ATTACK_MOVE = 14,     // 被动延迟移城 Uid Action
    EN_ACTION_CLASS_TASK_NOTIC = 15,          // 生成触发推送的action(15) Uid Action 废弃 不会使用
    EN_ACTION_MAIN_CLASS__TIMER = 16,         // 定时器 Sid Action
    EN_ACTION_MAIN_CLASS__AU_PRESSURE_MEASURE = 17,         // 定时器 Sid Action
    EN_ACTION_MAIN_CLASS__END,
};

// 值不能重复，客户端主要用secclass 做处理
enum EActionSecClass
{
    EN_ACTION_SEC_CLASS__BUILDING_UPGRADE = 1,
    EN_ACTION_SEC_CLASS__BUILDING_REMOVE = 2,
    EN_ACTION_SEC_CLASS__RESEARCH_UPGRADE = 3,
    EN_ACTION_SEC_CLASS__TROOP = 4, //train
    EN_ACTION_SEC_CLASS__FORT = 5,  //train
    EN_ACTION_SEC_CLASS__HOS_TREAT = 6,

    EN_ACTION_SEC_CLASS__TRANSPORT = 8,
    EN_ACTION_SEC_CLASS__REINFORCE_NORMAL = 9,
    EN_ACTION_SEC_CLASS__SCOUT = 10,

    EN_ACTION_SEC_CLASS__ITEM = 11,

    EN_ACTION_SEC_CLASS__ATTACK = 12,

    EN_ACTION_SEC_CLASS__OCCUPY = 13,

    EN_ACTION_SEC_CLASS__RES_LOAD = 14, //废弃

    EN_ACTION_SEC_CLASS__ALTAR_TREAT = 15, //废弃
    EN_ACTION_SEC_CLASS__REASSIGN = 16, //废弃
    EN_ACTION_SEC_CLASS__CAMP = 17,

    EN_ACTION_SEC_CLASS__EQUIP_UPGRADE = 18,
    EN_ACTION_SEC_CLASS__FORT_REPAIR = 19,
    EN_ACTION_SEC_CLASS__REMOVE_OBSTACLE = 20,

    EN_ACTION_SEC_CLASS__ATTACK_MOVE = 21,

    EN_ACTION_SEC_CLASS__DRAGON_ATTACK = 22, //  英雄打怪
    EN_ACTION_SEC_CLASS__DRAGON_OCCUPY = 23, //拉取怪物地形 //废弃

    EN_ACTION_SEC_CLASS__RALLY_WAR = 24,
    EN_ACTION_SEC_CLASS__RALLY_REINFORCE = 25,
    EN_ACTION_SEC_CLASS__DRAGON_ASSIGN = 26, //废弃

    EN_ACTION_SEC_CLASS__THRONE_TIMER = 27,
    EN_ACTION_SEC_CLASS__PRISON_TIMER = 28,
    EN_ACTION_SEC_CLASS__NOTI_TIMER = 29,

    EN_ACTION_SEC_CLASS__AU_PRESSURE_MEASURE = 30,

    EN_ACTION_SEC_CLASS__TRADE = 31, // 贸易 nemo add //废弃

    EN_ACTION_SEC_CLASS__LEAVE_NEW_PLAYER_AL = 32, //新手盟清理无效用户  属于定时类 //废弃

    EN_ACTION_SEC_CLASS__RALLY_PRIDICT = 33, //王座省会争夺预告 //废弃

    EN_ACTION_SEC_CLASS__TAX = 34, // 王座收税action nemo add v1.3

    EN_ACTION_SEC_CLASS__THRONE_DONATE = 35, //废弃

    EN_ACTION_SEC_CLASS__UNLOCK_DRAGON = 36,
    EN_ACTION_SEC_CLASS__CATCH_DRAGON = 37,
    EN_ACTION_SEC_CLASS__RELEASE_DRAGON = 38,

    //新增王座相关action
    EN_ACTION_SEC_CLASS__ATTACK_THRONE = 39,
    EN_ACTION_SEC_CLASS__RALLY_WAR_THRONE = 40,
    EN_ACTION_SEC_CLASS__REINFORCE_THRONE = 41,
    EN_ACTION_SEC_CLASS__ASSIGN_THRONE = 42,

    //新增神像相关action
    EN_ACTION_SEC_CLASS__ATTACK_IDOL = 43,

    //神像各时期转换用action
    EN_ACTION_SEC_CLASS__IDOL_PERIOD = 44,

    //王座各时期转换用action
    EN_ACTION_SEC_CLASS__THRONE_PERIOD = 45,
};

enum EActionStatus
{
    EN_BUILDING_STATUS__BUILDDING = 0,
    EN_BUILDING_STATUS__REMOVEING = 0,
    EN_BUILDING_STATUS__RESEARCHING = 0,

    EN_TRAIN_STATUS__TRAINING = 0,

    EN_AUCTION_STATUS__SELLING = 0,  //nemo, sell item status
    EN_AUCTION_STATUS__SOLD,
    EN_AUCTION_STATUS__CANCELING,

    EN_SMELT_STATUS__COMPOSING = 0,
    EN_EQUIP_STATUS__UPGRADING = 0,

    EN_MARCH_STATUS__MARCHING = 0, //行军
    EN_MARCH_STATUS__FIGHTING,  //战斗中
    EN_MARCH_STATUS__RETURNING, //返回
    EN_MARCH_STATUS__DEFENDING, //reinforce到某城市的防守状态 1
    EN_MARCH_STATUS__LOADING,  //装载资源
    EN_MARCH_STATUS__SETUP_CAMP, //开始驻扎 1 
    EN_MARCH_STATUS__PRE_LOADING, //开始装载
    EN_MARCH_STATUS__UN_LOADING,  //卸载 1
    EN_MARCH_STATUS__PREPARING, //集结中 1
    EN_MARCH_STATUS__WAITING, //等待中
    EN_MARCH_STATUS__CALCING, //special

    EN_MARCH_STATUS__MOVE_CITY_PREPARE, //被动移城状态

    EN_MARCH_STATUS__TRADING, //使团待接待状态 nemo add
    EN_MARCH_STATUS__CAMPING_WITH_PEACETIME, // 驻扎中--有保护
    EN_MARCH_STATUS__CAMPING_NORMAL,
    
    EN_MARCH_STATUS__DELING = 20,
    EN_MARCH_STATUS__DELING_ON_FLY,
    EN_MARCH_STATUS__END,

    EN_ITEM_STATUS__USING = 0,

    EN_TAX_STATUS__PREPARING = 0,
    EN_TAX_STATUS__COLLECTING,
    EN_TAX_STATUS__FINISH,
    EN_TAX_STATUS__TRANSFER,

    EN_DRAGON_STATUS_UNLOCKING = 0,

    EN_TITMER_IDOL_PERIOD_STATUS__THRONE_PEACE_TIME = 0,
    EN_TITMER_IDOL_PERIOD_STATUS__BUFF,
    EN_TITMER_IDOL_PERIOD_STATUS__QUIET,
    EN_TITMER_IDOL_PERIOD_STATUS__CONTEST,

    EN_TITMER_THRONE_PERIOD_STATUS__PEACE_TIME = 0,
    EN_TITMER_THRONE_PERIOD_STATUS__QUIET,
    EN_TITMER_THRONE_PERIOD_STATUS__CONTEST,

};

enum ETroopDeadType //军队死亡方式
{
    EN_TROOP_DEAD_TYPE_ATTACK = 0,
    EN_TROOP_DEAD_TYPE_DEFEND,
    EN_TROOP_DEAD_TYPE_REINFORCE,
    EN_TROOP_DEAD_TYPE_COLLECT,
};

enum EBuildingType
{
    EN_BUILDING_TYPE__CASTLE = 0, //主城
    EN_BUILDING_TYPE__WALL,       //城墙
    EN_BUILDING_TYPE__ALCHEMY_LAB,//研究院
    EN_BUILDING_TYPE__KNIGHT_HALL,//骑士
    EN_BUILDING_TYPE__EMBASSY,    //大使馆
    EN_BUILDING_TYPE__STOREHOUSE, //仓库
    EN_BUILDING_TYPE__RALLY_POINT,//rally field
    EN_BUILDING_TYPE__WATCH_TOWER,//警戒塔
    EN_BUILDING_TYPE__BLACKSMITH, //复用为冶炼工厂
    EN_BUILDING_TYPE__JAIL,//注: 龙牢复用EN_BUILDING_TYPE__STABLES
    EN_BUILDING_TYPE__MARKETPLACE,//市场
    EN_BUILDING_TYPE__ALTAR,      //祭坛
    EN_BUILDING_TYPE__COTTAGE,    //房屋
    EN_BUILDING_TYPE__BARRACKS,   //兵营
    EN_BUILDING_TYPE__HOSPITAL,   //troop医院
    EN_BUILDING_TYPE__FARM,       //农场
    EN_BUILDING_TYPE__SAWMILL,
    EN_BUILDING_TYPE__QUARRY,
    EN_BUILDING_TYPE__MINE,
    EN_BUILDING_TYPE__INFANTRY_BARRACKS,
    EN_BUILDING_TYPE__REMOTE_BARRACKS,
    EN_BUILDING_TYPE__SOWAR_BARRACKS,
    EN_BUILDING_TYPE__SIEGE_BARRACKS,
    EN_BUILDING_TYPE__HELP,
    EN_BUILDING_TYPE__TRIAL = 26,
    EN_BUILDING_TYPE__GROVE = 105,
    EN_BUILDING_TYPE__END = 200,
};

enum EResearchType
{
    EN_RESEARCH_TYPE__SCOUT = 62,
    EN_RESEARCH_TYPE__END = 1024,
    EN_RESEARCH_TYPE__LIMIT = 1024,
};

enum ETroopType
{
    EN_TROOP_TYPE__T1_INFANTRY = 0,
    EN_TROOP_TYPE__T1_ARCHERS,
    EN_TROOP_TYPE__T1_CAVALRY,
    EN_TROOP_TYPE__T1_SIEGE,


    EN_TROOP_TYPE__T2_INFANTRY,
    EN_TROOP_TYPE__T2_ARCHERS,
    EN_TROOP_TYPE__T2_CAVALRY,
    EN_TROOP_TYPE__T2_SIEGE,


    EN_TROOP_TYPE__T3_INFANTRY,
    EN_TROOP_TYPE__T3_ARCHERS,
    EN_TROOP_TYPE__T3_CAVALRY,
    EN_TROOP_TYPE__T3_SIEGE,

    EN_TROOP_TYPE__T4_INFANTRY,
    EN_TROOP_TYPE__T4_ARCHERS,
    EN_TROOP_TYPE__T4_CAVALRY,
    EN_TROOP_TYPE__T4_SIEGE,

    //
    EN_TROOP_TYPE__END = 80,
};

enum ETroopCategory
{
    EN_TROOP_CATEGORY__NONE = -2,
    EN_TROOP_CATEGORY__ALL = -1,
    EN_TROOP_CATEGORY__INFANTRY = 0,//步兵
    EN_TROOP_CATEGORY__REMOTE,//远程兵
    EN_TROOP_CATEGORY__SOWAR,//骑兵
    EN_TROOP_CATEGORY__SIEGE,//攻城
    EN_TROOP_CATEGORY__END,
};

enum EArmsClass
{
    // troop 分类
    EN_ARMS_CLS__SUPPLY_TROOPS = 0,
    EN_ARMS_CLS__LIGHT_CAVALRY,
    EN_ARMS_CLS__MILITIAMAN,
    EN_ARMS_CLS__ARCHERS,
    EN_ARMS_CLS__SUPPLY_CART,
    EN_ARMS_CLS__CAVALRY,
    EN_ARMS_CLS__SWORDSMAN,
    EN_ARMS_CLS__BALLISTA,
    EN_ARMS_CLS__SUPPLY_WAGON,
    EN_ARMS_CLS__HEAVY_CAVALRY,
    EN_ARMS_CLS__BATTERING_RAMS,
    EN_ARMS_CLS__CATAPULTS,
    EN_ARMS_CLS__LV4_WAGON,
    EN_ARMS_CLS__LV4_CAVALRY,
    EN_ARMS_CLS__LV4_RAMS,
    EN_ARMS_CLS__LV4_CATAPULTS,
    EN_ARMS_CLS__LV5_WAGON,
    EN_ARMS_CLS__LV5_CAVALRY,
    EN_TROOP_CLS__END = 100,

    // fort 分类
    EN_ARMS_CLS__TRAPS = 101,
    EN_ARMS_CLS__CALTROPS,
    EN_ARMS_CLS__WALL_MOUNTED_CROSSBOWS,
    EN_ARMS_CLS__BOILING_OIL,
    EN_ARMS_CLS__SPIKED_BARRIER,
    EN_ARMS_CLS__DEFENSIVE_TREBUCHET,
    EN_ARMS_CLS__GREEK_FIRE,
    EN_ARMS_CLS__PERSIAN_SULFUR,
    EN_ARMS_CLS__HELLFIRE_THROWERS,
    EN_FORT_CLS__END = 150,

    // 其他兵分类
    EN_ARMS_CLS__END = 150,
};

enum EFortType
{
    EN_FORT_TYPE__TRAPS = 0,
    EN_FORT_TYPE__CALTROPS,
    EN_FORT_TYPE__WALL_MOUNTED_CROSSBOWS,
    EN_FORT_TYPE__BOILING_OIL,
    EN_FORT_TYPE__SPIKED_BARRIER,
    EN_FORT_TYPE__DEFENSIVE_TREBUCHET,
    EN_FORT_TYPE__GREEK_FIRE,
    EN_FORT_TYPE__PERSIAN_SULFUR,
    EN_FORT_TYPE__HELLFIRE_THROWERS,
    EN_FORT_TYPE__END = 30,
};

enum ETroopFortGradeType
{
    EN_TROOP_FORT_GRADE_TYPE_T1 = 1,
    EN_TROOP_FORT_GRADE_TYPE_T2 = 2,
    EN_TROOP_FORT_GRADE_TYPE_T3 = 3,
    EN_TROOP_FORT_GRADE_TYPE_T4 = 4,
    EN_TROOP_FORT_GRADE_TYPE_END = 5,
};
enum ETroopDetailType
{
    EN_TROOP_DETAIL_TYPE__BEGIN = 0,
    EN_TROOP_DETAIL_TYPE__TROOP_BEGIN = EN_TROOP_DETAIL_TYPE__BEGIN,
    EN_TROOP_DETAIL_TYPE__SUPPLY_TROOPS = EN_TROOP_DETAIL_TYPE__TROOP_BEGIN,
    EN_TROOP_DETAIL_TYPE__LIGHT_CAVALRY,
    EN_TROOP_DETAIL_TYPE__MILITIAMAN,
    EN_TROOP_DETAIL_TYPE__ARCHERS,
    EN_TROOP_DETAIL_TYPE__SUPPLY_CART,
    EN_TROOP_DETAIL_TYPE__CAVALRY,
    EN_TROOP_DETAIL_TYPE__SWORDSMAN,
    EN_TROOP_DETAIL_TYPE__BALLISTA,
    EN_TROOP_DETAIL_TYPE__SUPPLY_WAGON,
    EN_TROOP_DETAIL_TYPE__HEAVY_CAVALRY,
    EN_TROOP_DETAIL_TYPE__BATTERING_RAMS,
    EN_TROOP_DETAIL_TYPE__CATAPULTS,
    EN_TROOP_DETAIL_TYPE__LV4_WAGON,
    EN_TROOP_DETAIL_TYPE__LV4_CAVALRY,
    EN_TROOP_DETAIL_TYPE__LV4_RAMS,
    EN_TROOP_DETAIL_TYPE__LV4_CATAPULTS,
    EN_TROOP_DETAIL_TYPE__LV5_WAGON,
    EN_TROOP_DETAIL_TYPE__LV5_CAVALRY,
    EN_TROOP_DETAIL_TYPE__TROOP_END,

    EN_TROOP_DETAIL_TYPE__FORT_BEGIN = EN_TROOP_DETAIL_TYPE__TROOP_END,
    EN_TROOP_DETAIL_TYPE__TRAPS = EN_TROOP_DETAIL_TYPE__FORT_BEGIN,
    EN_TROOP_DETAIL_TYPE__CALTROPS,
    EN_TROOP_DETAIL_TYPE__WALL_MOUNTED_CROSSBOWS,
    EN_TROOP_DETAIL_TYPE__BOILING_OIL,
    EN_TROOP_DETAIL_TYPE__SPIKED_BARRIER,
    EN_TROOP_DETAIL_TYPE__DEFENSIVE_TREBUCHET,
    EN_TROOP_DETAIL_TYPE__GREEK_FIRE,
    EN_TROOP_DETAIL_TYPE__PERSIAN_SULFUR,
    EN_TROOP_DETAIL_TYPE__HELLFIRE_THROWERS,
    EN_TROOP_DETAIL_TYPE__FORT_END,
    EN_TROOP_DETAIL_TYPE__WALL_BEGIN = EN_TROOP_DETAIL_TYPE__FORT_END,
    EN_TROOP_DETAIL_TYPE__WALL = EN_TROOP_DETAIL_TYPE__WALL_BEGIN,
    EN_TROOP_DETAIL_TYPE__WALL_END,
    EN_TROOP_DETAIL_TYPE__END = EN_TROOP_DETAIL_TYPE__WALL_END,
};

enum EIncentiveType
{
    EN_INCENTIVE_TYPE__GOLD = 0,
    EN_INCENTIVE_TYPE__FOOD,
    EN_INCENTIVE_TYPE__WOOD,
    EN_INCENTIVE_TYPE__STONE,
    EN_INCENTIVE_TYPE__ORE,
    EN_INCENTIVE_TYPE__AVOID_ATTACK,
    EN_INCENTIVE_TYPE__AVOID_SCOUT,
    EN_INCENTIVE_TYPE__ATTACK,
    EN_INCENTIVE_TYPE__HEALTH,
    EN_INCENTIVE_TYPE__END,
};

enum EWildType //对应wild_res["key"]
{
    EN_WILD_TYPE__INVAILD = -1,
    EN_WILD_TYPE__NORMAL = 0,

    EN_WILD_TYPE__LAKE = 6,
    EN_WILD_TYPE__CITY = 7,
    EN_WILD_TYPE__SPECIAL_LAKE = 8,
    EN_WILD_TYPE__MOUNTAIN = 9,

    EN_WILD_TYPE__CAMP = 12,

    EN_WILD_TYPE__THRONE_NEW = 20,
    EN_WILD_TYPE__IDOL = 21,

    EN_WILD_TYPE_RES_INIT = 100,
    EN_WILD_TYPE_RES_GOLD = 101,

    EN_WILD_TYPE_PROVINCE = 111, //废弃
    EN_WILD_TYPE_THRONE, //废弃
    EN_WILD_TYPE__END,
};



enum EWildClass//对应wild_res["key"]["a0"]["a0"]字段
{
    EN_WILD_CLASS_NORMAL = 0,
    EN_WILD_CLASS_CITY = 1,
    EN_WILD_CLASS_RES = 2,
    EN_WILD_CLASS_MONSTER = 3,
    EN_WILD_CLASS_MONSTER_NEST = 4,
    //EN_WILD_CLASS_TRIBE = 5, //废弃
    //EN_WILD_CLASS_BATTLEFIELD = 6, //废弃
    //EN_WILD_CLASS_PROVINCE = 7, //废弃
    EN_WILD_CLASS_THRONE = 8,
    EN_WILD_CLASS_LEADER_MONSTER = 9,
    EN_WILD_CLASS_CAMP = 10,
    EN_WILD_CLASS_IDOL = 11,
};

// 跟游戏文案相对应，现在所用到的只是拉资源地回程之后的notification文案所需要用到
const TCHAR g_aszWildName[][32] =
{
    "Normal",       // 游戏展示由一份固定的地图数据展示
    "Gold",
    "Food",
    "Wood",
    "Stone",
    "Iron",
    "Lake",
    "city",
    "Gems",
    "Battlefield",  // Battlefield三种类型在兵种的数量配置上由运营决定
    "Battlefield",
    "Battlefield",
    "Tribe",
    "Babel Tower",
    "",             // 游戏上没有，后台不使用，客户端需要
    "Relic",
    "",             // 游戏上没有，后台保留字段
    "",
};


enum ECityStatus
{
    EN_CITY_STATUS__NORMAL = 0,
    EN_CITY_STATUS__AVOID_WAR = 1, //PEACETIME
    EN_CITY_STATUS__AVOID_SCOUT = 2,
    EN_CITY_STATUS__NEW_PROTECTION = 4,
    EN_CITY_STATUS__NEW_PROTECTION_CANCEL = 8, //llt add 20130923
    EN_CITY_STATUS__FIRST_ALLIANCE_REWARD = 16, //首次加入联盟标识,领取完奖励后清除
    EN_CITY_STATUS__NEW_USER_MISTERY = 32,  //玩家处于新手mistery
    EN_CITY_STATUS__ON_FIGHT = 64,  //省会或者王座处于持续战斗期
    EN_CITY_STATUS__BEEN_ATTACK = 128, //城市受攻击会冒烟，持续30min
    EN_CITY_STATUS__BEEN_REMOVE = 256, //2)	城市被清零会冒火
    EN_CITY_STATUS__ON_SPECIAL_WILD = 512, // 处在特殊地形上

    EN_CITY_STATUS__END,
};

enum EAlliancePos
{
    EN_ALLIANCE_POS__REQUEST = 0,
    EN_ALLIANCE_POS__MEMBER,
    EN_ALLIANCE_POS__OFFICER,
    EN_ALLIANCE_POS__VICE_MINISTER,
    EN_ALLIANCE_POS__MINISTER,
    EN_ALLIANCE_POS__VICE_CHANCELOR,
    EN_ALLIANCE_POS__CHANCELLOR,
};

enum EJOINTYPE //联盟加入策略
{
    EN_JOIN_NORMAL = 0,
    EN_JOIN_FOURCE = 1,
};

static const TCHAR g_aszAlliancePos[][32] =
{
    "",
    "Member",
    "Vice Marshal",
    "Grand Marshal",
    "Officer",
    "Vice Chancellor",
    "Chancellor",
};

enum EItemFuncType
{
    EN_ITEM_FUNC_TYPE__SPECIAL = 0,
    EN_ITEM_FUNC_TYPE__AVOID_WAR_TIME,
    EN_ITEM_FUNC_TYPE__SPEEDUP_TIME,
    EN_ITEM_FUNC_TYPE__AVOID_SCOUT_TIME,
    EN_ITEM_FUNC_TYPE__TROOP_ATTACK,
    EN_ITEM_FUNC_TYPE__TROOP_HEALTH,
    EN_ITEM_FUNC_TYPE__GOLD_PRODUCTION,
    EN_ITEM_FUNC_TYPE__FOOD_PRODUCTION,
    EN_ITEM_FUNC_TYPE__WOOD_PRODUCTION,
    EN_ITEM_FUNC_TYPE__STONE_PRODUCTION,
    EN_ITEM_FUNC_TYPE__ORE_PRODUCTION,
    EN_ITEM_FUNC_TYPE__KNIGHT_EXP_ADD,
    EN_ITEM_FUNC_TYPE__CHEST,
    EN_ITEM_FUNC_TYPE__GOLD_ADD,
    EN_ITEM_FUNC_TYPE__FOOD_ADD,
    EN_ITEM_FUNC_TYPE__WOOD_ADD,
    EN_ITEM_FUNC_TYPE__STONE_ADD,
    EN_ITEM_FUNC_TYPE__ORE_ADD,
    EN_ITEM_FUNC_TYPE__NEW_PROTECTION,
    EN_ITEM_FUNC_TYPE__MARCH_SPEED_UP_PERCENT,
    EN_ITEM_FUNC_TYPE__VIP_POINT_ADD,
    EN_ITEM_FUNC_TYPE__VIP_ENABLE,
    EN_ITEM_FUNC_TYPE__MARCH_SIZE_UP_PERCENT,
    EN_ITEM_FUNC_TYPE__MORE_MARCH,
    EN_ITEM_FUNC_TYPE__BOOK_OF_WAR_ADD,
    EN_ITEM_FUNC_TYPE__DRAGON_HATCH = 25, //孵化龙
    EN_ITEM_FUNC_TYPE__DRAGON_ATTACK_UP_PERCENT = 26, //buff info,龙加攻击力
    EN_ITEM_FUNC_TYPE__DRAGON_HEALTH_UP_PERCENT = 27, //buff info,龙加生命值
    EN_ITEM_FUNC_TYPE__DRAGON_BLOOD_ADD = 28,//龙加气血

    //wot2.5新增
    EN_ITEM_FUNC_TYPE__UPKEEP = 37,                                   //upkeep
    EN_ITEM_FUNC_TYPE__RESOURCE_GET_SPEED_UP = 38,                   //加速拉取资源
    EN_ITEM_FUNC_TYPE__SPEEDUP_TRAIN = 39,                           //加速军队训练

    EN_ITEM_FUNC_TYPE__SPEED_UP_PERCENT,            //加速任务
    EN_ITEM_FUNC_TYPE__ADD_CARD_VITALITY_POINT = 43,            //恢复card的活力值

    // 抽奖箱子:多抽一
    EN_ITEM_FUNC_TYPE__LOTTERY_CHEST = 101,

    EN_ITEM_FUNC_TYPE__RESOURCE_PRODUCT_ADD = 150,                //增加生产 后台内部使用 
    EN_ITEM_FUNC_TYPE__END,
};

enum EItemType
{
    //物品合成/分解/镶嵌相关操作
    EN_ITEM_EQUIPMENT = 0,
    EN_ITEM_CRYSTAL,
    EN_ITEM_MATERIAL,
    EN_ITEM_CARD_EQUIPMENT,
    EN_ITEM_CARD_CRYSTAL,
    EN_ITEM_CARD_MATERIAL,
    EN_ITEM_NORMAL = 10,//普通物品
};

enum EItemCategory
{
    EN_ITEM_CATEGORY__MISC = 0,
    EN_ITEM_CATEGORY__SPEEDUP,
    EN_ITEM_CATEGORY__COMBAT,
    EN_ITEM_CATEGORY__RESOURCE,
    EN_ITEM_CATEGORY__CHEST,
    EN_ITEM_CATEGORY__END,
};

enum EChestCategory
{
    EN_CHEST_CATEGORY__DEFAULT = 0,
    EN_CHEST_CATEGORY__NORMAL,
    EN_CHEST_CATEGORY__MATERIAL,
    EN_CHEST_CATEGORY__CRYSTAL,
    EN_CHEST_CATEGORY__EQUIP,

    EN_CHEST_CATEGORY__END,
};


enum EItemID
{
    //TODO
    EN_ITEM_ID__PORTAL_OF_REFUGE = 0,
    EN_ITEM_ID__PORTAL_OF_ORDER,

    EN_ITEM_ID__DRAGONS_STOMP = 9,

    EN_ITEM_ID__SVR_CHANGE_AUTO_DEL = 333,

    EN_ITEM_ID__THRONE_CROWN = 512, //todo

    EN_ITEM_ID__END = 2000,
};

enum EStatType
{
    EN_STAT_TYPE__MAIL = 1,
    EN_STAT_TYPE__REPORT,
};

enum EPlayerStatField
{
    EN_STAT_FIELD__ID = 0,
    EN_STAT_FIELD__ALID,
    EN_STAT_FIELD__MAIL_RETRUAN_ID,
    EN_STAT_FIELD__MAIL_NEW_NUM,
    EN_STAT_FIELD__REPORT_RETRUAN_ID,
    EN_STAT_FIELD__REPORT_NEW_NUM,
    EN_STAT_FIELD__BOOKMARK_NUM,
    EN_STAT_FIELD__END,
};

enum EGlobalParam
{
    //  全局相关 sid 固定为-1
    EN_GLOBAL_PARAM__USER_ID = 1,
    EN_GLOBAL_PARAM__MAIL_ID,
    EN_GLOBAL_PARAM__REPORT_ID,
    EN_GLOBAL_PARAM__ALLIANCE_ID,
    EN_GLOBAL_PARAM__HELP_BUBBLE_TIME,

    // 服务器相关
    EN_SVR_PARAM__ALLIANCE_COUNT = 100, //total
    EN_SVR_PARAM__ALLIANCE_NORMAL_COUNT, //normal
    EN_SVR_PARAM__ALLIANCE_AUTO_COUNT, //auto
    EN_SVR_PARAM__PLAYER_COUNT,
};

enum EAllianceReportGetType
{
    EN_ALLIANCE_REPORT_GET_TYPE__ALL,
    EN_ALLIANCE_REPORT_GET_TYPE__OUT,
    EN_ALLIANCE_REPORT_GET_TYPE__IN,
    EN_ALLIANCE_REPORT_GET_TYPE__RES,
};

enum EPlayerClass
{
    EN_PLAYER_CLASS__DEFAULT = 1,
    EN_PLAYER_CLASS__GOLD = 2,
    EN_PLAYER_CLASS__FOOD = 3,
    EN_PLAYER_CLASS__WOOD = 4,
    EN_PLAYER_CLASS__STONE = 5,
    EN_PLAYER_CLASS__IRON = 6,
    EN_PLAYER_CLASS__HERO_EXP = 7,
    EN_PLAYER_CLASS__ATTACK = 8,
    EN_PLAYER_CLASS__PEACE = 9,
    EN_PLAYER_CLASS__SPEED_UP = 10,
    EN_PLAYER_CLASS__POPULATION = 11,
    EN_PLAYER_CLASS__SECOND_CITY = 12,
    EN_PLAYER_CLASS__THIRD_CITY = 13,
    EN_PLAYER_CLASS__FOURTH_CITY = 14,
    EN_PLAYER_CLASS__FIFTH_CITY = 15,
    EN_PLAYER_CLASS__SIXTH_CITY = 16,
    EN_PLAYER_CLASS__SEVENTH_CITY = 17,
    EN_PLAYER_CLASS__EIGHTH_CITY = 18,
    EN_PLAYER_CLASS__NINTH_CITY = 19,
    EN_PLAYER_CLASS__TENTH_CITY = 20,
    EN_PLAYER_CLASS__END,
};

enum ETimeQuestStatus
{
    EN_TIME_QUEST_STATUS_UNKOWN,        // 无效的任务状态
    EN_TIME_QUEST_STATUS_WAIT_START,    // 任务等待开始
    EN_TIME_QUEST_STATUS_RUNNING,       // 任务正在运行
    EN_TIME_QUEST_STATUS_FINISH,        // 完成但未获取奖励
    EN_TIME_QUEST_STATUS_DONE,          // 完成并且获取了奖励
    EN_TIME_QUEST_STATUS_AUTO_FINISH,        // VIP 自动完成
};

enum EAlGiftStatus
{
    EN_AL_GIFT_STATUS_NORMAL = 0,
    EN_AL_GIFT_STATUS_OPENED,
    EN_AL_GIFT_STATUS_CLEARED,
    EN_AL_GIFT_STATUS_EXPIRED,
};

enum EAllianceItemType
{
    EN_ALLIANCE_ITEM_BASIC = 1,
    EN_ALLIANCE_ITEM_STORE,
    EN_ALLIANCE_ITEM_LIMITE_OFFER,
};

enum EAllianceJoinPolicy //联盟加入策略
{
    EN_ALLIANCE_JOIN_NORMAL, //需要批准
    EN_ALLIANCE_JOIN_AUTO, //自动加入,无需批准
    EN_ALLIANCE_JOIN_BOTH,
};

enum EAllianceReqProType
{
    EN_AL_REQ_PRO_TYPE__REJECT = 1,
    EN_AL_REQ_PRO_TYPE__AGREE,
};

enum ERallySide
{
    EN_RALLY_SIDE_ATTACK = 0,
    EN_RALLY_SIDE_DEFENCE,
};

enum EAllianceActionType
{
    EN_AL_ACTION_TYPE__HELP = 1,
    EN_AL_ACTION_TYPE__RALLY_REINFORCE_ATTACK,
    EN_AL_ACTION_TYPE__RALLY_REINFORCE_DEFENCE,
};

enum EGameBasicDef
{
    EN_GAME_BASIC_HELP_FUND = 0,
    EN_GAME_BASIC_HELP_LOYALTY,
    EN_GAME_BASIC_FUND_UPPER_12_HOUR,
    EN_GAME_BASIC_LOYALTY_UPPER_12_HOUR,
    EN_GAME_BASIC_AL_GIFT_EPPIRE_TIME,
    EN_GAME_BASIC_FIRST_JOIN_ALLIANCE_GEM_REWARD,
    EN_GAME_BASIC_ALTER_REWARD_TIME_LIMIT,
    EN_GAME_BASIC_ALLIANCE_MENBER_LIMIT,
    EN_GAME_BASIC_STEAL_TROOP_PERCENT,
    EN_GAME_BASIC_STEAL_RESOURCE_PERCENT,
    EN_GAME_BASIC_GOLD_BASE_PRODUCTION,
    EN_GAME_BASIC_FOOD_BASE_PRODUCTION,
    EN_GAME_BASIC_WOOD_BASE_PRODUCTION,
    EN_GAME_BASIC_STONE_BASE_PRODUCTION,
    EN_GAME_BASIC_ORE_BASE_PRODUCTION,
    EN_GAME_BASIC_XX_BASE_PRODUCTION,
    EN_GAME_BASIC_TIME_BUILDING_COST_BY_ONE_EXP,
    EN_GAME_BASIC_TIME_TRAIN_COST_BY_ONE_EXP,
    EN_GAME_BASIC_RESOURCE_GEM_TRAISPORT_RATE,
    EN_GAME_BASIC_BASE_AL_HELP_NUM,
    EN_GAME_BASIC_MAX_BUILDING_LV,
    EN_GAME_BASIC_MAX_RESEARCH_LV,
    EN_GAME_BASIC_DEFENDER_BUFFER,
    EN_GAME_BASIC_TROOP_SIZE,
    EN_GAME_BASIC_TROOP_NUM,
    EN_GAME_BASIC_CASTAL_LV_TO_CREATE_AL,
    EN_GAME_BASIC_NEW_PROTECT_TIME,
    EN_GAME_BASIC_QUEST_REFRESH_CYCLE,
    EN_GAME_BASIC_AL_GIFT_OUT_TIME,
    EN_GAME_BASIC_NEW_BREAK_PROTECT_PLAYER_LV,
    EN_GAME_BASIC_NEW_BREAK_DAILY_QUEST_LV,
    EN_GAME_BASIC_GUIDE_BUTTON_SHOW_FLAG,
    EN_GAME_BASIC_TOP_QUEST_CAN_KICK_FLAG,
    EN_GAME_BASIC_SPEED_UP_LIMIT,
    EN_GAME_BASIC_INIT_DAILY_QUEST_NUM,
    EN_GAME_BASIC_INIT_AL_QUEST_NUM,
    EN_GAME_BASIC_FREE_INSTANT_TIME = 37,
    EN_GAME_BASIC_VIP_LEVEL_UP_REWARD_TIME = 38,
    EN_GAME_BASIC_RATES_OF_ITEMS = 40,
    EN_GAME_BASIC_RATES_OF_CHEST,
    EN_GAME_BASIC_OPEN_CHEST_PRICE,
    EN_GAME_BASIC_LOTTERY_COST_STONE_NUM,
    EN_GAME_BASIC_LUCKY_POINT_RANDOM_RANGE_MIN,
    EN_GAME_BASIC_LUCKY_POINT_RANDOM_RANGE_MAX,

    EN_GAME_BASIC_HERO_MONSTER_CONN_TIME_INTERVAL = 55,
    EN_GAME_BASIC_HERO_ATTACK_DEFAULT,
    EN_GAME_BASIC_HERO_CONN_DEFAULT,
    EN_GAME_BASIC_HERO_BAOJI,
    EN_GAME_BASIC_HERO_ENERGY_DEFAULT,
    EN_GAME_BASIC_HERO_ENERGY_RECOVER_RATE_DEFAULT,
    EN_GAME_BASIC_HERO_BAOJI_BUFF,
    EN_GAME_BASIC_HERO_MARCH_SPEED,

    EN_GAME_BASIC_RALLY_TARGET_LV_LIMIT = 63,
    EN_GAME_BASIC_RALLY_SLOT_LIMIT,
    EN_GAME_BASIC_RALLY_TROOP_NUM_LIMIT,

    EN_GAME_BASIC_THRONE_TROOP_NUM_LIMIT = 66,
    EN_GAME_BASIC_PROVINCE_TROOP_NUM_LIMIT = 67,

    EN_GAME_BASIC_HERO_AUTO_RELEASE_TIME = 68,
    EN_GAME_BASIC_HERO_CAPTURE_RATE = 69,

    EN_GAME_BASIC_THRONE_FIGHT_TIME = 70,
    EN_GAME_BASIC_THRONE_PEACE_TIME = 71,

    EN_GAME_BASIC_LOTTERY_ONE_GEM = 77,
    EN_GAME_BASIC_LOTTERY_TEN_GEM = 78,

    EN_GAME_BAISC_WIN_HERO_EXP = 79,
    EN_GAME_BAISC_LOSE_HERO_EXP = 80,

    EN_GAME_BASIC_TRADE_SPEED = 88,
    EN_GAME_BASIC_TRADE_STAYING_TIME = 89,
    EN_GAME_BASIC_TRADE_REFRESH_INTERVAL = 90,
    EN_GAME_BASIC_TRADE_DISTANCE_RATE = 91,

    EN_GAME_BASIC_NEW_PLAYER_AL_MEMBER = 93,

    EN_GAME_BASIC_ASSIST_INTERVAL = 94,
    EN_GAME_BASIC_NEW_PLAYER_AL_CLEAR_INTERVAL = 95,

    EN_GAME_BASIC_TRADE_RECEPTION_REWARD = 103,


    EN_GAME_BASIC_ASSIST_AVAILABLE_TIME = 104,

    EN_GAME_BASIC_BLACKLIST_NUM_LIMIT = 105,

    EN_GAME_BASIC_ALLIANCE_TOP_NOTICE_NUM = 106,
    EN_GAME_BASIC_KNIGHT_TOP_LEVEL = 107,
    EN_GAME_BASIC_KNIGHT_ASSIGN_COST_GOLD = 108,
    EN_GAME_BASIC_DRAGON_ATTACK_WIN_EXP = 109,
    EN_GAME_BASIC_DRAGON_ATTACK_LOST_EXP = 110,
    EN_GAME_BASIC_DRAGON_OCCUPY_EXP = 111,

    EN_GAME_BASIC_Al_COMBO_BUFF = 112,

    EN_GAME_BASIC_DEFAULT_TRANSPORT_SPEED = 115,

    EN_GAME_BASIC_DRAGON_IMPRISON_TIME = 117,
    EN_GAME_BASIC_DRAGON_EXECUTED_TIME = 118,
    EN_GAME_BASIC_CITY_LV_DRAGON_CAN_CAPTURED = 119,
    EN_GAME_BASIC_CITY_LV_DRAGON_CAN_EXECUTED = 120,

    EN_GAME_BASIC_DRAGON_CAPTURE_RATE = 121,
    EN_GAME_BASIC_DRAGON_CAPTURE_OUTSIDE_RATE = 122,
    EN_GAME_BASIC_CITY_LV_DRAGON_UNLOCK = 123,
    EN_GAME_BASIC_DEBUFF_FOR_MARCH_SPEED_ON_SWAMP = 124,
    EN_GAME_BASIC_MIN_MARCH_TIME_ON_SWAMP = 125,

    EN_GAME_BASIC_MARCH_BASE_SPEED = 128,

    EN_GAME_BASIC_MIN_MARCH_TIME = 130,

    EN_GAME_BASIC_DRAGON_FIGHT_EXP_RATIO = 131,
    EN_GAME_BASIC_TRIAL_NORMAL_DRAGON_SHARD_COST = 132,
    EN_GAME_BASIC_TRIAL_RAGE_DRAGON_SHARD_COST = 133,
    EN_GAME_BASIC_CAMP_PROTECT_TIME = 134,

    EN_GAME_BASIC_EX_DRAGON_IMPRISON_TIME_PER_LV = 136,

    EN_GAME_BASIC_TAX_INTERVAL = 137,

    EN_GAME_BASIC_IAP_PROMOTE_REWARD = 138,

    EN_GAME_BASIC_DECORATION_UPPER_LIMIT = 139,

    EN_GAME_BASIC_ALTAR_DRAGON_BUFF_FACTOR = 140,

    EN_GAME_BASIC_IAP_PROMOTE_EX_GEM = 141,

    EN_GAME_BASIC_END,
};

enum EAlAssistType
{
    EN_ASSIST_TYPE__RES_REQ = 1,
    EN_ASSIST_TYPE__TROOP_REQ,
    EN_ASSIST_TYPE__RES_SHARE,
    EN_ASSIST_TYPE__END,
};

enum EHelpTipsType
{
    EN_HELP_TYPE__BUILDING = 0,
    EN_HELP_TYPE__RESEARCH,
    EN_HELP_TYPE__HEALING,
    EN_HELP_TYPE__SMELT,
    EN_HELP_TYPE__REMOVE_OBSTCLE,  //移除障碍物或拆除建筑
    EN_HELP_TYPE__TROOP_TRAIN,
    EN_HELP_TYPE__TROOP_HEAL,
    EN_HELP_TYPE__FORT_TRAIN,
    EN_HELP_TYPE__FORT_REPAIR,
    EN_HELP_TYPE__UNLOCK_DRAGON,
};

enum ESkillType
{
    EN_SKILL_TYPE__END = 50,
    EN_SKILL_TYPE__LIMIT = 50,
};

enum ETipsType
{
    EN_TIPS_TYPE__AL_HELP = 0, //help_type(枚举EHelpTipsType)+target_type(建筑类型、研究类型等)+target_level(建筑等级、研究等级等，没有等级的返回0)+name + 减少秒数
                                // train_help help_type(枚举EHelpTipsType)+type(troop or fort) + num + name + 减少秒数
    EN_TIPS_TYPE__DAILY_QUEST_OK, // 0+0+0
    EN_TIPS_TYPE__ALLIANCE_QUEST_OK, // 0+0+0
    EN_TIPS_TYPE__BUILDING_OK, // type+level+0
    EN_TIPS_TYPE__RESEARCH_OK, // type+level+0
    EN_TIPS_TYPE__TRAIN_TROOP_OK,// type+num+0
    EN_TIPS_TYPE__TRAIN_FORT_OK,// type+num+0
    EN_TIPS_TYPE__HEAL_TROOP_OK,// type+num+0
    EN_TIPS_TYPE__HEAL_HERO_OK,// type+num+0
    EN_TIPS_TYPE__REINFORCE_NORMAL_OK, // cid+uid+0+name
    EN_TIPS_TYPE__JOINED_ALLIANCE,// alid+0+0+alname
    EN_TIPS_TYPE__TRANSPORT_OK, //tcid+tuid+0+tname
    EN_TIPS_TYPE__OCCUPY_OK, //tpos+type+level
    EN_TIPS_TYPE__WAR_RESULT, //tpos+tuid+rescode+tname+resourcelist(gold|food|wood|stone|ore|gem)
    //(资源包括5种基础资源和gem, gem放在第六位)  rescode=[0：进攻打赢 1：进攻失败 2：防守赢 3：防守输]
    EN_TIPS_TYPE__VIP_QUEST_OK,             // 0+0+0
    EN_TIPS_TYPE__ATTACKING, //tpos+type+level+tname

    EN_TIPS_TYPE__QUEST_OK = 32, // quest_id+cid

    EN_TIPS_TYPE__LEAVE_ALLIANCE_OK = 33, //alid+0+0+alname
    EN_TIPS_TYPE__LEAVE_EQUIP_OK = 34, //e_id(game json id)+lv
    EN_TIPS_TYPE__REMOVE_CRYSTAL = 35,        // lv+crystal id
    EN_TIPS_TYPE__COMMON_REWARD = 36,         // 表示通用的奖励, 当tip type为这个时, tip content不是string
    EN_TIPS_TYPE__MYSTEY_GIFT = 37,           // [[int, int, int]] [[type, id, num]]
    EN_TIPS_TYPE__REMOVE_OBSTCLE = 38, // type+level+0
    EN_TIPS_TYPE__HEAL_FORT_OK = 39,// type+num+0
    EN_TIPS_TYPE__DEL_MAIL_OK = 40,
    EN_TIPS_TYPE__DEL_MAIL_FAIL = 41,
    EN_TIPS_TYPE__REMOVE_BUILDING_OK = 42,//type+lv+0

    EN_TIPS_TYPE__HERO_ATTACKING = 43,// wild_type + lv (正在攻击怪物)
    EN_TIPS_TYPE__HERO_KILL_MONSTER_OK = 44,// wild_type+lv(击杀怪物成功)
    EN_TIPS_TYPE__DRAGON_ATTACK_MONSTER_GET_REWARD = 45,// [[int, int, int]] [[type, id, num]]

    EN_TIPS_TYPE__KILL_HERO = 46,//hero_level+0+0+hero_name  给抓捕者
    EN_TIPS_TYPE__HERO_IS_KILLED = 47,//0+0+0+对方玩家名称  给被抓者
    EN_TIPS_TYPY__CAPTURE_HERO = 48,//0+0+0+对方玩家名称  给抓捕者
    EN_TIPS_TYPY__HERO_IS_CAPTURED = 49,//0+0+0+对方玩家名称  给被抓者
    EN_TIPS_TYPY__RESCUE_HERO = 50,//0+0+0  给营救者
    EN_TIPS_TYPY__PRISONER_IS_RESCUED = 51,//0+0+0+对方玩家名称  给抓捕者
    EN_TIPS_TYPY__HERO_IS_RELEASED = 52,//0+0+0+对方玩家名称  给被抓者
    EN_TIPS_TYPY__EQUIP_ABATE = 53,//equip_id+0+0
    EN_TIPS_TYPY__VIP_LEVEL_UP = 54,//target_level+0+0
    EN_TIPS_TYPY__GET_WILD_REWARD = 55,// [[int, int, int]] [[type, id, num]]
    EN_TIPS_TYPE__EVENT_RANK = 56, //event_id+0+0
    EN_TIPS_TYPY__VIP_INVALID = 57, //0+0+0

    EN_TIPS_TYPY__EQUIP_COMPOSE_BEGIN = 58,//e_id
    EN_TIPS_TYPY__COMPOSE_RESULT = 59,//type + id (type 为globalres type)

    EN_TIPS_TYPY__RALLY_WAR_BEGIN = 60,//TYPE+LV+0+name  //开始出征
    EN_TIPS_TYPY__BE_RALLY_WARED = 61,//0+0+0+name
    EN_TIPS_TYPY__MARCH_TIME_IS_REDUCED = 62,//item_id+0+0+name
    EN_TIPS_TYPY__RALLY_WAR_BEGIN_TO_ASSEMBLE = 63,//0+0+0+name  //开始集结

    EN_TIPS_TYPY__ASSIGN_HERO_ARRIVE = 71,//pos + type + lv
    EN_TIPS_TYPY__QUEST_REFRESHED = 72,//type+0+0  type:ETimeQuestType(daily=1 alliance=2 vip=6)
    EN_TIPS_TYPY__REMOVED_FROM_ALLIANCE = 73,//alliance_flag+0+0+联盟名称
    EN_TIPS_TYPY__LOAD_FINISHED = 74,//map_type+0+0
    EN_TIPS_TYPY__BE_SCOUTED = 75,//pos+type+0+name
    EN_TIPS_TYPY__CRYSTAL_IS_DESTROYED = 76,// crystal_id+0+0

    EN_TIPS_TYPY__TRADE_BE_RECEPTED = 77,// 0+0+0+target_user_name
    EN_TIPS_TYPY__TRADE_RETURN = 78,// gold_num

    EN_TIPS_TYPE__ALLIANCE_TASK = 79, //type+time, type=0联盟任务开始预告，type=1联盟任务开始预告
    EN_TIPS_TYPE__DRAGON_ENERGY_OK = 80,//龙体力恢复满
    EN_TIPS_TYPE__KING_DUB = 81,//type+0+0+name,免去(type=0)授予(type=1)称号
    EN_TIPS_TYPE__BLACKUSER_DEL = 82,//0+0+0+name,黑名单删除
    EN_TIPS_TYPE__KNIGHT_DISMISS = 83, //id,骑士被撤职
    EN_TIPS_TYPE__DRAGON_KILL_MONSTER_GET_REWARD = 84, //[[type,id,num]]

    EN_TIPS_TYPE__ASSIGN_KNIGHT_ARRIVE = 85, //pos + type + lv 

    EN_TIPS_TYPE__DRAGON_KILL_LEADER_MONSTER_GET_REWARD = 86, //[[type,id,num]]

    EN_TIPS_TYPE__UNLOCK_DRAGON = 87,
    EN_TIPS_TYPE__KNIGHT_LV_UP = 88, // knight id

    EN_TIPS_TYPE__SCOUT_SUCC = 89, //pos
    EN_TIPS_TYPE__SCOUT_FAIL = 90, //pos
    EN_TIPS_TYPE__TROOP_RETURN = 91,
    EN_TIPS_TYPE__TOP_QUEST_FINISH = 92,//quest_id
    EN_TIPS_TYPE__TASK_FINISH = 93,//task_id
    EN_TIPS_TYPE__BE_REINFORCE_NORMAL_OK = 94, // cid+uid+0+name
    EN_TIPS_TYPE__SPEED_UP_RALLY_REINFORCE = 95, // uid1+uid2+0+name1+name2
    EN_TIPS_TYPE__TRIAL_ACTIVATE_RAGE_MODE = 96,
    EN_TIPS_TYPE__TRIAL_GIFT = 97, // [[int, int, int]] [[type, id, num]]
    EN_TIPS_TYPE__CAMP_SUCC = 98,
    EN_TIPS_TYPE__SCOUT_BE_PREVENTED = 99, //scout被防止了.. // cid+uid+0+name
    EN_TIPS_TYPE__PREVENT_SCOUT = 100, //防止了对方的scout // uid+0+0+name

    EN_TIPS_TYPE__THRONE_DISMISS_ALL = 101,
    EN_TIPS_TYPE__THRONE_RECALL = 102,
    EN_TIPS_TYPE__THRONE_REINFORCE_ARRIVE = 103,
    EN_TIPS_TYPE__THRONE_ASSIGN_ARRIVE = 104,
};

enum EQuestType
{
    EN_QUEST_TYPE_UPGRADE_BUILDING = 0,
    EN_QUEST_TYPE_CONSTRUCT_BUILDING = 1, //无
    EN_QUEST_TYPE_UPGRADE_RESEARCH = 2,
    EN_QUEST_TYPE_INCREASE_PRODUCTION = 3,
    EN_QUEST_TYPE_INCREASE_CITY_BASE = 4, //无
    EN_QUEST_TYPE_TROOP = 5,
    EN_QUEST_TYPE_AK_PLAYER = 6, //无
    EN_QUEST_TYPE_ROB_RESOURCE = 7, //无
    EN_QUEST_TYPE_LEVEL_UP = 8, //无
    EN_QUEST_TYPE_MISC = 9, //无
    EN_QUEST_TYPE_QUEST_NUM = 10, //无
    EN_QUEST_TYPE_BEGIN_TRAIN = 11, //无
    EN_QUEST_TYPE_BEGIN_RESEARCH = 12,//无
    EN_QUEST_TYPE_BEGIN_BUILDING = 13,//无
    EN_QUEST_TYPE_POPULATION = 14, //无
    EN_QUEST_TYPE_FORT = 15,
};

enum EEventMsgType
{
    EN_EVENT_MSG_TYPE__RANK = 0,    // rank+0+0
    EN_EVENT_MSG_TYPE__SCORE = 1,   // reward_lv+0+0
};

enum EBWHonour
{
    EN_BW_HONOUR_EMPEROR = 1,
    EN_BW_HONOUR_REX = 2,
    EN_BW_HONOUR_DUKE = 4,
    EN_BW_HONOUR_MARCHESE = 8,
    EN_BW_HONOUR_QUEST_1 = 16, //需要产品命名  
    EN_BW_HONOUR_QUEST_2 = 32,
};

//for show flag
enum EGuideTypeId
{
    EN_GUIDE_ID__UPGRADE_HERO = 20,
    EN_GUIDE_ID__HELP_ALLIANCE = 24,
    EN_GUIDE_ID__COLLECT_RECOURCE = 25,
    EN_GUIDE_ID__WIN_WAR = 26,
    EN_GUIDE_ID__FUSE_CARD = 55,
    EN_GUIDE_ID__ABSORB_CARD = 56,
    EN_GUIDE_ID__SMELT_CARD_EQUIPMENT = 57,
};

enum EVIPBONUSTYPE
{
    EN_VIP_BONUS_TYPE_VIP_SHOW = 0,
    EN_VIP_BONUS_TYPE_GOLD,
    EN_VIP_BONUS_TYPE_FOOD,
    EN_VIP_BONUS_TYPE_WOOD,
    EN_VIP_BONUS_TYPE_STONE,
    EN_VIP_BONUS_TYPE_ORE,
    EN_VIP_BONUS_TYPE_DAILY_QUEST_NUM,
    EN_VIP_BONUS_TYPE_AL_QUEST_NUM,
    // EN_VIP_BONUS_TYPE_VIP_QUEST_NUM,
    EN_VIP_BONUS_TYPE_MARCH_SPEED,
    EN_VIP_BONUS_TYPE_TROOP_ATTACK,
    EN_VIP_BONUS_TYPE_TROOP_HEALTH,
    EN_VIP_BONUS_TYPE_TRAP_ATTACK,
    EN_VIP_BONUS_TYPE_TRAP_HEALTH,
    EN_VIP_BONUS_TYPE_TROOP_LOAD_BONUS,
    EN_VIP_BONUS_TYPE_GATHERER_SPEED,
    EN_VIP_BONUS_TYPE_AUTOCOMPLETE_DAILY_QUEST,
    EN_VIP_BONUS_TYPE_AUTOCOMPLETE_AL_QUEST,
    // EN_VIP_BONUS_TYPE_AUTOCOMPLETE_VIP_QUEST
};

// 连续登录的奖励类型
enum ECONNLOGINBONUSTYPE
{
    EN_CONN_LOGIN_BONUS_TYPE_ITEM = 1,
    EN_CONN_LOGIN_BONUS_TYPE_RESOURCE,
    EN_CONN_LOGIN_BONUS_TYPE_LOYALTY_FUND,
    EN_CONN_LOGIN_BONUS_TYPE_GEMS,
    EN_CONN_LOGIN_BONUS_TYPE_VIP_POINT,
};

enum EReportType
{
    EN_REPORT_TYPE_ATTACK = 0,
    EN_REPORT_TYPE_SCOUT,
    EN_REPORT_TYPE_TRANSPORT,
    EN_REPORT_TYPE_REINFORCE,
    EN_REPORT_TYPE_OCCUPY,
    EN_REPORT_TYPE_RALLY_WAR,
    EN_REPORT_TYPE_RALLY_REINFORCE,
    EN_REPORT_TYPE_DRAGON_RELEASE,
    EN_REPORT_TYPE_DRAGON_KILLED,
    EN_REPORT_TYPE_DRAGON_MONSTER,//v1.2_wave@2015.07.24
    EN_REPORT_TYPE_DRAGON_COLLECT,
    EN_REPORT_TYPE_DRAGON_ASSIGN,
    EN_REPORT_TYPE_TRADE, // nemo
    EN_REPORT_TYPE_COLLECT_TAX, // nemo v1.3
    EN_REPORT_TYPE_PAY_TAX, // nemo v1.3
    EN_REPORT_TYPE_CAMP,

    EN_REPORT_TYPE_THRONE_SCOUT,
    EN_REPORT_TYPE_THRONE_ATTACK,
    EN_REPORT_TYPE_THRONE_RALLY_WAR,
    EN_REPORT_TYPE_THRONE_REINFORCE,
    EN_REPORT_TYPE_THRONE_DISPATCH,
    EN_REPORT_TYPE_IDOL_SCOUT,
    EN_REPORT_TYPE_IDOL_ATTACK,

    EN_REPORT_TYPE_LOST_THRONE = 23,
    EN_REPORT_TYPE_OCCUPY_THRONE,
    EN_REPORT_TYPE_THRONE_PEACE_TIME,
    EN_REPORT_TYPE_THRONE_PEACE_TIME_END,
};

enum EReportResult
{
    EN_REPORT_RESULT_WIN = 0,// action执行成功
    EN_REPORT_RESULT_LOSE,   // 战争类action 打输
    EN_REPORT_RESULT_TARGET_CHANGE, //目标已经离开
    EN_REPORT_RESULT_TARGET_PEACETIME, //目标处于peacetime
    EN_REPORT_RESULT_SAME_ALLIANCE,    //与目标同联盟
    EN_REPORT_RESULT_DIFF_ALLIANCE,    //与目标不同联盟
    EN_REPORT_RESULT_TARGET_COLLECTED_OUT, //目标被采集光
    EN_REPORT_RESULT_TARGET_HAS_OCCUPIED, //目标已被占领
    EN_REPORT_RESULT_TARGET_REINFORCE_FULL, //大使馆满了
    EN_REPORT_RESULT_TARGET_IS_FRIEND, //友好联盟
    EN_REPORT_RESULT_SELF_PEACETIME, //自己处于peacetime
    EN_REPORT_RESULT_BE_DISMISSED, //被遣返
    EN_REPORT_RESULT_RECALL, //玩家自己召回
    EN_REPORT_RESULT_TROOP_LIMIT, //军队数量超过集结上限
    EN_REPORT_RESULT_DRAGON_ESCAPE, //英雄逃跑
    EN_REPORT_RESULT_HERO_RESCUE, //英雄被救
    EN_REPORT_RESULT_DRAGON_RELEASE, //英雄被释放
    EN_REPORT_RESULT_RALLY_WAR_END, //rallywar 已经结束
    EN_REPORT_RESULT_NOT_IN_ALLIANCE, //不在联盟中
    EN_REPORT_RESULT_EXIST_DRAGON, //已经有英雄
    EN_REPORT_RESULT_NO_EMBASSY, //没有大使馆
    EN_REPORT_RESULT_GIVE_UP_PROVINCE, //已有省会或王座, 放弃占领新省会
    EN_REPORT_RESULT_OCCUPY_LAIR_NUM_LIMIT, //拉取巢穴人数到达上限
    EN_REPORT_RESULT_OCCUPY_LAIR_WRONG_AL, //巢穴被其他联盟占领
    EN_REPORT_RESULT_OCCUPY_LAIR_NO_AL, //必须加入联盟才能拉取巢穴
    EN_REPORT_RESULT_WILD_NOT_NORMAL, // 地块不是空地

    EN_REPORT_RESULT_THRONE_PEACE_TIME, //王座和平期
    EN_REPORT_RESULT_THRONE_SAME_ALLIANCE, //王座属于同一联盟
    EN_REPORT_RESULT_IDOL_PEACE_TIME, //神像非争夺期
    EN_REPORT_RESULT_IDOL_PEACE_TIME_FOR_THRONE, //神像处于王座和平期
    EN_REPORT_RESULT_HAS_REINFORCED_THRONE, //已经reinforce过了...
    EN_REPORT_RESULT_SCOUT_BE_PREVENT, //scout被防止了..
};

enum EAuctionStat  //拍卖行信息
{
    EN_AUCTION_NORMAL = 0,
    EN_AUCTION_NEW_ITEM_SOLD,
};

enum EBackPackItem      //背包物品类型
{
    EN_BACKPACK_ITEM_ALL = 0,
    EN_BACKPACK_ITEM_HELMET,
    EN_BACKPACK_ITEM_ARMOR,
    EN_BACKPACK_ITEM_AROFOIL,
    EN_BACKPACK_ITEM_CLAW,
    EN_BACKPACK_ITEM_CRYSTAL,
    EN_BACKPACK_ITEM_MATERIAL,
    EN_BACKPACK_ITEM_EQUIPMENT,
};

enum EInviteQuestType
{
    EN_INVITE_QUEST_TYPE__CASTAL_LV = 0,
    EN_INVITE_QUEST_TYPE__END = 64,
};

enum EAllianceTaskType
{
    EN_ALLIANCE_RELIC_UPGRADE_TASK = 0,
};

enum EBackpackType
{
    EN_BACK_PACK_TYPE__DRAGON = 0,
    EN_BACK_PACK_TYPE__CARD
};

enum ERankType
{
    EN_RANK_TYPE_PLAYER_CHAMPION = 0,
    EN_RANK_TYPE_PLAYER_FORCE_KILL,
    EN_RANK_TYPE_PLAYER_TROOPS_KILL,
    EN_RANK_TYPE_PLAYER_FORCE,
    EN_RANK_TYPE_PLAYER_TROOPS_KDR,
    EN_RANK_TYPE_PLAYER_BATTLE_WON,
    EN_RANK_TYPE_PLAYER_BWLR,  //Battles Won/Lost Ration
    EN_RANK_TYPE_PLAYER_DRAGON_CAPTURED,
    EN_RANK_TYPE_PLAYER_DRAGON_EXECUTED,
    EN_RANK_TYPE_PLAYER_EVIL_TROOP_KILL,
    EN_RANK_TYPE_PLAYER_EVIL_FORCE_KILL,
    EN_RANK_TYPE_PLAYER_GAIN_RESOURCE,
    EN_RANK_TYPE_PLAYER_TRANSPORT_RESOURCE_0,
    EN_RANK_TYPE_PLAYER_TRANSPORT_RESOURCE_1,
    EN_RANK_TYPE_PLAYER_TRANSPORT_RESOURCE_2,
    EN_RANK_TYPE_PLAYER_TRANSPORT_RESOURCE_3,
    EN_RANK_TYPE_PLAYER_TRANSPORT_RESOURCE_4,
    EN_RANK_TYPE_PLAYER_KILL_MONSTER,
    EN_RANK_TYPE_ALLIANCE_CHAMPION = 100,
    EN_RANK_TYPE_ALLIANCE_FORCE_KILL,
    EN_RANK_TYPE_ALLIANCE_TROOPS_KILL,
    EN_RANK_TYPE_ALLIANCE_FORCE,
    EN_RANK_TYPE_ALLIANCE_TROOPS_KDR,
    EN_RANK_TYPE_ALLIANCE_BATTLE_WON,
    EN_RANK_TYPE_ALLIANCE_BWLR,  //Battles Won/Lost Ration
    EN_RANK_TYPE_ALLIANCE_HELP,
    EN_RANK_TYPE_ALLIANCE_FUND,
    EN_RANK_TYPE_ALLIANCE_GIFT_POINT,
    EN_RANK_TYPE_ALLIANCE_DRAGON_CAPTURED,
    EN_RANK_TYPE_ALLIANCE_DRAGON_EXECUTED,
    EN_RANK_TYPE_ALLIANCE_EVIL_TROOP_KILL,
    EN_RANK_TYPE_ALLIANCE_EVIL_FORCE_KILL,
    EN_RANK_TYPE_ALLIANCE_THRONE_OCCUPY,
};

enum EBattleType
{
    EN_BATTLE_TYPE__NO_OP = 0,
    EN_BATTLE_TYPE__ATTACK_CITY,
    EN_BATTLE_TYPE__ATTCK_OCCUPY,
    EN_BATTLE_TYPE__ATTCK_WILD,
    EN_BATTLE_TYPE__RALLY_CITY,
    EN_BATTLE_TYPE__RALLY_WILD,
    EN_BATTLE_TYPE__ATTACK_OCCUPY_LAIR,
    EN_BATTLE_TYPE__ATTACK_CAMP,

    EN_BATTLE_TYPE__ATTACK_IDOL,
    EN_BATTLE_TYPE__RALLY_THRONE,
};

enum ETimeQuestType
{
    EN_TIME_QUEST_TYPE_BEGIN = 0,
    EN_TIME_QUEST_TYPE_DAILY = 1,
    EN_TIME_QUEST_TYPE_ALLIANCE = 2,
    EN_TIME_QUEST_TYPE_MISTERY = 3,
    EN_TIME_QUEST_TYPE_NEW_USER_MISTERY = 4,
    EN_TIME_QUEST_TYPE_NEW_USER_DAILY = 5,
    EN_TIME_QUEST_TYPE_VIP = 6,
    EN_TIME_QUEST_TYPE_END,
};

enum SGlobalResType
{
    EN_GLOBALRES_TYPE_ITEM = 0,
    EN_GLOBALRES_TYPE_GEM,
    EN_GLOBALRES_TYPE_HONOR, //useless
    EN_GLOBALRES_TYPE_RESOURCE = 3,
    EN_GLOBALRES_TYPE_TROOP,
    EN_GLOBALRES_TYPE_LORD_EXP,
    EN_GLOBALRES_TYPE_POPULATION, //useless
    EN_GLOBALRES_TYPE_BUILDING_LV = 7,
    EN_GLOBALRES_TYPE_RESEARC_LV,
    EN_GLOBALRES_TYPE_LORD_LV,
    EN_GLOBALRES_TYPE_AL_GIFT,
    EN_GLOBALRES_TYPE_VIP_POINT,
    EN_GLOBALRES_TYPE_RATE, //useless
    EN_GLOBALRES_TYPE_HAPPYNESS, //useless
    EN_GLOBALRES_TYPE_VIP_LV,//useless
    EN_GLOBALRES_TYPE_VIP_TIME = 15,
    EN_GLOBALRES_TYPE_FORT,
    EN_GLOBALRES_TYPE_KNIGHT_EXP,
    EN_GLOBALRES_TYPE_KNIGHT_LV,
    EN_GLOBALRES_TYPE_SPEEDUP_TIME,
    EN_GLOBALRES_TYPE_SPEEDUP_PERCENT,
    EN_GLOBALRES_TYPE_DRAGON_SKILL_LV,
    EN_GLOBALRES_TYPE_ADD_KNIGHT_EXP_HIGH_LV,

    EN_GLOBALRES_TYPE_EQUIP = 23,
    EN_GLOBALRES_TYPE_EQUIP_CRYSTAL = 24,
    EN_GLOBALRES_TYPE_EQUIP_MATERIAL = 25,
    EN_GLOBALRES_TYPE_FUND = 26,
    EN_GLOBALRES_TYPE_LOYLTY = 27,
    EN_GLOBALRES_TYPE_DRAGON_SKILL_POINT = 28,
    EN_GLOBALRES_TYPE_DRAGON_INTEGRATION = 29,	//积分
    EN_GLOBALRES_TYPE_BUILDING_OBSTACLE = 30,	//只用于障碍物
    EN_GLOBALRES_TYPE_BUILD_LEVEL_FUNC = 31,   //用function type为id表示的type

    EN_GLOBALRES_TYPE_EQUIP_SOUL = 32,
    EN_GLOBALRES_TYPE_EQUIP_PARTS = 33,

    EN_GLOBALRES_TYPE_DRAGON_ENERGY = 34,
    EN_GLOBALRES_TYPE_SPECIAL_CRYSTAL = 35,

    EN_GLOBALRES_TYPE_MONSTER_SKILL_LV = 36,
    EN_GLOBALRES_TYPE_PURPLE_GOLD=37,
    EN_GLOBALRES_TYPE_AGE = 38,
    EN_GLOBALRES_TYPE_REGISTER_TIME = 39,

    //WAVE@20160408
    EN_GLOBALRES_TYPE_THRONE_RESEARCH_LV = 40,
    EN_GLOBALRES_TYPE_LORD_SKILL_POINT = 41,
    EN_GLOBALRES_TYPE_LORD_SKILL_LV = 42,
    EN_GLOBALRES_TYPE_THRONE_RESOURCE = 43,
    EN_GLOBALRES_TYPE_DRAGON_EXP = 44,
    EN_GLOBALRES_TYPE_DRAGON_LV = 45,

    EN_GLOBALRES_TYPE_THRONE_RESEARCH_SPEEDUP = 49, //废弃
    EN_GLOBALRES_TYPE_MATERIAL_TYPE = 50,
    EN_GLOBALRES_TYPE_SCROLL = 51,
    EN_GLOBALRES_TYPE_DRAGON_SHARD = 52,
    EN_GLOBALRES_TYPE_TRIAL_GOBLIN = 53,

    EN_GLOBALRES_TYPE_LORD_IMAGE = 54,
    EN_GLOBALRES_TYPE_DECORATION = 55,
    EN_GLOBALRES_TYPE_OTHER = 100,
    EN_GLOBALRES_TYPE_END,
};

enum RewardType
{
    EREWARD_TYPE_ALL = 0,
    EREWARD_TYPE_SOME = 1,
    EREWARD_TYPE_ONE = 2,
};

enum EGlobalAttrType
{
    EN_GLOBAL_ATTRIBUTE_TYPE_LV = 1,
    EN_GLOBAL_ATTRIBUTE_TYPE_QUANLITY = 2,//品质
    EN_GLOBAL_ATTRIBUTE_TYPE_ABSORT_TIME = 3,//吸收次数
};

enum EItemEffectType
{
    EN_ITEM_EFFECT_TYPE_NOTHING = 0,
    EN_ITEM_EFFECT_TYPE_REFRESH_DAILY_QUEST,
    EN_ITEM_EFFECT_TYPE_REFRESH_AL_QUEST,
    EN_ITEM_EFFECT_TYPE_ADD_GOLD_NUM,
    EN_ITEM_EFFECT_TYPE_ADD_FOOD_NUM,
    EN_ITEM_EFFECT_TYPE_ADD_WOOD_NUM,
    EN_ITEM_EFFECT_TYPE_ADD_STONE_NUM,
    EN_ITEM_EFFECT_TYPE_ADD_ORE_NUM,
    EN_ITEM_EFFECT_TYPE_ADD_HERO_EXP,
    EN_ITEM_EFFECT_TYPE_ADD_HERO_EXP_HIGH_LV,
    EN_ITEM_EFFECT_TYPE_ADD_POPULATION,
    EN_ITEM_EFFECT_TYPE_SPEED_UP_ACTION_TIME,
    EN_ITEM_EFFECT_TYPE_SPEED_UP_ACTION_TIME_PERCENT,
    EN_ITEM_EFFECT_TYPE_SPEED_UP_MARCHSPEED_TIME_PERCENT,
    EN_ITEM_EFFECT_TYPE_SPEED_UP_BUILDING_TIME_PERCENT,
    EN_ITEM_EFFECT_TYPE_SPEED_UP_RESEARCH_TIME_PERCENT,
    EN_ITEM_EFFECT_TYPE_SPEED_UP_TRAIN_AND_TREAT_TIME_PERCENT,
    EN_ITEM_EFFECT_TYPE_CHEST,
    EN_ITEM_EFFECT_TYPE_ADD_VIP_POINT,
    EN_ITEM_EFFECT_TYPE_ADD_HAPPINESS,
    EN_ITEM_EFFECT_TYPE_DESCONSTRUCT,

};

enum EBufferInfo
{
    EN_BUFFER_INFO_BEGIN = 0,

    EN_BUFFER_INFO_GOLD_PRODUCTION_PERCENT = 1,
    EN_BUFFER_INFO_FOOD_PRODUCTION_PERCENT = 2,
    EN_BUFFER_INFO_WOOD_PRODUCTION_PERCENT = 3,
    EN_BUFFER_INFO_STON_PRODUCTION_PERCENT = 4,
    EN_BUFFER_INFO_ORE_PRODUCTION_PERCENT = 5,
    EN_BUFFER_INFO_RESOURCE_CAPACITY = 6,
    EN_BUFFER_INFO_RESOURCE_PROTECTION = 7,
    EN_BUFFER_INFO_BUILDING_SPEED_UP_PERCENT = 8,
    EN_BUFFER_INFO_RESEARCH_SPEED_UP_PERCENT = 9,
    EN_BUFFER_INFO_SIEGE_ATTACK = 10,
    EN_BUFFER_INFO_SIEGE_LIFE = 11,
    EN_BUFFER_INFO_SOWAR_ATTACK = 12,
    EN_BUFFER_INFO_SOWAR_LIFE = 13,
    EN_BUFFER_INFO_INFANTRY_ATTACK = 14,
    EN_BUFFER_INFO_INFANTRY_LIFE = 15,
    EN_BUFFER_INFO_REMOTE_ATTACK = 16,
    EN_BUFFER_INFO_REMOTE_LIFE = 17,
    EN_BUFFER_INFO_PROMOTE_TROOP_TYPE_1 = 18,
    EN_BUFFER_INFO_PROMOTE_TROOP_TYPE_2 = 19,
    EN_BUFFER_INFO_PROMOTE_TROOP_TYPE_3 = 20,
    EN_BUFFER_INFO_PROMOTE_TROOP_TYPE_4 = 21,
    EN_BUFFER_INFO_PROMOTE_TROOP_TYPE_5 = 22,
    EN_BUFFER_INFO_PROMOTE_TROOP_TYPE_6 = 23,
    EN_BUFFER_INFO_PROMOTE_TROOP_TYPE_7 = 24,
    EN_BUFFER_INFO_PROMOTE_TROOP_TYPE_8 = 25,
    EN_BUFFER_INFO_PROMOTE_TROOP_TYPE_9 = 26,
    EN_BUFFER_INFO_PROMOTE_TROOP_TYPE_10 = 27,
    EN_BUFFER_INFO_PROMOTE_TROOP_TYPE_11 = 28,
    EN_BUFFER_INFO_PROMOTE_TROOP_TYPE_12 = 29,
    EN_BUFFER_INFO_PROMOTE_TROOP_TYPE_13 = 30,
    EN_BUFFER_INFO_PROMOTE_TROOP_TYPE_14 = 31,
    EN_BUFFER_INFO_PROMOTE_TROOP_TYPE_15 = 32,
    EN_BUFFER_INFO_PROMOTE_TROOP_TYPE_16 = 33,
    EN_BUFFER_INFO_TROOP_LOAD = 34,
    EN_BUFFER_INFO_MARCH_SPEED = 35,
    EN_BUFFER_INFO_ALL_RESOURCE_PRODUCTION_PERCENT = 36,
    EN_BUFFER_INFO_ALL_RESOURCE_CAPACITY = 37,
    EN_BUFFER_INFO_ALL_RESOURCE_PROTECTION = 38,
    EN_BUFFER_INFO_ALL_TROOP_TRAIN_SPEED = 39,
    EN_BUFFER_INFO_ALL_TROOP_TRAIN_COST = 40,
    EN_BUFFER_INFO_ALL_TROOP_ATTACK = 41,
    EN_BUFFER_INFO_ALL_TROOP_LIFE = 42,
    EN_BUFFER_INFO_ALL_TROOP_UPKEEP = 43,
    EN_BUFFER_INFO_QUEUE_NUM = 44,
    EN_BUFFER_INFO_PEACE_TIME = 45,
    EN_BUFFER_INFO_COLLECT_SPEED = 46,
    EN_BUFFER_INFO_VIP_ACTIVATE = 47,
    EN_BUFFER_INFO_TROOP_SIZE = 48,
    EN_BUFFER_INFO_FOOD_COLLECT_SPEED = 49,
    EN_BUFFER_INFO_WOOD_COLLECT_SPEED = 50,
    EN_BUFFER_INFO_STONE_COLLECT_SPEED = 51,
    EN_BUFFER_INFO_ORE_COLLECT_SPEED = 52,
    EN_BUFFER_INFO_GOLD_COLLECT_SPEED = 53,
    EN_BUFFER_INFO_BUILD_WALL_SPEED = 54,
    EN_BUFFER_INFO_WALL_ATTACK = 55,
    EN_BUFFER_INFO_WALL_DEFENSE = 56,
    EN_BUFFER_INFO_WALL_LIFE = 57,
    EN_BUFFER_INFO_SIEGE_DEFENSE = 58,
    EN_BUFFER_INFO_SOWAR_DEFENSE = 59,
    EN_BUFFER_INFO_REMOTE_DEFENSE = 60,
    EN_BUFFER_INFO_INFANTRY_DEFENSE = 61,
    EN_BUFFER_INFO_ALL_TROOP_DEFENSE = 62,
    EN_BUFFER_INFO_ASSIGN_QUEUE_NUM = 63,
    EN_BUFFER_INFO_EACH_TROOP_SIZE = 64,
    EN_BUFFER_INFO_REINFORCE_QUEUE_NUM = 65,
    EN_BUFFER_INFO_REINFORCE_SPEED_UP_PERCENT = 66, // transport & reinforce
    EN_BUFFER_INFO_FOOD_PROTECTION = 67,
    EN_BUFFER_INFO_WODD_PROTECTION = 68,
    EN_BUFFER_INFO_STONE_PROTECTION = 69,
    EN_BUFFER_INFO_ORE_PROTECTION = 70,
    EN_BUFFER_INFO_POPULATION_CAPICATY = 71,
    EN_BUFFER_INFO_HOSPITAL_CAPICATY = 72,
    EN_BUFFER_INFO_GOLD_CAPICATY = 73,
    EN_BUFFER_INFO_FOOD_CAPICATY = 74,
    EN_BUFFER_INFO_WOOD_CAPICATY = 75,
    EN_BUFFER_INFO_STONE_CAPICATY = 76,
    EN_BUFFER_INFO_ORE_CAPICATY = 77,
    EN_BUFFER_INFO_REDUCE_ALTER_RESOURCE = 78,
    EN_BUFFER_INFO_REDUCE_ALTER_GEM = 79,
    EN_BUFFER_INFO_KNIGHT_NUM = 80,
    EN_BUFFER_INFO_OUT_CITY_BLOCK = 81,
    EN_BUFFER_INFO_IN_CITY_BLOCK = 82,
    EN_BUFFER_INFO_REDUCE_TRANSPORT_RATE = 83,
    EN_BUFFER_INFO_ADD_FORCE = 84,
    EN_BUFFER_INFO_WALL_CAPICATY = 85,
    EN_BUFFER_INFO_GOLD_PRODUCTION = 86,
    EN_BUFFER_INFO_FOOD_PRODUCTION = 87,
    EN_BUFFER_INFO_WOOD_PRODUCTION = 88,
    EN_BUFFER_INFO_STRON_PRODUCTION = 89,
    EN_BUFFER_INFO_ORE_PRODUCTION = 90,
    EN_BUFFER_INFO_FREE_INSTANT_FINISH_TIME = 91,
    EN_BUFFER_INFO_ALLIANCE_HELP_NUM = 92,
    EN_BUFFER_INFO_DAILY_QUEST_NUM = 93,
    EN_BUFFER_INFO_ALLIANCE_NUM = 94,
    EN_BUFFER_INFO_VIP_QUEST_NUM = 95,
    EN_BUFFER_INFO_AUTO_FINISH_DAILY = 96,
    EN_BUFFER_INFO_AUTO_FINISH_ALLIANCE = 97,
    EN_BUFFER_INFO_UPGRADE_EQUIP_SPEED = 98,
    EN_BUFFER_INFO_GOLD_PROTECTION = 99,
    EN_BUFFER_INFO_ASSIGN_TROOP_TOTAL_SIZE = 100,
    EN_BUFFER_INFO_CAN_REFINFORCE_TROOP_TOTAL_SIZE = 101,
    EN_BUFFER_INFO_TROOP_TRAINING_QUEUE_NUM = 102,
    EN_BUFFER_INFO_TROOP_HEALING_QUEUE_NUM = 103,
    EN_BUFFER_INFO_FORT_TRAINING_QUEUE_NUM = 104,
    EN_BUFFER_INFO_TRANSPORT_LIMIT = 105,
    EN_BUFFER_INFO_SECOND_BUILDING_TASK = 106, //gt_v1.0_2015.7.31@nathan
    EN_BUFFER_INFO_FORT_HOSPITAL_CAPICATY = 107,
    EN_BUFFER_INFO_DEFNESE_TROOP_SIZE = 108, //gt_v1.0_2015.8.6@nathan
    EN_BUFFER_INFO_CAN_DECONSTRUCT_NUM = 109, //gt_v1.0_2015.8.14@nathan
    EN_BUFFER_INFO_TROOP_SIZE_PERCENT = 110,

    EN_BUFFER_INFO_INFANTRY_TRAIN_SPEED = 111, //gt_v1.0_2015.9.2@nathan
    EN_BUFFER_INFO_REMOTE_TRAIN_SPEED = 112,
    EN_BUFFER_INFO_SOWAR_TRAIN_SPEED = 113,
    EN_BUFFER_INFO_SIEGE_TRAIN_SPEED = 114,
    EN_BUFFER_INFO_INFANTRY_POPULATION = 115,
    EN_BUFFER_INFO_REMOTE_POPULATION = 116,
    EN_BUFFER_INFO_SOWAR_POPULATION = 117,
    EN_BUFFER_INFO_SIEGE_POPULATION = 118,
    EN_BUFFER_INFO_OBSTACLE_LEVEL = 119,

    EN_BUFFER_INFO_HERO_ATTACK = 120,  //nathan@2015.10.9
    EN_BUFFER_INFO_HERO_CRIT = 121, 
    EN_BUFFER_INFO_MONSTER_DEFENSE_DOWN = 122,
    EN_BUFFER_INFO_HERO_MARCH_TIME = 123,
    EN_BUFFER_INFO_HERO_COLLECT = 124,//------------no use
    EN_BUFFER_INFO_HERO_COMBO = 125,
    EN_BUFFER_INFO_HERO_STAMINA_RECOVER = 126,//------------no use
    EN_BUFFER_INFO_HERO_STAMINA_USE = 127,
    EN_BUFFER_INFO_HERO_STAMINA_LIMIT = 128,
    EN_BUFFER_INFO_JAIL_LIMIT = 129,
    EN_BUFFER_INFO_RALLY_TROOP_LIMIT = 130,
    EN_BUFFER_INFO_EXECUTE_TIME = 131,//------------no use

    EN_BUFFER_INFO_INFANTRY_TRAIN_SPEED_ONLY = 132,
    EN_BUFFER_INFO_INFANTRY_HEAL_SPEED_ONLY = 133,
    EN_BUFFER_INFO_INFANTRY_MARCH_SPEED_ONLY = 134,
    EN_BUFFER_INFO_REMOTE_TRAIN_SPEED_ONLY = 135,
    EN_BUFFER_INFO_REMOTE_HEAL_SPEED_ONLY = 136,
    EN_BUFFER_INFO_REMOTE_MARCH_SPEED_ONLY = 137,
    EN_BUFFER_INFO_SOWAR_TRAIN_SPEED_ONLY = 138,
    EN_BUFFER_INFO_SOWAR_HEAL_SPEED_ONLY = 139,
    EN_BUFFER_INFO_SOWAR_MARCH_SPEED_ONLY = 140,
    EN_BUFFER_INFO_SIEGE_TRAIN_SPEED_ONLY = 141,
    EN_BUFFER_INFO_SIEGE_HEAL_SPEED_ONLY = 142,
    EN_BUFFER_INFO_SIEGE_MARCH_SPEED_ONLY = 143,

    EN_BUFFER_INFO_SRATEGIC_INFANTRY_ATTACK = 144,//------------no use
    EN_BUFFER_INFO_SRATEGIC_INFANTRY_DEFENSE = 145,//------------no use
    EN_BUFFER_INFO_SRATEGIC_INFANTRY_LIFE = 146,//------------no use
    EN_BUFFER_INFO_SRATEGIC_REMOTE_ATTACK = 147,//------------no use
    EN_BUFFER_INFO_SRATEGIC_REMOTE_DEFENSE = 148,//------------no use
    EN_BUFFER_INFO_SRATEGIC_REMOTE_LIFE = 149,//------------no use
    EN_BUFFER_INFO_SRATEGIC_SOWAR_ATTACK = 150,//------------no use
    EN_BUFFER_INFO_SRATEGIC_SOWAR_DEFENSE = 151,//------------no use
    EN_BUFFER_INFO_SRATEGIC_SOWAR_LIFE = 152,//------------no use
    
    EN_BUFFER_INFO_FORT_HEAL_SPEED = 153,

    EN_BUFFER_INFO_HERO_LEAD_TROOP_ATTACK = 154,
    EN_BUFFER_INFO_HERO_LEAD_TROOP_DEFENSE = 155,
    EN_BUFFER_INFO_HERO_LEAD_TROOP_LIFE = 156,

    EN_BUFFER_INFO_EQUIPMENT_CRAFT_SPEED = 157,//------------client use
    EN_BUFFER_INFO_EQUIPMENT_CRAFT_COST = 158,//------------client use

    EN_BUFFER_INFO_CORE_GATHERING_RATE = 159,
    EN_BUFFER_INFO_PARTS_GATHERING_RATE = 160,
    EN_BUFFER_INFO_MATERIAL_GATHERING_RATE = 161,
    EN_BUFFER_INFO_CRYSTAL_GATHERING_RATE = 162,

    EN_BUFFER_INFO_CORE_EQUIPMENT_DURATION = 163,
    EN_BUFFER_INFO_CORE_EQUIPMENT_LUCK = 164,

    EN_BUFFER_INFO_RALLY_WAR_SPEED = 165,
    EN_BUFFER_INFO_RALLY_WAR_INFANTRY_SPEED = 166,
    EN_BUFFER_INFO_RALLY_WAR_REMOTE_SPEED = 167,
    EN_BUFFER_INFO_RALLY_WAR_SOWAR_SPEED = 168,
    EN_BUFFER_INFO_RALLY_WAR_SIEGE_SPEED = 169,

    EN_BUFFER_INFO_FORT_QUEUE_NUM = 170,//------------no use
    EN_BUFFER_INFO_THRONE_BUFF = 171,//------------no use
    EN_BUFFER_INFO_PROVINCE_BUFF = 172,//------------no use

    EN_BUFFER_INFO_SPECIAL_BLOCK = 173,
    EN_BUFFER_INFO_TRADE_QUEUE_NUM = 174,
    EN_BUFFER_INFO_TRADE_QUEUE_NUM_MEANWHILE = 175,

    EN_BUFFER_INFO_REINFORCE_ATTACK = 177,
    EN_BUFFER_INFO_REINFORCE_DEFENSE = 178,
    EN_BUFFER_INFO_REINFORCE_LIFE = 179,
    EN_BUFFER_INFO_RALLY_ATTACK = 180,
    EN_BUFFER_INFO_RALLY_DEFENSE = 181,
    EN_BUFFER_INFO_RALLY_LIFE = 182,

    EN_BUFFER_INFO_ALL_TROOP_ONLY_TRAIN_SPEED = 183,
    EN_BUFFER_INFO_ALL_TROOP_ONLY_HEAL_SPEED = 184,

    EN_BUFFER_INFO_TRANSPORT_SPEED = 185,

    EN_BUFFER_INFO_TRANSPORT_QUEUE_NUM = 186,

    EN_BUFFER_INFO_TROOP1_TRAIN_COST = 189,
    EN_BUFFER_INFO_TROOP2_TRAIN_COST = 190,
    EN_BUFFER_INFO_TROOP3_TRAIN_COST = 191,
    EN_BUFFER_INFO_TROOP4_TRAIN_COST = 192,
    EN_BUFFER_INFO_FORT_TRAIN_COST = 193,

    EN_BUFFER_INFO_ALTAR_EXECUTE_TIME = 194,
    EN_BUFFER_INFO_UNLOCK_DRAGON_LV = 195,
    EN_BUFFER_INFO_DRAGON_EXP_BONUS = 196,
    EN_BUFFER_INFO_BUILDING_TIME_REDUCE = 197,
    EN_BUFFER_INFO_RESEARCH_TIME_REDUCE = 198,
    EN_BUFFER_INFO_REINFORCE_TROOP_NUM = 199,
    EN_BUFFER_INFO_DRAGON_CITY_BLOCK = 200,

    EN_BUFFER_INFO_KNIGHT_HALL_BASE_BUFF = 201, //rock@v1.2
    EN_BUFFER_INFO_EQUIP_CRISTAL_UNLOCK = 202,
    EN_BUFFER_INFO_INCREACE_DRAGON_SKILL_POINT = 203, //rock@v1.2
    EN_BUFFER_INFO_INCREACE_LORD_SKILL_POINT = 204,
    EN_BUFFER_INFO_INCREACE_MONSTER_SKILL_POINT = 205,

    EN_BUFFER_INFO_LORD_EXP_BONUS = 206,
    EN_BUFFER_INFO_SCOUT_PREVENT = 207,
    EN_BUFFER_INFO_OPEN_CRYSTAL_CHEST = 208,
    EN_BUFFER_INFO_OPEN_METERIAL_CHEST = 209,

    EN_BUFFER_INFO_USER_JSON_OUTPUT_END, //放到最后一个buff后面

    EN_BUFFER_INFO_END = 500,
};

enum EEncourgeMailType
{
    EN_MAIL_TYPE_BUILDING_UPGRADE = 0,
    EN_MAIL_TYPE_AGE = 1,
    EN_MAIL_TYPE_DRAGON_LV = 2,
    EN_MAIL_TYPE_NOTHING = 3,
    EN_MAIL_TYPE_VIP_LV = 4,
};

enum EMailDocId
{
    EN_MAIL_ID__WELCOME_TO_GAME = 1,
    EN_MAIL_ID__FIRST_JOIN_ALLIANCE,
    EN_MAIL_ID__FIRST_CREATE_ALLIANCE,
    EN_MAIL_ID__FIRST_BE_ATK,
    EN_MAIL_ID__FIRST_HOSPITAL_OVER,
    EN_MAIL_ID__PROTECTION_MODE_EXPIRED,
    EN_MAIL_ID__AGE_2,
    EN_MAIL_ID__AGE_3,
    EN_MAIL_ID__AGE_4,
    EN_MAIL_ID__MAIN_BASE_LEVEL_5,
    EN_MAIL_ID__JOINED_AN_ALLIANCE,
    EN_MAIL_ID__CREATE_ALLIANCE,
    EN_MAIL_ID__REQUEST_IS_DECLINED,
    EN_MAIL_ID__BE_DISMISS,
    EN_MAIL_ID__BE_PROMOTED,
    EN_MAIL_ID__BE_DEMOTED,
    EN_MAIL_ID__PERSON_GOAL,
    EN_MAIL_ID__PERSON_RANK,
    EN_MAIL_ID__ALLIANCE_GOAL,
    EN_MAIL_ID__ALLIANCE_RANK,

    //联盟关系相关
    EN_MAIL_ID__BE_FRIEND = 21,  //对方申请友好
    EN_MAIL_ID__CONFIRM_FRIEND,  //与对方关系变为友好
    EN_MAIL_ID__CONFIRM_NORMAL,  //与对方关系变为普通
    EN_MAIL_ID__CONFIRM_HOSTILE,  //与对方关系变为敌对
    EN_MAIL_ID__CANCEL_HOSTILE,  //对方解除了敌对

    EN_MAIL_ID__MAIN_BASE_LEVEL_10 = 26,
    EN_MAIL_ID__AL_GIFT_LV_UP,
    EN_MAIL_ID__OCCUPY_THRONE,
    EN_MAIL_ID__OCCUPY_PROVINCE,
    EN_MAIL_ID__ACCOUNT_IDENTIFY,
    EN_MAIL_ID__ACCOUNT_REGISTER,
    EN_MAIL_ID__ACCOUNT_BIND,
    EN_MAIL_ID__ACCOUNT_PASSWORD,
    EN_MAIL_ID__HERO_LV_7,
    EN_MAIL_ID__FIRST_IAP,
    EN_MAIL_ID__MAIN_BASE_LEVEL_15,

    EN_MAIL_ID__BE_HOSTILE = 37,  //对方设置了敌对
    EN_MAIL_ID__DELAY_PURCHASE,  //只在延迟购买时发

    EN_MAIL_ID__HARD_PERSON_GOAL = 39,
    EN_MAIL_ID__HARD_PERSON_RANK = 40,

    //41-60 nemo add 解锁兵相关的科技id全部是写死的...
    EN_MAIL_ID__CASTLE_FULL_LEVEL = 41,
    EN_MAIL_ID__FIRST_T3_TROOP_UNLOCK = 42,
    EN_MAIL_ID__FIRST_T4_TROOP_UNLOCK = 43,
    EN_MAIL_ID__FIRST_T4_FORT_UNLOCK = 44,
    EN_MAIL_ID__FIRST_COMPOSE_EQUIP = 45,
    EN_MAIL_ID__FIRST_COMPOSE_SOUL_EQUIP = 46,
    EN_MAIL_ID__FIRST_COMPOSE_TOP_SOUL_EQUIP = 47,
    EN_MAIL_ID__FIRST_HERO_ATTACK = 48,
    EN_MAIL_ID__FIRST_RALLY_WAR_FINISH = 49,
    EN_MAIL_ID__FIRST_TRANSPORT = 50,
    EN_MAIL_ID__FIRST_REINFORCE = 51,
    EN_MAIL_ID__FIRST_TRADE_FINISH = 52,
    EN_MAIL_ID__FIRST_CAPTURE_HERO = 53,
    EN_MAIL_ID__FIRST_EXECUTE_HERO = 54,
    EN_MAIL_ID__FIRST_HERO_LV_30 = 55,
    EN_MAIL_ID__FIRST_HERO_FULL_LV = 56,
    EN_MAIL_ID__RESEARCH_ALL_ECONOMICS = 57,
    EN_MAIL_ID__RESEARCH_ALL_HERO = 58,
    EN_MAIL_ID__VIP_LV_7 = 59,
    EN_MAIL_ID__VIP_LV_10 = 60,
    EN_MAIL_ID__INVITE = 61,
    EN_MAIL_ID__AUTO_TELL_NPC = 62, //自动说明自己是npc
    EN_MAIL_ID__GUIDE_TO_NEW_ALLIANCE = 63,

    EN_MAIL_ID__SUPPORT_AUTO_REPLY = 66,
    EN_MAIL_ID__THRONE_DRAGON_UNLOCK = 68, //TODO
    EN_MAIL_ID__DRAGON_UNLOCK = 69,

    EN_MAIL_ID__THEME_EVENT_GOAL = 78,  //主题活动goal达成邮件
    EN_MAIL_ID__THEME_EVENT_RANK = 79,  //主题活动rank奖励邮件

    EN_MAIL_ID__THRONE_HAS_BEEN_OCCUPIED = 80,

    EN_MAIL_ID__BE_DUBBED_TITLE = 82,

    EN_MAIL_ID__GIVE_GIFT = 83,
    EN_MAIL_ID__PICK_UP_GIFT = 84,
    EN_MAIL_ID__EVENT_SEND_SCORE = 85,
};

enum EJsonType
{
    EN_JSON_TYPE_UNKNOWN = 0,
    EN_JSON_TYPE_USER_JSON,
    EN_JSON_TYPE_MAIL_LIST,
    EN_JSON_TYPE_ALLIANCE_LIST, //al_dipomacy_get
    EN_JSON_TYPE_PLAYER_LIST,
    EN_JSON_TYPE_WALL,
    EN_JSON_TYPE_REPORT,
    EN_JSON_TYPE_AL_REPORT,
    EN_JSON_TYPE_MAP,
    EN_JSON_TYPE_OPERATE_BUFFER_INFO,
    EN_JSON_TYPE_ASSIST_LIST,
    EN_JSON_TYPE_SVR_LIST,
    EN_JSON_TYPE_EVENT,
    EN_JSON_TYPE_OPERATE_TASK_INFO,
    EN_JSON_TYPE_RALLY_WAR_INFO,
    EN_JSON_TYPE_RALLY_HISTORY,
    EN_JSON_TYPE_PLAYER_RECOMMEND,
    EN_JSON_TYPE_RANDOM_REWARD,
    EN_JSON_TYPE_IDOL_INFO,
    EN_JSON_TYPE_THRONE_INFO,
    EN_JSON_TYPE_END,
    EN_JSON_TYPE_RANK, //rank svrer

};

enum EBuffType
{
    EN_BUFF_TYPE_BASIC,
    EN_BUFF_TYPE_DRAGON_SKILL, //change
    EN_BUFF_TYPE_RESEARCH,
    EN_BUFF_TYPE_ITEM,
    EN_BUFF_TYPE_VIP,
    EN_BUFF_TYPE_EQUIP, //change
    EN_BUFF_TYPE_TITLE,
    EN_BUFF_TYPE_ALTAR,
    EN_BUFF_TYPE_THRONE,
    EN_BUFF_TYPE_FORT,
    EN_BUFF_TYPE_TROOP,
    EN_BUFF_TYPE_BUILDING,
    EN_BUFF_TYPE_DRAGON_LV,
    EN_BUFF_TYPE_DRAGON_MONSTER_SKILL, //change
    EN_BUFF_TYPE_LORD_SKILL, //add
    EN_BUFF_TYPE_THRONE_RESEARCH, //add
    EN_BUFF_TYPE_KNIGHT, //add
    EN_BUFF_TYPE_LORD_LV, //add
    EN_BUFF_TYPE_IDOL,
    EN_BUFF_TYPE_END
};

enum EEquipmentStatus //装备状态
{
    EN_EQUIPMENT_STATUS_NORMAL = 0,
    EN_EQUIPMENT_STATUS_UPGRADING = 1, //合成中
    EN_EQUIPMENT_STATUS_ON_DRAGON = 2,//在英雄身上
};

enum EEquipCategory //装备类型
{
    EN_EQUIP_CATEGORY_NORMAL = 0,
    EN_EQUIP_CATEGORY_SOUL = 1,
};

enum EMailSendType
{
    EN_MAIL_SEND_TYPE_PLAYER_TO_PLAYERS = 0,
    EN_MAIL_SEND_TYPE_PLAYER_TO_ALLIANCE,
    EN_MAIL_SEND_TYPE_SYSTEM_TO_PLAYERS,
    EN_MAIL_SEND_TYPE_SYSTEM_TO_ALLIANCE,
    EN_MAIL_SEND_TYPE_PLAYER_TO_SUPPORT,
    EN_MAIL_SEND_TYPE_SUPPORT_TO_PLAYER,
};

enum EChatSysMsgType
{
    EN_CHAT_SYS_MSG_JOIN_TO_ALLIANCE = 0,
    EN_CHAT_SYS_MSG_LEAVE_FROM_ALLIANCE = 1,
    EN_CHAT_SYS_MSG_KICK_FROM_ALLIANCE = 2,
};



enum EMailDisplayType
{
    EN_MAIL_DISPLAY_TYPE_NORMAL = 0,
    EN_MAIL_DISPLAY_TYPE_ALLIANCE,
    EN_MAIL_DISPLAY_TYPE_SYSTEM_NOTICE,
    EN_MAIL_DISPLAY_TYPE_SYSTEM_ACTIVITY,
    EN_MAIL_DISPLAY_TYPE_SYSTEM_ENCOURAGE,
    EN_MAIL_DISPLAY_TYPE_SYSTEM_EVENT,
    EN_MAIL_DISPLAY_TYPE_SYSTEM_HOLIDAY,
    EN_MAIL_DISPLAY_TYPE_SYSTEM_NEW_PLAYER_AL,
    EN_MAIL_DISPLAY_TYPE_ALLIANCE_DIPLOMACY,
    EN_MAIL_DISPLAY_TYPE_ALLIANCE_INVITE,
    EN_MAIL_DISPLAY_TYPE_SUPPORT_HELP,
};

enum EMailTotalListType
{
    EN_MAIL_FLOW,
    EN_MAIL_INTEGRATION,
};

enum EMailOperateStatus
{
    EN_MAIL_STATUS_READ = 0x01,
    EN_MAIL_STATUS_DEL = 0x02,
    EN_MAIL_STATUS_COLLECT = 0x04,
    EN_MAIL_STATUS_MARK = 0x08,
    EN_MAIL_STATUS_DONE = 0x10,
};

enum EDragonStatus
{
    EN_DRAGON_STATUS_NORMAL,
    EN_DRAGON_STATUS_MARCH,
    EN_DRAGON_STATUS_DEAD,
    EN_DRAGON_STATUS_BEING_ESCORT, //被押送中
    EN_DRAGON_STATUS_WAIT_KILL,    //等待杀(不可杀)
    EN_DRAGON_STATUS_WAIT_RELEASE, //等待释放(可杀)
};

enum EMailJmpType
{
    EN_MAIL_JMP_TYPE_NO_JMP,
    EN_MAIL_JMP_TYPE_FACEBOOK,
    EN_MAIL_JMP_TYPE_URL,
    EN_MAIL_JMP_TYPE_GEM_STORE,
    EN_MAIL_JMP_TYPE_EVENT,
    EN_MAIL_JMP_TYPE_ACCOUNT,
    EN_MAIL_JMP_TYPE_HOW_TO_PLAY,
};

enum ERewardWinbdowType
{
    EN_REWARD_WINDOW_TYPE_ONE_CRYSTAL = 0,
    EN_REWARD_WINDOW_TYPE_ONE_MATERIAL = 1,
    EN_REWARD_WINDOW_TYPE_ONE_EQUIP = 3,
    //EN_REWARD_WINDOW_TYPE_ONE_SOUL = 4,
    //EN_REWARD_WINDOW_TYPE_ONE_PARTS = 5,

    EN_REWARD_WINDOW_TYPE_CRYSTAL = 6,
    EN_REWARD_WIMDOW_TYPE_MATERIAL = 7,
    //EN_REWARD_WIMDOW_TYPE_SOUL = 8,
    //EN_REWARD_WIMDOW_TYPE_PARTS = 9,
    //EN_REWARD_WIMDOW_TYPE_ONE_SP_CRYSTAL = 10,
    //EN_REWARD_WIMDOW_TYPE_SP_CRYSTAL = 11,
    EN_REWARD_WIMDOW_TYPE_EQUIP = 12,

    EN_REWARD_WINDOW_TYPE_COMMON = 13,

    EN_REWARD_WINDOW_TYPE_ELITE_MONSTER_KILLED = 14,

    EN_REWARD_WIMDOW_TYPE_CHEST = 15,

    EN_REWARD_WIMDOW_TYPE_LORD_IMAGE = 16,
};

enum ERewardWindowGetType
{
    EN_REWARD_WINDOW_GET_TYPE_OPEN_CHEST = 1,
    EN_REWARD_WINDOW_GET_TYPE_COMPOSE = 2,
    EN_REWARD_WINDOW_GET_TYPE_DESTROY = 3,
    EN_REWARD_WINDOW_GET_TYPE_ELITE_MONSTER = 4,
};
enum EActiveQuestType
{
    /*
        0:不可配置的任务
        1：训练兵
        2：治疗兵
        3：复活兵
        4：攻击玩家城市
        5：攻击玩家采集队伍
        6：发起团战
        7：支援盟友
        8：升级建筑
        9：消耗资源
        10：采集gold资源x
        11：研究科技
        12：升级英雄
        13：攻击怪物
        14: 带兵出征
        15：联盟帮助
        16：请求联盟帮助
        17：联盟商店标记
        18：消耗宝石
        19：使用加速道具
        20: 侦查目标
        21: 强化装备
        22：组合材料
        23：组合水晶
        24：openall材料
        25：训练一级兵x个
        26：训练二级兵x个
        27：训练三级兵x个
        28：训练四级兵x个
        29：训练步兵x个
        30：训练骑兵x个
        31：训练远程兵x个
        32：训练攻城兵x个
        33：采集food资源x
        34：采集wood资源x
        35：采集stone资源x
        36：采集iron资源x
        */
    EN_ACTIVE_QUEST_TYPE__UNCONFIGURE = 0,
    EN_ACTIVE_QUEST_TYPE__TRAIN_TROOP = 1,
    EN_ACTIVE_QUEST_TYPE__TREAT_TROOP = 2,
    EN_ACTIVE_QUEST_TYPE__ALTAR_TROOP = 3,
    EN_ACTIVE_QUEST_TYPE__ATTACK_CITY = 4,
    EN_ACTIVE_QUEST_TYPE__ATTACK_COLLECT_ACTION = 5,
    EN_ACTIVE_QUEST_TYPE__RELLY = 6,
    EN_ACTIVE_QUEST_TYPE__REINFORCE = 7,
    EN_ACTIVE_QUEST_TYPE__UPGRADE_BUILDING = 8,
    EN_ACTIVE_QUEST_TYPE__COST_RESOURCE = 9,
    EN_ACTIVE_QUEST_TYPE__COLLECT_GOLD = 10,
    EN_ACTIVE_QUEST_TYPE__UPGRADE_RESEARCH = 11,
    EN_ACTIVE_QUEST_TYPE__UPGRADE_HERO = 12,
    EN_ACTIVE_QUEST_TYPE__ATTACK_MONSTER = 13,
    EN_ACTIVE_QUEST_TYPE__BATTLE = 14,//use less
    EN_ACTIVE_QUEST_TYPE__SEND_ALLIANCE_HELP = 15,
    EN_ACTIVE_QUEST_TYPE__ASK_ALLIANCE_HELP = 16,
    EN_ACTIVE_QUEST_TYPE__MASK_ALLIANCE_ITEM = 17,
    EN_ACTIVE_QUEST_TYPE__COST_GEM = 18,
    EN_ACTIVE_QUEST_TYPE__COST_SPEED_ITEM = 19,
    EN_ACTIVE_QUEST_TYPE__SCOUT = 20,
    EN_ACTIVE_QUEST_TYPE__UPGRADE_EQUIP = 21,
    EN_ACTIVE_QUEST_TYPE__UPGRADE_MATERIAL = 22,
    EN_ACTIVE_QUEST_TYPE__UPGRADE_CRYSTAL = 23,
    EN_ACTIVE_QUEST_TYPE__OPEN_ALL_MATERIAL = 24,
    EN_ACTIVE_QUEST_TYPE__TRAIN_TIER_1_TROOP = 25,
    EN_ACTIVE_QUEST_TYPE__TRAIN_TIER_2_TROOP = 26,
    EN_ACTIVE_QUEST_TYPE__TRAIN_TIER_3_TROOP = 27,
    EN_ACTIVE_QUEST_TYPE__TRAIN_TIER_4_TROOP = 28,
    EN_ACTIVE_QUEST_TYPE__TRAIN_INFANTRY_TROOP = 29,
    EN_ACTIVE_QUEST_TYPE__TRAIN_SOWAR_TROOP = 30,
    EN_ACTIVE_QUEST_TYPE__TRAIN_REMOTE_TROOP = 31,
    EN_ACTIVE_QUEST_TYPE__TRAIN_SIEGE_TROOP = 32,
    EN_ACTIVE_QUEST_TYPE__COLLECT_FOOD = 33,
    EN_ACTIVE_QUEST_TYPE__COLLECT_WOOD = 34,
    EN_ACTIVE_QUEST_TYPE__COLLECT_STONE = 35,
    EN_ACTIVE_QUEST_TYPE__COLLECT_IRON = 36,

    EN_ACTIVE_QUEST_TYPE_END = 100,
};

enum EActiveQuestStatus
{
    EN_ACTIVE_QUEST_STATUS__UNFINISH = 0,
    EN_ACTIVE_QUEST_STATUS__FINISH = 1,
    EN_ACTIVE_QUEST_STATUS__DONE = 2,
};

enum EScoreType
{
    EN_SCORE_TYPE__UNKNOW = 0,
    EN_SCORE_TYPE__KILL_FORCE,  //击杀兵
    EN_SCORE_TYPE__TRAIN_TROOP,  //训练单位士兵
    EN_SCORE_TYPE__TRAIN_FORT,  //训练城防
    EN_SCORE_TYPE__BUILDING_UPGRADE,
    EN_SCORE_TYPE__RESEARCH_UPGRADE,
    EN_SCORE_TYPE__HEAL_TROOP,
    EN_SCORE_TYPE__KNIGHT_EXP,  //骑士经验
    EN_SCORE_TYPE__HERO_EXP,  //英雄经验
    EN_SCORE_TYPE__SPEED_UP,  //加速
    EN_SCORE_TYPE__BUY_GEM,
    EN_SCORE_TYPE__COST_GEM,
    EN_SCORE_TYPE__EQUIP_UPGRADE,  //强化装备
    EN_SCORE_TYPE__LOTTERY,  //抽奖
    EN_SCORE_TYPE__TRIAL_ATTACK,  //龙的试炼打怪
    EN_SCORE_TYPE__BUY_IAP, //购买iap
    EN_SCORE_TYPE__ATTACK_MONSTER,  //打怪
    EN_SCORE_TYPE__KILL_MONSTER,    //杀死怪

    EN_SCORE_TYPE__RES_COLLECT,

    EN_SCORE_TYPE__END = 50,
};

enum EScoreId
{
    EN_SCORE_ID_KILL_FORCE__CITY_TROOP = 0,
    EN_SCORE_ID_KILL_FORCE__CITY_FORT,
    EN_SCORE_ID_KILL_FORCE__WILD_TROOP,
    EN_SCORE_ID_KILL_FORCE__MAX,

    EN_SCORE_ID_KNIGHT_EXP__MARCH = 0,
    EN_SCORE_ID_KNIGHT_EXP__ITEM,
    EN_SCORE_ID_KNIGHT_EXP__MAX,

    EN_SCORE_ID_HERO_EXP__MARCH = 0,
    EN_SCORE_ID_HERO_EXP__ITEM,
    EN_SCORE_ID_HERO_EXP__RESEARCH,
    EN_SCORE_ID_HERO_EXP__BUILDING,
    EN_SCORE_ID_HERO_EXP__MAX,

    EN_SCORE_ID_SPEED_UP__ITEM = 0,
    EN_SCORE_ID_SPEED_UP__GEM,
    EN_SCORE_ID_SPEED_UP__ALL,
    EN_SCORE_ID_SPEED_UP__MAX,

    EN_SCORE_ID_LOTTERY__ONE_TIME = 0,
    EN_SCORE_ID_LOTTERY__TEN_TIMES,
    EN_SCORE_ID_LOTTERY__MAX,

    EN_SCORE_ID_TRIAL_ATTACK__ONE_TIME = 0,

    EN_SCORE_ID_BUY_IAP__ONE_CENT = 0,

    EN_SCORE_ID__NORMAL = 0,
    EN_SCORE_ID__MAX,
};
enum ELotteryType
{
    EN_LOTTERY_TYPE_NORMAL = 1,
    EN_LOTTERY_TYPE_CAMPAIGN,
    EN_LOTTERY_TYPE_CHEST,
};

enum ENewPlayerFlag
{
    EN_NEW_PLAYER__NORMAL = 0,
    EN_NEW_PLAYER__CREATE,
    EN_NEW_PLAYER__FAKE,
};

enum EEventType
{
    EN_EVENT_TYPE__ALLIANCE = 0,
    EN_EVENT_TYPE__PERSONAL_1, //困难个人
    EN_EVENT_TYPE__PERSONAL_2, //简单个人

    EN_EVENT_TYPE__THEME = 999,
    EN_EVENT_TYPE__END,
};

enum ETaskType
{
    EN_TASK_TYPE_CONSTRUCT_BUILDING = 1,
    EN_TASK_TYPE_UPGRADE_BUILDING,
    EN_TASK_TYPE_UNLOCK_PLACE,
    EN_TASK_TYPE_RESEARCH,
    EN_TASK_TYPE_DAILY_QUEST_FINISH,
    EN_TASK_TYPE_ALLIANCE_QUEST_FINISH,
    EN_TASK_TYPE_VIP_QUEST_FINISH,
    EN_TASK_TYPE_TRAIN_TROOPS,
    EN_TASK_TYPE_TREAT_TROOPS,
    EN_TASK_TYPE_TRAIN_CITYWALL,
    EN_TASK_TYPE_TREAT_CITYWALL,
    EN_TASK_TYPE_VISIT_WORLD_MAP,
    EN_TASK_TYPE_JOIN_ALLIANCE,
    EN_TASK_TYPE_CHECK_MAIL,
    EN_TASK_TYPE_SEND_MAIL,
    EN_TASK_TYPE_CHECK_REPORT,
    EN_TASK_TYPE_USE_ITEMS,
    EN_TASK_TYPE_BUY_GEMS,
    EN_TASK_TYPE_CHANGE_PLAYER_NAME,
    EN_TASK_TYPE_CHANGE_CITY_NAME,
    EN_TASK_TYPE_CHANGE_PLAYER_ICON,
    EN_TASK_TYPE_CHECK_ALLIANCE_HELP,
    EN_TASK_TYPE_ALLIANCE_TRANSPORT,
    EN_TASK_TYPE_ALLIANCE_REINFORCE,
    EN_TASK_TYPE_ALLIANCE_CONSTRUCT,
    EN_TASK_TYPE_ALLIANCE_COMMENT,
    EN_TASK_TYPE_GET_ALLIANCE_CONTRIBUTION,
    EN_TASK_TYPE_SEND_ALLIANCE_MAIL,
    EN_TASK_TYPE_COLLECT_ALLIANCE_GIFT,
    EN_TASK_TYPE_CHECK_WORLD_MAP_TILE,
    EN_TASK_TYPE_GET_RESOURCE,
    EN_TASK_TYPE_GET_ALL_RESOURCE,
    EN_TASK_TYPE_OCCUPY_RESOURCE_PATCH,
    EN_TASK_TYPE_ROB_RESOURCE,
    EN_TASK_TYPE_CHANGE_HERO_ICON,
    EN_TASK_TYPE_CHANGE_HERO_NAME,
    EN_TASK_TYPE_UPGRADE_HERO,
    EN_TASK_TYPE_ASSIGN_HERO_SKILLS,
    EN_TASK_TYPE_HERO_WEAR_EQUIPMENT,
    EN_TASK_TYPE_RAISE_POPULATION,
    EN_TASK_TYPE_INCREASE_HOSPITAL_CAPCITY,
    EN_TASK_TYPE_RESEARCH_SUM,
    EN_TASK_TYPE_ENHANCE_EQUIPMENT,
    EN_TASK_TYPE_MERGE_EQUIPMENT,
    EN_TASK_TYPE_ABSORB_EQUIPMENT,
    EN_TASK_TYPE_INCREASE_RESOURCE_CAPCITY,
    EN_TASK_TYPE_RAISE_ALLIANCE_MARCH_SPEED,
    EN_TASK_TYPE_GET_ALL_KNIGHT,
    EN_TASK_TYPE_UPGRADE_KNIGHT,

    EN_TASK_TYPE_ASSIGN_KNIGHT,
    EN_TASK_TYPE_ASSIGN_KNIGHT_POSITION,
    EN_TASK_TYPE_RAISE_MARCH_SUM,
    EN_TASK_TYPE_RAISE_MARCH_TROOPS,
    EN_TASK_TYPE_INCREASE_FOOD_PRODUCTION,
    EN_TASK_TYPE_INCREASE_WOOD_PRODUCTION,
    EN_TASK_TYPE_INCREASE_STONE_PRODUCTION,
    EN_TASK_TYPE_INCREASE_IRON_PRODUCTION,
    EN_TASK_TYPE_INCREASE_GOLD_PRODUCTION,
    EN_TASK_TYPE_RESOURCE_PRODUCTION_BUFF,
    EN_TASK_TYPE_TROOPS_SUM,
    EN_TASK_TYPE_KILL_TROOPS_SUM,
    EN_TASK_TYPE_GET_GOLD_RESOURCE,
    EN_TASK_TYPE_GET_FOOD_RESOURCE,
    EN_TASK_TYPE_GET_WOOD_RESOURCE,
    EN_TASK_TYPE_GET_STONE_RESOURCE,
    EN_TASK_TYPE_GET_IRON_RESOURCE,
    EN_TASK_TYPE_USE_SPEED_UP_ITEMS,
    EN_TASK_TYPE_USE_RESOURCE_ITEMS,
    EN_TASK_TYPE_OWN_EQUIP_NUM,
    EN_TASK_TYPE_COMPRESS_MATERIAL_NUM,
    EN_TASK_TYPE_BUILDING_NUM,
    EN_TASK_TYPE_USE_GEM_NUM,
    EN_TASK_TYPE_RANDOM_REWARD_RESOURCE_NUM,
    EN_TASK_TYPE_RANDOM_REWARD_GEM_NUM,
    EN_TASK_TYPE_AGE_UPGRADE,
    EN_TASK_TYPE_VIP_UPGRADE,
    EN_TASK_TYPE_EDIT_CITY,//编辑地块
    EN_TASK_TYPE_ALLIANCE_CHAT,

    //悬赏用task id
    EN_TASK_TYPE_ING_BUILDING_NUM,
    EN_TASK_TYPE_ING_BUILD_X_LV_BUILDING,
    EN_TASK_TYPE_ING_RESEARCH_TIME,
    EN_TASK_TYPE_ING_TROOP_TRAIN_NUM,
    EN_TASK_TYPE_ING_FORT_TRAIN_NUM,
    EN_TASK_TYPE_ING_SCOUT_CITY_NUM,
    EN_TASK_TYPE_ING_ATTACK_CITY_NUM,
    EN_TASK_TYPE_ING_KILL_TROP_NUM,
    EN_TASK_TYPE_ING_KILL_FORT_NUM,
    EN_TASK_TYPE_ING_ADD_HERO_EXP,
    EN_TASK_TYPE_ING_COMPOSE_EQUIP,
    EN_TASK_TYPE_ING_GET_RESOURCE,
    EN_TASK_TYPE_ING_KILL_MONSTER,
    EN_TASK_TYPE_ING_KILL_HERO,
    EN_TASK_TYPE_ING_REINFORCE_NUM, 
    EN_TASK_TYPE_ING_TRANSPORT_NUM,
    EN_TASK_TYPE_ING_BEEN_KING,
    EN_TASK_TYPE_ING_BEEN_PROVINCE_OWNER,
    EN_TASK_TYPE_END = 100,
};

enum ETaskOperateType
{
    EN_TASK_OPERATE_TYPE_MAP,
    EN_TASK_OPERATE_TYPE_CHECK_MAIL,
    EN_TASK_OPERATE_TYPE_CHECK_REPORT,
    EN_TASK_OPERATE_TYPE_GET_AL_HELP,
    EN_TASK_OPERATE_TYPE_MAP_TITLE,
    EN_TASK_OPERATE_TYPE_ALLIANCE_CHAT,
};

enum EUniqueNameType
{
    EN_ALLIANCE_NAME = 0,
    EN_ALLIANCE_NICK_NAME = 1,
    EN_PLAYER_NAME = 2,
    EN_DRAGON_NAME = 3,
    EN_CITY_NAME = 4,
};

enum EActionType
{
    EN_ACTION_TYPE_BUFF_NORMAL = 0,
    EN_ACTION_TYPE_AL_CAN_HELP = 1,
    EN_ACTION_TYPE_MARCH = 2,
};


enum EBuffProperty
{
    EN_BUFF_PROPERTY__MARCH = 0,
    EN_BUFF_PROPERTY__ECONOMICS,
    EN_BUFF_PROPERTY__OTHER,
    EN_BUFF_PROPERTY__DRAGON,
    EN_BUFF_PROPERTY__FORT,
};

enum EPurchaseAbility
{
    EN_PURCHASE_ABILITY__LV0 = 0,   //没消费过
    EN_PURCHASE_ABILITY__LV1,       //买过4.99
    EN_PURCHASE_ABILITY__LV2,       //买过49.99
    EN_PURCHASE_ABILITY__LV3,       //买过99.99
    EN_PURCHASE_ABILITY__END,
};

enum EAllianceThroneStatus
{
    EN_ALLIANCE_THRONE_STATUS_NONE = 0,
    EN_ALLIANCE_THRONE_STATUS_FIGHTING,
    EN_ALLIANCE_THRONE_STATUS_OCCUPY,
};

enum EPrisonResult
{
    EN_PRISON_RESULT_ESCAPE,
    EN_PRISON_RESULT_BE_KILLED,
    EN_PRISON_RESULT_BE_RELEASED,
};


enum EAccountStatus
{
    EN_ACCOUNT_STATUS_NORMAL,
    EN_ACCOUNT_STATUS_CREATE_AND_BIND,
    EN_ACCOUNT_STATUS_BIND,
};

enum ENoticTaskIndex
{
    EN_TOP_QUEST = 0,
    EN_DAILY_QUEST,
    EN_ALLIANCE_QUEST,
    EN_MISTERY_QUEST,
    EN_VIP_QUEST,
    EN_PLAYER_LEVEL_UP,
    EN_PEACETIME_OVER,
    EN_NEW_PLAYER_PROTECT,
    EN_BUILDING_FREE,
    EN_RESEARCH_FREE,
    EN_REMOVE_FREE,
};

enum ETaskShowStatus
{
    EN_TASK_SHOW_STATUS_NORMAL,//无标记
    EN_TASK_SHOW_STATUS_ADD,//加号
    EN_TASK_SHOW_STATUS_CHECK,//打勾
    EN_TASK_SHOW_STATUS_RECOMMAND_CAN_START,
};

enum ENewPlayerAlStatus
{
    EN_NEW_PLAYER_AL_STATUS__QUIT = 0,
    EN_NEW_PLAYER_AL_STATUS__JOIN,
    EN_NEW_PLAYER_AL_STATUS__NOT_JOIN,
};

enum EBroadcastCategory
{
    EN_BROADCAST_CATEGORY__PRIMARY = 0,
    EN_BROADCAST_CATEGORY__MEDIUM,
    EN_BROADCAST_CATEGORY__HIGH_THRONE,
    EN_BROADCAST_CATEGORY__HIGH_PROVINCE,
};

enum EBroadcastStrategy
{
    EN_BROADCAST_STRATEGY__REAL_TIME = 0,
};

enum EBroadcastTarget
{
    EN_BROADCAST_TARGET__ENTILE_GAME = 0, //不支持
    EN_BROADCAST_TARGET__SERVER,
    EN_BROADCAST_TARGET__PLAYER, //不支持
};

enum EBroadcastContentId
{
    EN_BROADCAST_CONTENT_ID__THRONE_PEACE_TIME_END = 1, 
    EN_BROADCAST_CONTENT_ID__OCCUPY_THRONE_ENTIRE = 2, //alname
    EN_BROADCAST_CONTENT_ID__BECOME_KING = 3, //uname
    EN_BROADCAST_CONTENT_ID__DUB_TITLE = 4, //uname title_id

    EN_BROADCAST_CONTENT_ID__END,
};

enum ETradeStatus
{
    EN_TRADE_STATUS__NORMAL = 0,
    EN_TRADE_STATUS__MARCHING,
    EN_TRADE_STATUS__STAY,
    EN_TRADE_STATUS__RECEPTION,
    EN_TRADE_STATUS__NOT_RECEPTION,
    EN_TRADE_STATUS__END,
};

enum EAdsType
{
    EN_ADS_TYPE__ALLIANCE = 0,
    EN_ADS_TYPE__IAP,
    EN_ADS_TYPE__EVENT,
};

enum EPridictStatus
{
    EN_PRIDICT_STATUS__3_1 = 0,  //三天前第一次预告
    EN_PRIDICT_STATUS__3_2,
    EN_PRIDICT_STATUS__3_3,

    EN_PRIDICT_STATUS__2_1,     //两天前第一次预告
    EN_PRIDICT_STATUS__2_2,
    EN_PRIDICT_STATUS__2_3,
    EN_PRIDICT_STATUS__2_4,

    EN_PRIDICT_STATUS__1_1,     //一天前第一次预告
    EN_PRIDICT_STATUS__1_2,
    EN_PRIDICT_STATUS__1_3,
    EN_PRIDICT_STATUS__1_4,
    EN_PRIDICT_STATUS__1_5,
    EN_PRIDICT_STATUS__1_6,
    EN_PRIDICT_STATUS__1_7,
    EN_PRIDICT_STATUS__1_8,
    EN_PRIDICT_STATUS__1_9,
    EN_PRIDICT_STATUS__1_10,
    EN_PRIDICT_STATUS__1_11,
    EN_PRIDICT_STATUS__1_12,

    EN_PRIDICT_STATUS__END,
};

enum EFuncOpenType
{
    /*
    0 - 贸易
    1 - 成就
    2 - 神秘商店
    3 - 神秘商店购买兵
    4 - 主场景气泡
    5 - 税收
    6 - 建筑顶级加成
    */
    EN_FUNC_OPEN_TYPE_TRADE,
    EN_FUNC_OPEN_TYPE_BOUNTY,
    EN_FUNC_OPEN_TYPE_MISTERY_STORE,
    EN_FUNC_OPEN_TYPE_MISTERY_STORE_TROOP,
    EN_FUNC_OPEN_TYPE_SECNE_BUBBLE,
    EN_FUNC_OPEN_TYPE_TAX,
    EN_FUNC_OPEN_TYPE_TOP_BUFF,
};

enum EHelpBubbleStatus
{
    EN_HELP_BUBBLE_STATUS_OFF,  //关闭气泡
    EN_HELP_BUBBLE_STATUS_ON,  //开启气泡
};

enum ESupportStatus
{
    EN_SUPPORT_STATUS__NORMAL,  //无事
    EN_SUPPORT_STATUS__NEED_SUPPORT,  //未处理
    EN_SUPPORT_STATUS__SUPPORTING,  //正在处理
};

enum ERefreshDataType
{
    EN_REFRESH_DATA_TYPE__QUEST = 0,
    EN_REFRESH_DATA_TYPE__MISTERY_GIFT,
    EN_REFRESH_DATA_TYPE__TRADE_MARKET,
    EN_REFRESH_DATA_TYPE__MISTERY_STORE,
    EN_REFRESH_DATA_TYPE__AL_GIFT,
    EN_REFRESH_DATA_TYPE__CHEST,
    EN_REFRESH_DATA_TYPE__MONSTER,
    EN_REFRESH_DATA_TYPE__OCCUPY,
    EN_REFRESH_DATA_TYPE__AL_GIFT_NEW   = 8,
    EN_REFRESH_DATA_TYPE__EQUIP_COMPOSE = 9,
    EN_REFRESH_DATA_TYPE__EQUIP_DESTROY = 10,
    EN_REFRESH_DATA_TYPE__TRIAL         = 11,
    EN_REFRESH_DATA_TYPE__GLOBAL_GIFT   = 12,
    EN_REFRESH_DATA_TYPE__END,
};

enum EDataRefreshReqType
{
    EN_REFRESH_DATA_REQ_TYPE__QUEST_ALL = 0,

    EN_REFRESH_DATA_REQ_TYPE__TRADE_MARKET_ALL = 0,

    EN_REFRESH_DATA_REQ_TYPE__MISTERY_STORE_ALL = 0,
	
    EN_REFRESH_DATA_REQ_TYPE__ALLIANCE_GIFT_ALL = 1,
	
    EN_REFRESH_DATA_REQ_TYPE__MISTERY_GIFT_ALL = 0,
};

enum ELockIdGenType
{
    EN_LOCK_ID_TYPE__UID,
    EN_LOCK_ID_TYPE__AID,
    EN_LOCK_ID_TYPE__TASK_ID,
    EN_LOCK_ID_TYPE__WILD,
    EN_LOCK_ID_TYPE__THRONE,
};

enum EThroneResearchId
{
    EN_THRONE_RESEARCH_ID__BEGIN = 0,

    EN_THRONE_RESEARCH_ID__DRAGON_UNLOCK_1 = 0,
    //todo
    EN_THRONE_RESEARCH_ID__END = 30,
};

enum EKnightsPos
{
    EN_KNIGHT_POS__UNASSIGN = 0,
    EN_KNIGHT_POS__RESOURCE,    // increase resource production
    EN_KNIGHT_POS__BUILDING,    // 
    EN_KNIGHT_POS__RESEARCH,	// increase research speed
    EN_KNIGHT_POS__TROOP,		// increase training speed, attack and life of defenders  
    
    EN_KNIGHT_POS__END,
};

enum EKnightStatus
{
    EN_KNIGHT_STATUS__NORMAL = 0,
    EN_KNIGHT_STATUS__MARCHING,
    EN_KNIGHT_STATUS__ASSIGNING,
    EN_KNIGHT_STATUS__DEAD,
    EN_KNIGHT_STATUS__REVIVING,
    EN_KNIGHT_STATUS__END,
};

enum ETrialMode
{
    EN_TRIAL_MODE__NORMAL = 0,
    EN_TRIAL_MODE__RAGE
};

enum EBuildingCategory
{
    EN_BUILDING_CATEGORY__OUT_CITY = 0,
    EN_BUILDING_CATEGORY__IN_CITY = 1,
    EN_BUILDING_CATEGORY__SPECIAL = 3,
    EN_BUILDING_CATEGORY__DRAGON = 4,
};

enum EThroneStatus
{
    EN_THRONE_STATUS__UNKNOWN = 0,
    EN_THRONE_STATUS__PEACE_TIME,
    EN_THRONE_STATUS__QUIET_PERIOD,
    EN_THRONE_STATUS__CONTEST_PERIOD,
};

enum EIdolStatus
{
    EN_IDOL_STATUS__UNKNOWN = 0,
    EN_IDOL_STATUS__BUFF_PERIOD,
    EN_IDOL_STATUS__QUIET_PERIOD,
    EN_IDOL_STATUS__CONTEST_PERIOD,
    EN_IDOL_STATUS__THRONE_PEACE_TIME,
};

#endif
